/**
 * Supplementary questions.
 *
 * The scheme needs 18 unique MCQs and 24 unique shorts per paper.
 * The base banks were short of that for several subjects, which caused
 * repeats inside a single paper. This file tops every subject up past
 * those thresholds. Merged in by examScheme.ts.
 */

import type { BankMCQ2, BankShort2, BankNumerical, Level } from "./examBank";

const B: Level = "both";
const I: Level = "inter";

export const EXTRA_MCQS: Record<string, BankMCQ2[]> = {
  physics: [
    { question: "The SI unit of frequency is the:", options: ["Hertz", "Second", "Metre", "Newton"], correctIndex: 0, explanation: "1 Hz = 1 cycle per second.", level: B, topic: "Waves" },
    { question: "A body moving with uniform velocity has an acceleration of:", options: ["Zero", "9.8 m/s^2", "Constant non-zero", "Infinite"], correctIndex: 0, explanation: "Uniform velocity means no change in speed or direction, so a = 0.", level: B, topic: "Kinematics" },
    { question: "The density of water at 4 C is:", options: ["1000 kg/m^3", "100 kg/m^3", "1 kg/m^3", "10000 kg/m^3"], correctIndex: 0, explanation: "Water has its maximum density of 1000 kg m^-3 (1 g/cm^3) at 4 C.", level: B, topic: "Matter" },
    { question: "Pressure exerted by a liquid column of height h is:", options: ["rho g h", "rho g / h", "h / rho g", "rho h / g"], correctIndex: 0, explanation: "P = rho g h, independent of the cross-sectional area.", level: B, topic: "Pressure" },
    { question: "The image formed by a plane mirror is always:", options: ["Virtual and erect", "Real and inverted", "Real and erect", "Virtual and inverted"], correctIndex: 0, explanation: "A plane mirror forms a virtual, erect image of the same size behind the mirror.", level: B, topic: "Light" },
    { question: "1 kilowatt-hour is equal to:", options: ["3.6 x 10^6 J", "1000 J", "3600 J", "10^5 J"], correctIndex: 0, explanation: "1 kWh = 1000 W x 3600 s = 3.6 x 10^6 J.", level: B, topic: "Work and Energy" },
    { question: "The angle of incidence equals the angle of reflection. This is:", options: ["The second law of reflection", "Snell's law", "Huygens' principle", "The law of refraction"], correctIndex: 0, explanation: "Both angles are measured from the normal and lie in the same plane.", level: B, topic: "Light" },
    { question: "The unit of magnetic flux density is the:", options: ["Tesla", "Weber", "Henry", "Farad"], correctIndex: 0, explanation: "1 T = 1 Wb m^-2.", level: I, topic: "Electromagnetism" },
  ],
  chemistry: [
    { question: "The formula of sulphuric acid is:", options: ["H2SO4", "HNO3", "HCl", "H2CO3"], correctIndex: 0, explanation: "Sulphuric acid is a dibasic strong mineral acid.", level: B, topic: "Acids and Bases" },
    { question: "The most abundant gas in the Earth's atmosphere is:", options: ["Nitrogen", "Oxygen", "Carbon dioxide", "Argon"], correctIndex: 0, explanation: "Nitrogen makes up about 78% of air by volume.", level: B, topic: "Environmental Chemistry" },
    { question: "One mole of any gas at STP occupies a volume of:", options: ["22.4 dm^3", "11.2 dm^3", "24 dm^3", "1 dm^3"], correctIndex: 0, explanation: "This is the molar volume of an ideal gas at 273 K and 1 atm.", level: B, topic: "Gases" },
    { question: "Which of the following is an alkali metal?", options: ["Sodium", "Calcium", "Aluminium", "Iron"], correctIndex: 0, explanation: "Group 1 elements are the alkali metals.", level: B, topic: "Periodic Table" },
    { question: "Rusting of iron is an example of:", options: ["Oxidation", "Reduction", "Neutralisation", "Sublimation"], correctIndex: 0, explanation: "Iron loses electrons in the presence of oxygen and moisture to form hydrated iron(III) oxide.", level: B, topic: "Redox" },
    { question: "The pH of a strongly acidic solution is closest to:", options: ["1", "7", "10", "14"], correctIndex: 0, explanation: "The lower the pH below 7, the more acidic the solution.", level: B, topic: "Acids and Bases" },
    { question: "Which process is used to separate two miscible liquids with different boiling points?", options: ["Fractional distillation", "Filtration", "Sublimation", "Decantation"], correctIndex: 0, explanation: "The fractionating column separates components by their boiling points.", level: B, topic: "Separation Techniques" },
    { question: "The valency of carbon is:", options: ["4", "2", "3", "1"], correctIndex: 0, explanation: "Carbon has four valence electrons and forms four covalent bonds.", level: B, topic: "Organic Chemistry" },
  ],
  math: [
    { question: "The additive inverse of -7 is:", options: ["7", "-7", "1/7", "0"], correctIndex: 0, explanation: "a + (-a) = 0, so the additive inverse of -7 is 7.", level: B, topic: "Real Numbers" },
    { question: "The value of tan 45 degrees is:", options: ["1", "0", "sqrt(3)", "1/sqrt(3)"], correctIndex: 0, explanation: "tan 45 = sin 45 / cos 45 = 1.", level: B, topic: "Trigonometry" },
    { question: "If a matrix has the same number of rows and columns it is called:", options: ["A square matrix", "A row matrix", "A null matrix", "A diagonal matrix"], correctIndex: 0, explanation: "An n x n matrix is a square matrix of order n.", level: B, topic: "Matrices" },
    { question: "The midpoint of the line joining (2, 4) and (6, 8) is:", options: ["(4, 6)", "(8, 12)", "(2, 2)", "(3, 5)"], correctIndex: 0, explanation: "Midpoint = ((x1+x2)/2, (y1+y2)/2) = (4, 6).", level: B, topic: "Coordinate Geometry" },
    { question: "The perimeter of a rectangle of length l and width w is:", options: ["2(l + w)", "l x w", "l + w", "4l"], correctIndex: 0, explanation: "Perimeter is the sum of all four sides.", level: B, topic: "Mensuration" },
    { question: "If 2^x = 32, then x equals:", options: ["5", "4", "6", "16"], correctIndex: 0, explanation: "2^5 = 32.", level: B, topic: "Indices" },
    { question: "The conjugate of the complex number 3 + 4i is:", options: ["3 - 4i", "-3 + 4i", "4 + 3i", "-3 - 4i"], correctIndex: 0, explanation: "The conjugate changes the sign of the imaginary part.", level: I, topic: "Complex Numbers" },
    { question: "The derivative of a constant is:", options: ["0", "1", "The constant itself", "Undefined"], correctIndex: 0, explanation: "A constant does not change, so its rate of change is zero.", level: I, topic: "Differentiation" },
  ],
  islam: [
    { question: "The number of Surahs in the Holy Quran is:", options: ["114", "110", "120", "104"], correctIndex: 0, explanation: "The Quran contains 114 Surahs revealed over 23 years.", level: B, topic: "Quran" },
    { question: "Hazrat Muhammad (PBUH) was born in the year:", options: ["571 CE", "610 CE", "622 CE", "632 CE"], correctIndex: 0, explanation: "He was born in the Year of the Elephant, 571 CE, in Makkah.", level: B, topic: "Seerat" },
    { question: "The first Caliph of Islam was:", options: ["Hazrat Abu Bakr (RA)", "Hazrat Umar (RA)", "Hazrat Usman (RA)", "Hazrat Ali (RA)"], correctIndex: 0, explanation: "Hazrat Abu Bakr Siddique (RA) was elected as the first Caliph in 632 CE.", level: B, topic: "Khilafat" },
    { question: "Fasting in the month of Ramadan is:", options: ["Farz", "Sunnah", "Nafl", "Mustahab"], correctIndex: 0, explanation: "Sawm is the fourth pillar of Islam and is obligatory on every adult Muslim.", level: B, topic: "Ibadat" },
    { question: "The Battle of Badr was fought in:", options: ["2 A.H.", "3 A.H.", "5 A.H.", "8 A.H."], correctIndex: 0, explanation: "It was the first decisive battle of Islam, fought in 2 A.H.", level: B, topic: "Ghazwat" },
    { question: "How many times is Zakat mentioned along with Salat in the Quran?", options: ["Frequently, over 30 times", "Only once", "Twice", "Never"], correctIndex: 0, explanation: "Salat and Zakat are repeatedly mentioned together, showing their linked importance.", level: B, topic: "Ibadat" },
    { question: "The Quran was compiled in book form during the caliphate of:", options: ["Hazrat Abu Bakr (RA)", "Hazrat Umar (RA)", "Hazrat Ali (RA)", "Hazrat Muawiya (RA)"], correctIndex: 0, explanation: "Compilation began under Hazrat Abu Bakr (RA) and standard copies were issued by Hazrat Usman (RA).", level: B, topic: "Quran" },
    { question: "'Khatam-un-Nabiyyin' means:", options: ["The last of the Prophets", "The first Prophet", "A messenger", "A companion"], correctIndex: 0, explanation: "Hazrat Muhammad (PBUH) is the final Prophet; no prophet will come after him.", level: B, topic: "Aqaid" },
    { question: "Hajj is obligatory on a Muslim who is:", options: ["Financially and physically able", "Above 60 years old", "A scholar", "Living in Arabia"], correctIndex: 0, explanation: "Hajj is farz once in a lifetime on every sane adult Muslim who can afford it.", level: B, topic: "Ibadat" },
    { question: "The Treaty of Hudaibiya was signed in:", options: ["6 A.H.", "2 A.H.", "8 A.H.", "10 A.H."], correctIndex: 0, explanation: "Though apparently unfavourable, the Quran called it a clear victory.", level: B, topic: "Seerat" },
  ],
  english: [
    { question: "Choose the correct synonym of 'benevolent'.", options: ["Kind", "Cruel", "Lazy", "Angry"], correctIndex: 0, explanation: "Benevolent means well-meaning and kindly.", level: B, topic: "Vocabulary" },
    { question: "Fill in the blank: 'She insisted ___ going home early.'", options: ["on", "at", "for", "to"], correctIndex: 0, explanation: "The verb 'insist' is followed by the preposition 'on'.", level: B, topic: "Prepositions" },
    { question: "Choose the correct plural of 'phenomenon'.", options: ["Phenomena", "Phenomenons", "Phenomenae", "Phenomenon"], correctIndex: 0, explanation: "Greek-origin nouns ending in -on form plurals in -a.", level: B, topic: "Grammar" },
    { question: "Identify the tense: 'She has been reading for two hours.'", options: ["Present perfect continuous", "Present continuous", "Past perfect", "Simple present"], correctIndex: 0, explanation: "'Has been + verb-ing' is the present perfect continuous tense.", level: B, topic: "Tenses" },
    { question: "Choose the correctly spelt word.", options: ["Conscientious", "Concientious", "Conscientous", "Consciencious"], correctIndex: 0, explanation: "The correct spelling is c-o-n-s-c-i-e-n-t-i-o-u-s.", level: B, topic: "Spelling" },
    { question: "The idiom 'to let the cat out of the bag' means:", options: ["To reveal a secret", "To buy a pet", "To run away", "To make noise"], correctIndex: 0, explanation: "It means to disclose something that was meant to be kept hidden.", level: B, topic: "Idioms" },
  ],
  urdu: [
    { question: "'شکوہ' اور 'جوابِ شکوہ' کس شاعر کی نظمیں ہیں؟", options: ["علامہ اقبال", "میر تقی میر", "غالب", "جوش ملیح آبادی"], correctIndex: 0, explanation: "یہ دونوں نظمیں بانگِ درا میں شامل ہیں۔", level: B, topic: "شاعری" },
    { question: "اردو کا پہلا صاحبِ دیوان شاعر کون ہے؟", options: ["قلی قطب شاہ", "ولی دکنی", "میر تقی میر", "سودا"], correctIndex: 0, explanation: "محمد قلی قطب شاہ کو اردو کا پہلا صاحبِ دیوان شاعر مانا جاتا ہے۔", level: B, topic: "تاریخِ ادب" },
    { question: "'مرثیہ' کس موضوع پر لکھا جاتا ہے؟", options: ["کسی کی وفات پر رنج و غم", "محبت", "بہار", "طنز و مزاح"], correctIndex: 0, explanation: "اردو میں مرثیہ خاص طور پر کربلا کے شہدا سے منسوب ہے۔", level: B, topic: "اصنافِ سخن" },
    { question: "لفظ 'خوش نصیب' میں 'خوش' کیا ہے؟", options: ["سابقہ", "لاحقہ", "فعل", "حرفِ ربط"], correctIndex: 0, explanation: "لفظ کے شروع میں آنے والا جزو سابقہ کہلاتا ہے۔", level: B, topic: "قواعد" },
    { question: "'دیوان' سے کیا مراد ہے؟", options: ["غزلوں کا مجموعہ بہ ترتیبِ حروفِ تہجی", "نثری کتاب", "ناول", "سفرنامہ"], correctIndex: 0, explanation: "دیوان میں غزلیں ردیف کے اعتبار سے مرتب ہوتی ہیں۔", level: B, topic: "اصنافِ سخن" },
    { question: "'انشائیہ' کی سب سے بڑی خصوصیت کیا ہے؟", options: ["ذاتی انداز اور بے تکلفی", "تاریخی حقائق", "سائنسی دلائل", "مکالمے"], correctIndex: 0, explanation: "انشائیہ میں مصنف اپنی شخصیت اور ذاتی رنگ نمایاں کرتا ہے۔", level: B, topic: "نثری اصناف" },
  ],
};

export const EXTRA_SHORTS: Record<string, BankShort2[]> = {
  physics: [
    { question: "Define velocity and acceleration.", modelAnswer: "Velocity is the rate of change of displacement, a vector quantity with SI unit m s^-1. Acceleration is the rate of change of velocity, a vector with SI unit m s^-2. A body accelerates if its speed changes, its direction changes, or both.", level: B, topic: "Kinematics" },
    { question: "State Newton's third law of motion with an example.", modelAnswer: "To every action there is an equal and opposite reaction, and the two forces act on different bodies. Example: when a swimmer pushes the water backwards with his hands (action), the water pushes him forwards with an equal force (reaction), which propels him ahead. Rocket propulsion works on the same principle.", level: B, topic: "Force and Motion" },
    { question: "Define density and give its SI unit.", modelAnswer: "Density is the mass per unit volume of a substance, rho = m/V. Its SI unit is kg m^-3. Water has a density of 1000 kg m^-3 at 4 C. A body floats in a liquid if its density is less than that of the liquid.", level: B, topic: "Matter" },
    { question: "What is atmospheric pressure? Name the instrument used to measure it.", modelAnswer: "Atmospheric pressure is the pressure exerted by the weight of the column of air above a unit area of the Earth's surface. At sea level it is about 101325 Pa (760 mm of mercury). It is measured by a barometer; a Fortin barometer or aneroid barometer is used, and its variation helps in weather forecasting.", level: B, topic: "Pressure" },
    { question: "State Archimedes' principle.", modelAnswer: "When a body is wholly or partially immersed in a fluid, it experiences an upthrust equal to the weight of the fluid displaced by it. Upthrust = weight of displaced fluid = rho g V. This explains why a body floats when the upthrust equals its weight and sinks when its weight exceeds the upthrust.", level: B, topic: "Pressure" },
    { question: "Differentiate between heat and temperature.", modelAnswer: "Heat is the total thermal energy transferred from a hotter to a colder body because of a temperature difference; it is measured in joules and depends on the mass of the body. Temperature is the degree of hotness or coldness, a measure of the average kinetic energy of the molecules; it is measured in kelvin or Celsius and does not depend on mass.", level: B, topic: "Heat" },
    { question: "What is meant by the term 'efficiency' of a machine?", modelAnswer: "Efficiency is the ratio of the useful output work or energy to the total input work or energy, usually expressed as a percentage: efficiency = (output/input) x 100. No real machine is 100% efficient because some energy is always lost as heat and sound due to friction and air resistance.", level: B, topic: "Work and Energy" },
    { question: "State the laws of reflection of light.", modelAnswer: "(1) The incident ray, the reflected ray and the normal at the point of incidence all lie in the same plane. (2) The angle of incidence is equal to the angle of reflection, both measured from the normal. These laws hold for both plane and curved mirrors.", level: B, topic: "Light" },
    { question: "Define the terms 'frequency' and 'wavelength' of a wave.", modelAnswer: "Frequency is the number of complete waves passing a point in one second, measured in hertz (Hz). Wavelength is the distance between two consecutive crests or troughs, or between any two successive points in the same phase, measured in metres. They are related to speed by v = f x lambda.", level: B, topic: "Waves" },
    { question: "What is an echo? State one condition for hearing it.", modelAnswer: "An echo is the repetition of sound produced by the reflection of sound waves from a hard surface such as a cliff or wall. To hear a distinct echo the reflecting surface must be at least 17 m away, because the human ear retains a sound sensation for 0.1 s and sound travels about 34 m (there and back) in that time at 340 m s^-1.", level: B, topic: "Sound" },
  ],
  chemistry: [
    { question: "Define a chemical reaction and give one example.", modelAnswer: "A chemical reaction is a process in which the atoms of one or more substances are rearranged to form new substances with different properties. It is accompanied by energy change, colour change, gas evolution or precipitate formation. Example: 2H2 + O2 -> 2H2O, in which hydrogen burns in oxygen to form water.", level: B, topic: "Basic Concepts" },
    { question: "What is a solution? Name its two components.", modelAnswer: "A solution is a homogeneous mixture of two or more substances whose composition is uniform throughout. Its components are the solute (the substance present in smaller amount that dissolves, e.g. salt) and the solvent (the substance present in larger amount that does the dissolving, e.g. water, the universal solvent).", level: B, topic: "Solutions" },
    { question: "Differentiate between a physical and a chemical change.", modelAnswer: "In a physical change no new substance is formed, the change is usually reversible and only the physical state or appearance alters, e.g. melting of ice, dissolving of sugar. In a chemical change a new substance with different properties is formed, the change is usually irreversible and is accompanied by an energy change, e.g. burning of paper, rusting of iron.", level: B, topic: "Basic Concepts" },
    { question: "What is the octet rule?", modelAnswer: "The octet rule states that atoms tend to gain, lose or share electrons so as to attain eight electrons in their outermost shell, achieving the stable electronic configuration of the nearest noble gas. Hydrogen and lithium follow the duplet rule, needing only two electrons. Exceptions include BF3 and PCl5.", level: B, topic: "Chemical Bonding" },
    { question: "Define allotropy and give one example.", modelAnswer: "Allotropy is the existence of an element in two or more different physical forms in the same physical state, differing in the arrangement of atoms. Example: carbon exists as diamond (tetrahedral, hardest known substance, non-conductor) and graphite (layered hexagonal, soft, good conductor of electricity), and also as fullerene.", level: B, topic: "Periodic Table" },
    { question: "What is meant by the term 'salt' in chemistry?", modelAnswer: "A salt is an ionic compound formed when the hydrogen ion of an acid is replaced by a metal ion or an ammonium ion, generally produced by the neutralisation of an acid with a base: acid + base -> salt + water. Example: HCl + NaOH -> NaCl + H2O. Salts may be neutral, acidic or basic depending on the parent acid and base.", level: B, topic: "Acids and Bases" },
    { question: "Explain the difference between a strong and a weak acid.", modelAnswer: "A strong acid ionises almost completely in aqueous solution to give a high concentration of H+ ions, so it has a very low pH and high electrical conductivity, e.g. HCl, H2SO4, HNO3. A weak acid ionises only partially, establishing an equilibrium, so it gives fewer H+ ions, has a higher pH and lower conductivity, e.g. acetic acid and carbonic acid.", level: B, topic: "Acids and Bases" },
    { question: "What is meant by water of crystallisation?", modelAnswer: "Water of crystallisation is the fixed number of water molecules chemically combined with each formula unit of a salt in its crystalline form. Such salts are called hydrated salts, e.g. CuSO4.5H2O (blue vitriol) and Na2CO3.10H2O (washing soda). On heating, the water is driven off and the salt becomes anhydrous, often with a colour change.", level: B, topic: "Solutions" },
    { question: "Define electrolysis.", modelAnswer: "Electrolysis is the process of decomposing an ionic compound in the molten state or in aqueous solution by passing a direct electric current through it. Cations migrate to the cathode and are reduced by gaining electrons, while anions migrate to the anode and are oxidised by losing electrons. It is used in electroplating and in the extraction of reactive metals such as aluminium.", level: B, topic: "Electrochemistry" },
    { question: "What are the harmful effects of acid rain?", modelAnswer: "Acid rain forms when oxides of sulphur and nitrogen from burning fossil fuels dissolve in rainwater to form sulphuric and nitric acids, lowering the pH below 5.6. It damages the leaves and roots of plants, lowers crop yield, acidifies lakes and kills fish and aquatic life, leaches essential minerals from soil, corrodes metal structures, and erodes marble buildings such as monuments.", level: B, topic: "Environmental Chemistry" },
  ],
  math: [
    { question: "Define a rational and an irrational number with one example of each.", modelAnswer: "A rational number can be expressed in the form p/q where p and q are integers and q is not zero; its decimal expansion terminates or recurs, e.g. 3/4 = 0.75, 1/3 = 0.333... An irrational number cannot be written as p/q and its decimal expansion is non-terminating and non-recurring, e.g. sqrt(2) = 1.41421..., pi = 3.14159...", level: B, topic: "Real Numbers" },
    { question: "Factorise: x^2 - 16.", modelAnswer: "This is a difference of two squares of the form a^2 - b^2 = (a - b)(a + b). Here a = x and b = 4, since 16 = 4^2. Therefore x^2 - 16 = (x - 4)(x + 4).", level: B, topic: "Factorisation" },
    { question: "Find the H.C.F. and L.C.M. of 12 and 18.", modelAnswer: "Prime factorisation: 12 = 2^2 x 3 and 18 = 2 x 3^2. H.C.F. is the product of the lowest powers of common factors = 2 x 3 = 6. L.C.M. is the product of the highest powers of all factors = 2^2 x 3^2 = 36. Verification: H.C.F. x L.C.M. = 6 x 36 = 216 = 12 x 18.", level: B, topic: "Number Theory" },
    { question: "Define a function and give an example.", modelAnswer: "A function f from set A to set B is a relation that assigns to each element of A exactly one element of B. A is the domain and the set of images is the range. Example: f(x) = 2x + 1 assigns to each real number x a unique value; f(3) = 7. A relation is a function only if no element of the domain has two different images.", level: B, topic: "Functions" },
    { question: "State the remainder theorem.", modelAnswer: "If a polynomial p(x) is divided by a linear factor (x - a), then the remainder is p(a). For example, dividing p(x) = x^2 + 3x - 4 by (x - 1) gives remainder p(1) = 1 + 3 - 4 = 0. Since the remainder is zero, (x - 1) is a factor, which is the factor theorem.", level: B, topic: "Polynomials" },
    { question: "Convert 45 degrees into radians.", modelAnswer: "180 degrees = pi radians, so 1 degree = pi/180 radians. Therefore 45 degrees = 45 x pi/180 = pi/4 radians, which is approximately 0.7854 radians.", level: B, topic: "Trigonometry" },
    { question: "What is the difference between permutation and combination?", modelAnswer: "A permutation is an arrangement of objects in which the order matters, given by nPr = n!/(n-r)!. A combination is a selection in which order does not matter, given by nCr = n!/[r!(n-r)!]. For example, arranging 3 books on a shelf from 5 is a permutation, whereas choosing 3 books from 5 to carry home is a combination.", level: I, topic: "Permutation and Combination" },
    { question: "Define the mean, median and mode.", modelAnswer: "The mean is the arithmetic average, the sum of all values divided by their number. The median is the middle value when the data are arranged in ascending order; for an even number of values it is the average of the two middle values. The mode is the value occurring most frequently. For 2, 3, 3, 5, 7: mean = 4, median = 3, mode = 3.", level: B, topic: "Statistics" },
    { question: "Find the value of x if 3x - 7 = 14.", modelAnswer: "3x - 7 = 14. Adding 7 to both sides: 3x = 21. Dividing both sides by 3: x = 7. Check: 3(7) - 7 = 21 - 7 = 14, which satisfies the equation.", level: B, topic: "Linear Equations" },
    { question: "State the Pythagoras theorem.", modelAnswer: "In a right-angled triangle, the square of the hypotenuse is equal to the sum of the squares of the other two sides: (hypotenuse)^2 = (base)^2 + (perpendicular)^2, i.e. c^2 = a^2 + b^2. For example, in a triangle with sides 3 and 4, the hypotenuse is sqrt(9+16) = 5.", level: B, topic: "Geometry Theorems" },
    { question: "What is a circle? Define its radius, chord and diameter.", modelAnswer: "A circle is the set of all points in a plane that are equidistant from a fixed point called the centre. The radius is the distance from the centre to any point on the circle. A chord is a line segment joining any two points on the circle. The diameter is the longest chord, passing through the centre, and equals twice the radius.", level: B, topic: "Geometry" },
    { question: "Simplify: (2/3) + (3/4).", modelAnswer: "The L.C.M. of the denominators 3 and 4 is 12. Converting: 2/3 = 8/12 and 3/4 = 9/12. Adding: 8/12 + 9/12 = 17/12, which as a mixed number is 1 and 5/12.", level: B, topic: "Fractions" },
  ],
  islam: [
    { question: "Write a note on the importance of Sawm (fasting).", modelAnswer: "Sawm is the fourth pillar of Islam, obligatory in Ramadan on every adult sane Muslim. It means abstaining from food, drink and marital relations from dawn to sunset with the intention of worship. It develops taqwa (God-consciousness), self-restraint and patience, teaches the rich the hunger of the poor and creates sympathy, purifies the soul from evil desires, and brings physical health benefits. The Quran says fasting was prescribed for earlier nations too so that you may attain piety.", level: B, topic: "Ibadat" },
    { question: "Describe the significance of Hajj.", modelAnswer: "Hajj is the fifth pillar of Islam, obligatory once in a lifetime on every Muslim who is physically and financially able. It is performed from 8 to 13 Zil-Hajj at Makkah and includes Ihram, Tawaf, Sa'i, standing at Arafat, Rami and Qurbani. It is the greatest demonstration of Muslim unity and equality, as all pilgrims wear the same two simple sheets regardless of wealth, race or nationality. It commemorates the sacrifices of Hazrat Ibrahim (AS) and washes away previous sins.", level: B, topic: "Ibadat" },
    { question: "What are the main teachings of Surah Al-Fatiha?", modelAnswer: "Surah Al-Fatiha is the opening chapter and is recited in every rakat of every prayer. Its teachings: praise and gratitude belong to Allah alone, who is Lord of all the worlds; He is Most Merciful and Most Compassionate; He is Master of the Day of Judgement, establishing accountability; worship and help must be sought from Him alone, which is pure Tauheed; and the believer prays for guidance on the straight path, the path of those favoured by Allah.", level: B, topic: "Quran" },
    { question: "Explain the concept of Akhirat (life after death).", modelAnswer: "Akhirat is the belief that this worldly life is temporary and that after death every person will be raised again on the Day of Resurrection to be judged. Belief in it includes the questioning in the grave, the blowing of the trumpet, resurrection, the presentation of the record of deeds, the weighing of deeds and the crossing of the bridge, followed by eternal reward in Paradise or punishment in Hell. This belief creates accountability, restrains a person from sin and encourages good deeds even when no one is watching.", level: B, topic: "Aqaid" },
    { question: "Write four qualities of a true Muslim.", modelAnswer: "(1) Sincere faith in the oneness of Allah and in the finality of the prophethood of Hazrat Muhammad (PBUH). (2) Truthfulness and honesty in speech and dealings, since the Prophet (PBUH) said a Muslim is one from whose tongue and hand other Muslims are safe. (3) Fulfilment of both Huqooq-Allah and Huqooq-ul-Ibad, including regular prayer and kindness to parents, neighbours and the poor. (4) Patience, forgiveness, humility and avoidance of backbiting, lying and injustice.", level: B, topic: "Akhlaq" },
    { question: "Describe the importance of the Sunnah as a source of guidance.", modelAnswer: "The Sunnah comprises the sayings, actions and tacit approvals of the Holy Prophet (PBUH). It is the second source of Islamic law after the Quran. Its importance: it explains and elaborates the brief commands of the Quran, for example the Quran orders prayer while the Sunnah teaches its times, rakats and method; it provides a practical model of the Quranic teachings; it legislates on matters not explicitly mentioned in the Quran; and obedience to the Prophet (PBUH) is repeatedly commanded in the Quran as obedience to Allah Himself.", level: B, topic: "Hadith" },
    { question: "What are the rights of neighbours in Islam?", modelAnswer: "The Holy Prophet (PBUH) said that Angel Jibraeel emphasised the rights of the neighbour so persistently that he thought neighbours would be made heirs. Rights include: greeting them and enquiring after their health; helping them in difficulty and sharing food; not causing them any harm by noise, smoke or blocking their way; guarding their honour and property in their absence; visiting them when ill and attending their funerals; and congratulating them in happiness. The Prophet (PBUH) declared that a person is not a true believer if his neighbour is not safe from his mischief.", level: B, topic: "Akhlaq" },
    { question: "Explain the importance of truthfulness (Sidq) in Islam.", modelAnswer: "Truthfulness is a fundamental moral virtue in Islam. The Quran commands the believers to be with the truthful. The Holy Prophet (PBUH) said that truthfulness leads to righteousness and righteousness leads to Paradise, while lying leads to wickedness and wickedness leads to Hell. He was called Sadiq and Ameen even by his enemies before prophethood. A truthful person earns the trust of society, and truthfulness is essential in trade, testimony and everyday dealings.", level: B, topic: "Akhlaq" },
    { question: "Write a note on the Charter of Madinah.", modelAnswer: "After the migration, the Holy Prophet (PBUH) framed a written agreement known as the Charter of Madinah, regarded as the first written constitution in history. Its main clauses: the Muslims and Jews of Madinah together formed one community (ummah); each group was free to practise its own religion; all parties would jointly defend Madinah against external attack; bloodshed and oppression were forbidden; disputes would be referred to the Holy Prophet (PBUH) as final arbiter; and no party would make a separate treaty with the enemy. It established religious tolerance and a rule of law.", level: B, topic: "Seerat" },
    { question: "What is meant by Taqwa?", modelAnswer: "Taqwa means piety, God-consciousness and fear of Allah that restrains a person from disobedience. It is an inner state in which a believer is constantly aware that Allah is watching, and therefore avoids what is forbidden and performs what is commanded, even in private. The Quran declares that the most honourable among you in the sight of Allah is the one who has the most taqwa, making it the sole criterion of superiority rather than wealth, race or lineage.", level: B, topic: "Akhlaq" },
  ],
  english: [
    { question: "Write a paragraph of about 100 words on 'Good Manners'.", modelAnswer: "Good manners are the outward expression of an inward refinement of character. They cost nothing but win the hearts of everyone. A well-mannered person greets others politely, speaks softly, listens patiently and never interrupts. He respects his elders, is kind to his juniors and helpful to strangers. He says 'please' and 'thank you' and apologises when at fault. In a crowded bus he offers his seat to an old man; in the classroom he does not disturb others. Good manners open doors that even wealth and education cannot. Truly, manners make a man.", level: B, topic: "Composition" },
    { question: "Change the voice: 'They are building a new hospital.'", modelAnswer: "Passive: A new hospital is being built (by them). Rule: for the present continuous tense the passive is formed with 'is/am/are + being + past participle'. The object 'a new hospital' becomes the subject, and the agent 'by them' is usually omitted when it is indefinite.", level: B, topic: "Voice" },
    { question: "Use the following pair of words in sentences to show the difference: 'accept' and 'except'.", modelAnswer: "Accept (verb: to receive willingly): I gladly accept your invitation to the dinner. Except (preposition: excluding): All the students passed the test except Ahmad. Note that 'accept' takes an object and expresses agreement, whereas 'except' introduces an exclusion.", level: B, topic: "Vocabulary" },
    { question: "Correct the sentence: 'One of my friend are coming tomorrow.'", modelAnswer: "Correct: One of my friends is coming tomorrow. Explanation: 'one of' must be followed by a plural noun, so 'friend' becomes 'friends'. However the subject of the sentence is the singular word 'one', so the verb must be singular, 'is', not 'are'.", level: B, topic: "Grammar" },
    { question: "Write four sentences on the importance of reading books.", modelAnswer: "Books are the truest and most faithful friends of man. They widen our mental horizon and introduce us to the thoughts of the greatest minds of all ages. A good book provides both instruction and delight, and gives us company in loneliness. Therefore we should cultivate the habit of reading good books daily.", level: B, topic: "Composition" },
    { question: "Change into indirect speech: She said to him, 'Please help me.'", modelAnswer: "Indirect: She requested him to help her. Rules: for an imperative sentence expressing a request, the reporting verb becomes 'requested'; the word 'please' is dropped as it is absorbed into 'requested'; the imperative verb changes to the infinitive 'to help'; and the pronoun 'me' changes to 'her'.", level: B, topic: "Narration" },
    { question: "Give the meaning of and use in a sentence: 'to give up'.", modelAnswer: "Meaning: to stop doing something, to abandon or surrender. Sentence: The doctor advised him to give up smoking immediately for the sake of his health. It is a separable phrasal verb, so one may also say 'give it up'.", level: B, topic: "Phrasal Verbs" },
    { question: "Punctuate: what a beautiful sight it is exclaimed ali", modelAnswer: "\"What a beautiful sight it is!\" exclaimed Ali. Corrections: inverted commas enclose the spoken words; capital W begins the quotation; an exclamation mark ends the exclamatory sentence inside the inverted commas; and the proper noun Ali takes a capital A, with a full stop at the end.", level: B, topic: "Punctuation" },
    { question: "Fill in the blanks with the correct form of the verb: (i) He ___ (go) to school daily. (ii) They ___ (play) cricket yesterday.", modelAnswer: "(i) He goes to school daily. The adverb 'daily' indicates a habitual action, so the simple present tense is used, and with the third person singular subject 'he' the verb takes -s. (ii) They played cricket yesterday. 'Yesterday' indicates a completed past action, so the simple past tense 'played' is used.", level: B, topic: "Tenses" },
    { question: "Write the central idea of any lesson or poem in about 50 words.", modelAnswer: "The central idea is that perseverance and honest effort ultimately triumph over difficulty. The writer shows through the experiences of the main character that failure is not final but a step towards success, and urges the reader never to lose heart in the face of hardship but to keep striving with patience and faith.", level: B, topic: "Comprehension" },
  ],
  urdu: [
    { question: "قومی زبان کی اہمیت پر مختصر نوٹ لکھیں۔", modelAnswer: "قومی زبان کسی قوم کی شناخت، تہذیب اور اجتماعی وحدت کی علامت ہوتی ہے۔ اردو پاکستان کی قومی زبان ہے جو ملک کے تمام صوبوں کے درمیان رابطے کا کام دیتی ہے۔ یہ تحریکِ پاکستان کی زبان رہی اور اس نے مسلمانوں کو ایک لڑی میں پرویا۔ قائدِ اعظم نے 1948ء میں ڈھاکہ میں واضح طور پر فرمایا کہ پاکستان کی سرکاری زبان اردو اور صرف اردو ہوگی۔ اپنی زبان میں تعلیم سے قوم جلد ترقی کرتی ہے۔", level: B, topic: "مضمون" },
    { question: "درج ذیل محاورے کو جملے میں استعمال کریں: 'ہاتھ پیر مارنا'", modelAnswer: "معنی: بہت کوشش کرنا، جدوجہد کرنا۔ جملہ: اسلم نے نوکری حاصل کرنے کے لیے بہت ہاتھ پیر مارے، مگر سفارش نہ ہونے کے باعث کامیاب نہ ہو سکا۔", level: B, topic: "محاورات" },
    { question: "'تلمیح' کی تعریف کریں اور ایک مثال دیں۔", modelAnswer: "تلمیح وہ صنعت ہے جس میں شعر یا عبارت میں کسی مشہور تاریخی، مذہبی یا ادبی واقعے یا شخصیت کی طرف اشارہ کیا جائے، مگر پورا واقعہ بیان نہ کیا جائے۔ مثال: اقبال کا شعر جس میں 'یدِ بیضا' کا ذکر ہے، حضرت موسیٰؑ کے معجزے کی طرف اشارہ ہے۔ اسی طرح 'یوسف و زلیخا' اور 'لیلیٰ مجنوں' کے حوالے بھی تلمیحات ہیں۔", level: B, topic: "علمِ بیان" },
    { question: "مثنوی کی تعریف کریں اور اردو کی مشہور مثنویوں کے نام لکھیں۔", modelAnswer: "مثنوی وہ صنفِ سخن ہے جس کے ہر شعر کے دونوں مصرعے ہم قافیہ ہوں مگر ہر شعر کا قافیہ الگ ہو۔ اس میں طوالت کی گنجائش ہوتی ہے، اس لیے قصے، داستانیں اور تصوف کے مضامین بیان کیے جاتے ہیں۔ اردو کی مشہور مثنویاں: میر حسن کی 'سحرالبیان'، دیا شنکر نسیم کی 'گلزارِ نسیم'، اور مولانا رومی کی فارسی 'مثنوی معنوی'۔", level: B, topic: "اصنافِ سخن" },
    { question: "واحد سے جمع بنائیں: (i) مکان (ii) عالم (iii) خبر", modelAnswer: "(i) مکان کی جمع 'مکانات' ہے۔ (ii) عالم کی جمع 'علما' ہے۔ (iii) خبر کی جمع 'اخبار' ہے۔ یہ سب عربی قواعد کے مطابق جمع مکسر کی مثالیں ہیں، جن میں لفظ کی ساخت تبدیل ہو جاتی ہے۔", level: B, topic: "قواعد" },
    { question: "سفرنامہ کی تعریف کریں اور اردو کے دو مشہور سفرنامے لکھیں۔", modelAnswer: "سفرنامہ وہ نثری صنف ہے جس میں مصنف اپنے سفر کے مشاہدات، تجربات، مقامات کی سیر، وہاں کے لوگوں کے رسم و رواج اور اپنے تاثرات دلچسپ انداز میں بیان کرتا ہے۔ اس میں معلومات کے ساتھ ادبی چاشنی بھی ہوتی ہے۔ مشہور اردو سفرنامے: ابنِ بطوطہ کے سفرنامے کا ترجمہ، مستنصر حسین تارڑ کا 'نکلے تری تلاش میں'، اور ابنِ انشا کا 'ابنِ بطوطہ کے تعاقب میں'۔", level: B, topic: "نثری اصناف" },
    { question: "'صنعتِ تضاد' کی وضاحت کریں۔", modelAnswer: "صنعتِ تضاد وہ صنعت ہے جس میں شعر یا عبارت میں دو متضاد یا مخالف معنی رکھنے والے الفاظ ایک ساتھ لائے جائیں، جس سے کلام میں حسن اور اثر پیدا ہوتا ہے۔ مثلاً دن اور رات، امیر اور غریب، ہنسنا اور رونا۔ اقبال کے کلام میں 'شاہین' اور 'کرگس' کا تقابل بھی اسی صنعت کی مثال ہے۔", level: B, topic: "علمِ بدیع" },
    { question: "مکالمہ نگاری کے اصول بیان کریں۔", modelAnswer: "(1) مکالمہ مختصر، برجستہ اور فطری ہو۔ (2) ہر کردار کی زبان اس کی عمر، تعلیم اور سماجی حیثیت کے مطابق ہو۔ (3) موضوع سے ہٹ کر بات نہ کی جائے۔ (4) بول چال کی سادہ اور رواں زبان استعمال ہو۔ (5) مکالمے میں دلچسپی اور تسلسل قائم رہے۔ (6) اختتام کسی نتیجے یا سبق پر ہو۔ (7) رموزِ اوقاف اور بولنے والے کا نام درست لکھا جائے۔", level: B, topic: "نثر نگاری" },
    { question: "'اسمِ نکرہ' اور 'اسمِ معرفہ' میں فرق واضح کریں۔", modelAnswer: "اسمِ نکرہ وہ اسم ہے جو کسی عام یا غیر متعین شے کے لیے بولا جائے، جیسے شہر، لڑکا، کتاب۔ اسمِ معرفہ وہ اسم ہے جو کسی خاص اور متعین شے یا شخص کے لیے بولا جائے، جیسے لاہور، اسلم، قرآنِ مجید۔ اسمِ معرفہ کی اقسام میں اسمِ علم، اسمِ ضمیر، اسمِ اشارہ اور اسمِ موصول شامل ہیں۔", level: B, topic: "قواعد" },
    { question: "علامہ اقبال کے تصورِ شاہین کی وضاحت کریں۔", modelAnswer: "اقبال نے شاہین کو مردِ مومن کی علامت کے طور پر پیش کیا ہے۔ شاہین کی خصوصیات: وہ بلند پرواز ہے اور فضاؤں کی وسعت میں رہتا ہے؛ خود دار ہے اور دوسرے کا مارا ہوا شکار نہیں کھاتا؛ آشیانہ نہیں بناتا یعنی دنیاوی آسائشوں سے بے نیاز ہے؛ تیز نگاہ اور جھپٹنے کی قوت رکھتا ہے؛ اور تنہائی پسند ہے۔ اقبال نوجوانوں کو انہی اوصاف کے اپنانے کی تلقین کرتے ہیں تاکہ وہ خودی سے آشنا ہو کر قوم کی رہنمائی کر سکیں۔", level: B, topic: "شاعری" },
  ],
};

export const EXTRA_NUMERICALS: Record<string, BankNumerical[]> = {
  physics: [
    { question: "A force of 150 N acts on a body of mass 30 kg. Calculate the acceleration produced and the distance covered in 6 s starting from rest.", formula: "F = ma ; S = ut + (1/2)at^2", solution: "GIVEN:\nF = 150 N, m = 30 kg, u = 0 m s^-1, t = 6 s\n\nREQUIRED: a = ? , S = ?\n\nFORMULA: F = ma and S = ut + (1/2)at^2\n\nWORKING:\na = F/m = 150/30 = 5 m s^-2\nS = (0)(6) + (1/2)(5)(6)^2\nS = (1/2)(5)(36) = 90 m\n\nRESULT: acceleration = 5 m s^-2 and distance covered = 90 m", marks: 5, level: B, topic: "Force and Motion" },
    { question: "Calculate the pressure exerted at the bottom of a water tank 5 m deep. (density of water = 1000 kg m^-3, g = 10 m s^-2)", formula: "P = rho g h", solution: "GIVEN:\nh = 5 m, rho = 1000 kg m^-3, g = 10 m s^-2\n\nREQUIRED: P = ?\n\nFORMULA: P = rho g h\n\nWORKING:\nP = 1000 x 10 x 5\nP = 50000 Pa\nP = 5 x 10^4 Pa = 50 kPa\n\nRESULT: the pressure at the bottom is 5 x 10^4 pascals.\n(Note: this is the pressure due to the water column only; atmospheric pressure would be added for absolute pressure.)", marks: 5, level: B, topic: "Pressure" },
  ],
  chemistry: [
    { question: "Calculate the number of moles in 4.9 g of H2SO4. (H = 1, S = 32, O = 16)", formula: "n = mass / molar mass", solution: "GIVEN:\nMass of H2SO4 = 4.9 g\n\nREQUIRED: number of moles n = ?\n\nWORKING:\nMolar mass of H2SO4 = (2 x 1) + 32 + (4 x 16)\n= 2 + 32 + 64 = 98 g mol^-1\n\nn = mass / molar mass = 4.9 / 98\nn = 0.05 mol\n\nNumber of molecules = 0.05 x 6.02 x 10^23 = 3.01 x 10^22\n\nRESULT: 0.05 mole (containing 3.01 x 10^22 molecules)", marks: 5, level: B, topic: "Mole Concept" },
  ],
  math: [
    { question: "Solve the simultaneous equations by the method of substitution: x + y = 10 and 2x - y = 5.", formula: "Substitution method", solution: "GIVEN:\nx + y = 10 ..... (i)\n2x - y = 5 ..... (ii)\n\nWORKING:\nFrom (i): y = 10 - x\n\nSubstituting into (ii):\n2x - (10 - x) = 5\n2x - 10 + x = 5\n3x = 15\nx = 5\n\nSubstituting x = 5 back into (i):\n5 + y = 10\ny = 5\n\nCHECK: 2(5) - 5 = 10 - 5 = 5 (correct)\n\nRESULT: x = 5 and y = 5, solution set {(5, 5)}", marks: 5, level: B, topic: "Linear Equations" },
  ],
};
