/**
 * Numerical + theory bank for Physics, Chemistry and Mathematics.
 *
 * The legacy pools in mockUpService.ts cycled through only 1-3 hardcoded strings,
 * so a 12-MCQ physics paper contained the same question repeated. This bank supplies
 * genuinely distinct, board-standard items, and crucially supplies NUMERICALS with
 * full step-by-step solutions (Given / Formula / Working / Answer with SI units)
 * as required by AGENTS.md.
 *
 * `level`: "matric" = 9th/10th, "inter" = 11th/12th, "both" = usable at either.
 */

export type Level = "matric" | "inter" | "both";

export interface BankMCQ2 {
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  level: Level;
  topic: string;
}

export interface BankShort2 {
  question: string;
  modelAnswer: string;
  level: Level;
  topic: string;
}

export interface BankLong2 {
  a: { question: string; modelAnswer: string };
  b: { question: string; modelAnswer: string };
  level: Level;
  topic: string;
}

export interface BankNumerical {
  question: string;
  formula: string;
  solution: string;
  marks: number;
  level: Level;
  topic: string;
}

export interface ExamSubjectBank {
  mcqs: BankMCQ2[];
  shorts: BankShort2[];
  longs: BankLong2[];
  numericals: BankNumerical[];
}

/* ============================== PHYSICS ============================== */
const physics: ExamSubjectBank = {
  mcqs: [
    { question: "The SI unit of force is the:", options: ["Newton", "Joule", "Pascal", "Watt"], correctIndex: 0, explanation: "1 N = 1 kg m s^-2, the force producing 1 m/s^2 in a 1 kg mass.", level: "both", topic: "Force and Motion" },
    { question: "Which of the following is a base quantity?", options: ["Length", "Force", "Velocity", "Density"], correctIndex: 0, explanation: "Length, mass, time, current, temperature, amount of substance and luminous intensity are the seven base quantities.", level: "both", topic: "Measurements" },
    { question: "The value of g on the surface of the Earth is approximately:", options: ["9.8 m s^-2", "8.9 m s^-2", "10.8 m s^-2", "6.67 m s^-2"], correctIndex: 0, explanation: "Free-fall acceleration near the Earth's surface is about 9.8 m s^-2.", level: "both", topic: "Gravitation" },
    { question: "Momentum is the product of:", options: ["Mass and velocity", "Mass and acceleration", "Force and time", "Force and distance"], correctIndex: 0, explanation: "p = mv, a vector with SI unit kg m s^-1 (or N s).", level: "both", topic: "Momentum" },
    { question: "Work done is zero when the angle between force and displacement is:", options: ["90 degrees", "0 degrees", "180 degrees", "45 degrees"], correctIndex: 0, explanation: "W = F d cos(theta); cos 90 = 0, so no work is done.", level: "both", topic: "Work and Energy" },
    { question: "The unit of electric charge is the:", options: ["Coulomb", "Ampere", "Volt", "Ohm"], correctIndex: 0, explanation: "1 C = 1 A s, the charge carried in one second by a current of one ampere.", level: "both", topic: "Electrostatics" },
    { question: "Ohm's law states that:", options: ["V = IR", "V = I/R", "I = VR", "R = VI"], correctIndex: 0, explanation: "At constant temperature, potential difference is directly proportional to current.", level: "both", topic: "Current Electricity" },
    { question: "The speed of light in vacuum is:", options: ["3 x 10^8 m/s", "3 x 10^6 m/s", "3 x 10^10 m/s", "1.5 x 10^8 m/s"], correctIndex: 0, explanation: "c = 2.998 x 10^8 m s^-1, usually taken as 3 x 10^8 m s^-1.", level: "both", topic: "Light" },
    { question: "In a series circuit, the quantity that remains the same through each resistor is:", options: ["Current", "Voltage", "Power", "Resistance"], correctIndex: 0, explanation: "There is only one path, so the same current flows through every component.", level: "both", topic: "Current Electricity" },
    { question: "The escape velocity from the Earth's surface is about:", options: ["11.2 km/s", "7.9 km/s", "9.8 km/s", "3 x 10^8 m/s"], correctIndex: 0, explanation: "v_esc = sqrt(2gR) which is approximately 11.2 km s^-1.", level: "both", topic: "Gravitation" },
    { question: "Coulomb's constant k in free space has the value:", options: ["9 x 10^9 N m^2 C^-2", "8.85 x 10^-12 C^2 N^-1 m^-2", "6.63 x 10^-34 J s", "1.6 x 10^-19 C"], correctIndex: 0, explanation: "k = 1/(4 pi epsilon-nought) = 9 x 10^9 N m^2 C^-2.", level: "both", topic: "Electrostatics" },
    { question: "The time period of a simple pendulum depends upon its:", options: ["Length", "Mass", "Amplitude for large swings", "Material"], correctIndex: 0, explanation: "T = 2 pi sqrt(L/g); it is independent of the mass of the bob.", level: "both", topic: "Oscillations" },
    { question: "Sound waves are:", options: ["Longitudinal mechanical waves", "Transverse waves", "Electromagnetic waves", "Standing waves only"], correctIndex: 0, explanation: "Particles of the medium vibrate parallel to the direction of propagation.", level: "both", topic: "Sound" },
    { question: "One horsepower is equal to:", options: ["746 W", "1000 W", "550 W", "100 W"], correctIndex: 0, explanation: "1 hp = 746 watts.", level: "both", topic: "Work and Energy" },
    { question: "The dimension of pressure is:", options: ["[ML^-1T^-2]", "[MLT^-2]", "[ML^2T^-2]", "[ML^-3]"], correctIndex: 0, explanation: "Pressure = Force/Area = [MLT^-2]/[L^2] = [ML^-1T^-2].", level: "inter", topic: "Measurements" },
    { question: "The dot product of two perpendicular vectors is:", options: ["Zero", "Maximum", "Unity", "Negative"], correctIndex: 0, explanation: "A.B = AB cos 90 = 0.", level: "inter", topic: "Vectors" },
    { question: "According to Einstein's photoelectric equation, the kinetic energy of the emitted electron is:", options: ["hf - W", "hf + W", "W - hf", "hf/W"], correctIndex: 0, explanation: "KE(max) = hf - W, where W is the work function of the metal.", level: "inter", topic: "Modern Physics" },
    { question: "The efficiency of a Carnot engine depends on:", options: ["Temperatures of source and sink", "Nature of the working substance", "Size of the engine", "Pressure only"], correctIndex: 0, explanation: "Efficiency = 1 - T2/T1, with temperatures in kelvin.", level: "inter", topic: "Thermodynamics" },
    { question: "In simple harmonic motion, acceleration is:", options: ["Directly proportional to displacement and oppositely directed", "Constant", "Zero at the extreme position", "Maximum at the mean position"], correctIndex: 0, explanation: "a = -omega^2 x, always directed towards the mean position.", level: "both", topic: "Oscillations" },
    { question: "The half-life of a radioactive element is the time in which:", options: ["Half of the nuclei decay", "All nuclei decay", "One quarter decays", "The element becomes stable"], correctIndex: 0, explanation: "After each half-life the number of undecayed nuclei is halved.", level: "inter", topic: "Nuclear Physics" },
  ],
  shorts: [
    { question: "Define scalar and vector quantities with one example of each.", modelAnswer: "A scalar quantity has only magnitude with a proper unit, e.g. mass 5 kg, temperature 30 C. A vector quantity has both magnitude and direction and obeys vector addition, e.g. velocity 20 m/s due east, force 10 N downward.", level: "both", topic: "Vectors" },
    { question: "State Newton's second law of motion and derive F = ma.", modelAnswer: "The rate of change of momentum of a body is directly proportional to the applied force and takes place in the direction of the force. F = (mv - mu)/t = m(v-u)/t = ma, since (v-u)/t is acceleration a. In SI units the constant of proportionality is 1, giving F = ma.", level: "both", topic: "Force and Motion" },
    { question: "Differentiate between distance and displacement.", modelAnswer: "Distance is the total length of the actual path travelled; it is a scalar, always positive and never decreases. Displacement is the shortest directed straight-line distance from the initial to the final position; it is a vector, can be zero or negative, and its magnitude is always less than or equal to the distance.", level: "both", topic: "Kinematics" },
    { question: "What is meant by the term 'inertia'?", modelAnswer: "Inertia is the natural tendency of a body to resist any change in its state of rest or of uniform motion in a straight line. It is directly proportional to the mass of the body; a heavier body has greater inertia. It is described by Newton's first law, also called the law of inertia.", level: "both", topic: "Force and Motion" },
    { question: "State the law of conservation of momentum.", modelAnswer: "The total linear momentum of an isolated system remains constant provided no net external force acts on it. For a collision between two bodies: m1u1 + m2u2 = m1v1 + m2v2. It follows from Newton's third law and applies to both elastic and inelastic collisions.", level: "both", topic: "Momentum" },
    { question: "Define power and write its SI unit.", modelAnswer: "Power is the rate of doing work or the rate of transfer of energy. P = W/t = Fv. Its SI unit is the watt (W), where 1 W = 1 J s^-1. A larger unit is the kilowatt (1 kW = 1000 W) and 1 horsepower = 746 W.", level: "both", topic: "Work and Energy" },
    { question: "Distinguish between conductors and insulators.", modelAnswer: "Conductors contain a large number of free electrons that move easily, so they allow charge and heat to flow readily and have very low resistivity, e.g. copper, silver, aluminium. Insulators have tightly bound electrons and no free charge carriers, so they oppose the flow of current and have very high resistivity, e.g. glass, rubber, dry wood.", level: "both", topic: "Current Electricity" },
    { question: "State Coulomb's law and write its mathematical form.", modelAnswer: "The force of attraction or repulsion between two point charges is directly proportional to the product of the magnitudes of the charges and inversely proportional to the square of the distance between them, acting along the line joining them. F = k q1 q2 / r^2, where k = 9 x 10^9 N m^2 C^-2 in free space.", level: "both", topic: "Electrostatics" },
    { question: "What is the difference between AC and DC?", modelAnswer: "Direct current flows in one direction only and its magnitude stays constant, e.g. from a cell or battery. Alternating current periodically reverses its direction and its magnitude varies sinusoidally with time, e.g. mains supply at 50 Hz in Pakistan. AC can be stepped up or down by a transformer and transmitted over long distances with less loss.", level: "both", topic: "Current Electricity" },
    { question: "Define refractive index of a medium.", modelAnswer: "The refractive index n of a medium is the ratio of the speed of light in vacuum to the speed of light in that medium: n = c/v. Equivalently, by Snell's law, n = sin i / sin r. It is a dimensionless quantity and is always greater than or equal to 1; for glass it is about 1.5.", level: "both", topic: "Light" },
    { question: "State the first law of thermodynamics.", modelAnswer: "Energy can neither be created nor destroyed but only converted from one form to another. When heat Q is supplied to a system, part of it increases the internal energy (delta U) and the rest is used by the system in doing external work W: Q = delta U + W. It is the law of conservation of energy applied to thermal systems.", level: "inter", topic: "Thermodynamics" },
    { question: "What is meant by the photoelectric effect?", modelAnswer: "The photoelectric effect is the emission of electrons from the surface of a metal when light of sufficiently high frequency falls on it. Emission occurs only above a threshold frequency, is instantaneous, and the maximum kinetic energy depends on frequency, not intensity, while the number of electrons depends on intensity. Einstein explained it by KE(max) = hf - W.", level: "inter", topic: "Modern Physics" },
    { question: "Define simple harmonic motion and give two examples.", modelAnswer: "SHM is the vibratory motion in which acceleration is directly proportional to the displacement from the mean position and is always directed towards it: a = -omega^2 x. Examples: the oscillation of a simple pendulum with small amplitude, and the vertical vibration of a mass attached to a spring.", level: "both", topic: "Oscillations" },
    { question: "Differentiate between longitudinal and transverse waves.", modelAnswer: "In longitudinal waves the particles of the medium vibrate parallel to the direction of propagation, forming compressions and rarefactions, e.g. sound waves. In transverse waves the particles vibrate perpendicular to the direction of propagation, forming crests and troughs, e.g. water waves and light waves. Longitudinal waves can travel through solids, liquids and gases, whereas transverse mechanical waves travel only through solids and along liquid surfaces.", level: "both", topic: "Waves" },
    { question: "State the principle of the transformer.", modelAnswer: "A transformer works on the principle of mutual induction: a changing current in the primary coil produces a changing magnetic flux that links the secondary coil and induces an EMF in it. For an ideal transformer Vs/Vp = Ns/Np. A step-up transformer has Ns > Np and increases voltage while decreasing current; a step-down transformer does the reverse. Power remains nearly constant.", level: "both", topic: "Electromagnetism" },
    { question: "What is meant by half-life of a radioactive substance?", modelAnswer: "Half-life is the time during which half of the radioactive nuclei present in a sample decay, or the activity falls to half its original value. It is a characteristic constant for each isotope and is independent of temperature, pressure and chemical state. After n half-lives the remaining fraction is (1/2)^n.", level: "inter", topic: "Nuclear Physics" },
  ],
  longs: [
    { a: { question: "Define uniform circular motion. Derive an expression for centripetal acceleration.", modelAnswer: "Uniform circular motion is motion in a circle with constant speed but continuously changing direction, so the velocity and hence the motion is accelerated. Consider a body moving with speed v in a circle of radius r. In a small time interval delta-t it moves through arc length v.delta-t, and the velocity vector turns through the same angle delta-theta = v.delta-t / r. From the vector triangle, the change in velocity is delta-v = v.delta-theta. Therefore a = delta-v/delta-t = v.(v/r) = v^2/r, directed towards the centre of the circle. Hence centripetal force F = mv^2/r = m.omega^2.r." }, b: { question: "State and explain Newton's law of universal gravitation.", modelAnswer: "Every body in the universe attracts every other body with a force that is directly proportional to the product of their masses and inversely proportional to the square of the distance between their centres. F = G m1 m2 / r^2, where G = 6.67 x 10^-11 N m^2 kg^-2 is the universal gravitational constant. The force acts along the line joining the centres, is always attractive, obeys Newton's third law, and is independent of the medium. On the Earth's surface F = mg, hence g = GM/R^2, which shows that g decreases with altitude and depth." }, level: "both", topic: "Circular Motion and Gravitation" },
    { a: { question: "State Ohm's law. Derive expressions for the equivalent resistance of resistors in series and in parallel.", modelAnswer: "Ohm's law: at constant temperature the current through a conductor is directly proportional to the potential difference across its ends, V = IR. Series: the same current I flows through R1, R2, R3 and the total voltage is the sum of individual voltages. V = V1 + V2 + V3, so IRe = IR1 + IR2 + IR3, giving Re = R1 + R2 + R3. The equivalent resistance is greater than the largest individual resistance. Parallel: the same voltage V is across each resistor and the total current is the sum of branch currents. I = I1 + I2 + I3, so V/Re = V/R1 + V/R2 + V/R3, giving 1/Re = 1/R1 + 1/R2 + 1/R3. The equivalent resistance is smaller than the smallest individual resistance." }, b: { question: "Explain Joule's law of heating and state three of its applications.", modelAnswer: "When current flows through a conductor, the heat produced is directly proportional to the square of the current, the resistance and the time: H = I^2 R t joules. This is because the drifting electrons collide with the lattice ions and transfer kinetic energy, which appears as heat. Applications: electric heaters, irons and geysers use high-resistance nichrome coils; the filament of an incandescent bulb (tungsten) becomes white hot and emits light; a fuse wire of low melting point melts and breaks the circuit when excessive current flows, protecting appliances." }, level: "both", topic: "Current Electricity" },
    { a: { question: "What is meant by the equations of motion? Derive the three equations of uniformly accelerated motion.", modelAnswer: "Let u be the initial velocity, v the final velocity, a the uniform acceleration, t the time and S the distance covered. (1) By definition a = (v-u)/t, therefore v = u + at. (2) Distance = average velocity x time = ((u+v)/2) t. Substituting v = u + at gives S = ((u + u + at)/2) t = ut + (1/2)at^2. (3) From (1), t = (v-u)/a. Substituting in S = ((u+v)/2)t gives S = ((u+v)(v-u))/(2a) = (v^2 - u^2)/(2a), hence 2aS = v^2 - u^2. These are valid only for straight-line motion with constant acceleration." }, b: { question: "Distinguish between elastic and inelastic collisions and apply conservation laws to a head-on elastic collision.", modelAnswer: "In an elastic collision both momentum and kinetic energy are conserved and the bodies separate after impact, e.g. collisions between gas molecules or ivory balls. In an inelastic collision momentum is conserved but kinetic energy is not, some being converted into heat, sound and deformation; in a perfectly inelastic collision the bodies stick together. For a head-on elastic collision of masses m1 and m2 with initial velocities u1 and u2: m1u1 + m2u2 = m1v1 + m2v2 and (1/2)m1u1^2 + (1/2)m2u2^2 = (1/2)m1v1^2 + (1/2)m2v2^2. Solving gives v1 = ((m1-m2)/(m1+m2))u1 + (2m2/(m1+m2))u2. Special case: if m1 = m2 and u2 = 0, then v1 = 0 and v2 = u1, i.e. the velocities are exchanged." }, level: "both", topic: "Motion and Momentum" },
    { a: { question: "Describe the construction and working of an AC generator.", modelAnswer: "Construction: an AC generator consists of a rectangular coil (armature) of many turns of insulated copper wire wound on a soft-iron core, mounted between the poles of a strong permanent magnet or electromagnet. The ends of the coil are connected to two separate slip rings which press against carbon brushes connected to the external circuit. Working: it works on the principle of electromagnetic induction. As the coil is rotated mechanically in the magnetic field, the flux linked with it changes continuously and an EMF is induced given by e = NBA.omega.sin(omega.t). When the plane of the coil is parallel to the field the rate of flux change is maximum and the EMF is maximum; when the plane is perpendicular the EMF is zero. After every half rotation the direction of the induced current reverses, producing an alternating current. The slip rings maintain a continuous connection while allowing the current to alternate." }, b: { question: "State Faraday's laws of electromagnetic induction and Lenz's law.", modelAnswer: "Faraday's first law: whenever the magnetic flux linked with a circuit changes, an EMF is induced in it, and it lasts only as long as the change continues. Faraday's second law: the magnitude of the induced EMF is directly proportional to the rate of change of magnetic flux, e = -N (d(phi)/dt), where N is the number of turns. Lenz's law: the direction of the induced current is always such that it opposes the cause producing it. This is expressed by the negative sign in Faraday's equation. For example, when the north pole of a magnet is pushed towards a coil, the near face of the coil becomes a north pole and repels the magnet, so work must be done against this opposition. Lenz's law is a direct consequence of the law of conservation of energy." }, level: "both", topic: "Electromagnetism" },
    { a: { question: "Explain the kinetic molecular theory of gases and derive the gas laws from it qualitatively.", modelAnswer: "Postulates: a gas consists of a very large number of tiny molecules in continuous random motion; the volume of the molecules is negligible compared with the volume of the container; intermolecular forces are negligible except during collisions; all collisions are perfectly elastic; the average kinetic energy of the molecules is directly proportional to the absolute temperature. Pressure arises from the continual bombardment of molecules on the walls, P = (1/3) rho c-bar^2. Boyle's law: at constant temperature the mean square speed is fixed, so reducing the volume increases the frequency of collisions with the walls and therefore the pressure, giving PV = constant. Charles's law: raising the temperature increases the average kinetic energy and hence the speed, so to keep pressure constant the volume must increase, giving V proportional to T." }, b: { question: "Define specific heat capacity and latent heat. Explain the importance of the high specific heat of water.", modelAnswer: "Specific heat capacity c is the amount of heat required to raise the temperature of one kilogram of a substance through one kelvin: Q = mc.delta-T, SI unit J kg^-1 K^-1. Latent heat is the heat absorbed or released during a change of state at constant temperature: Q = mL. Latent heat of fusion is the heat needed to convert 1 kg of a solid into liquid at its melting point (for ice, 3.36 x 10^5 J/kg) and latent heat of vaporisation converts 1 kg of liquid into vapour at its boiling point (for water, 2.26 x 10^6 J/kg). Water has an unusually high specific heat capacity of 4200 J kg^-1 K^-1, so it warms and cools slowly. This moderates the climate of coastal regions, makes water an excellent coolant in car radiators and power stations, and helps living organisms maintain a stable body temperature." }, level: "both", topic: "Heat and Thermodynamics" },
    { a: { question: "Describe the phenomenon of total internal reflection and state its conditions and applications.", modelAnswer: "When light travels from a denser medium to a rarer medium it bends away from the normal. As the angle of incidence increases, the angle of refraction increases faster and at a particular angle called the critical angle the refracted ray grazes along the boundary at 90 degrees. If the angle of incidence exceeds the critical angle, no refraction occurs and the entire light is reflected back into the denser medium; this is total internal reflection. Conditions: (1) light must travel from a denser to a rarer medium; (2) the angle of incidence must be greater than the critical angle. The critical angle is given by sin C = 1/n. For glass (n = 1.5), C is about 42 degrees. Applications: optical fibres used in telecommunications and endoscopy, totally reflecting prisms in periscopes and binoculars, the sparkle of diamonds, and the formation of mirages." }, b: { question: "Explain the working of a simple microscope and a compound microscope with ray diagrams.", modelAnswer: "Simple microscope: it is a single convex lens of short focal length. The object is placed between the lens and its principal focus, so the image formed is virtual, erect and magnified, and is viewed at the least distance of distinct vision (25 cm). Its magnifying power M = 1 + d/f, where d = 25 cm. A shorter focal length gives greater magnification. Compound microscope: it consists of two convex lenses, an objective of very short focal length and small aperture facing the object, and an eyepiece of moderate focal length. The object is placed just beyond the focus of the objective, which forms a real, inverted and magnified image inside the focal length of the eyepiece. The eyepiece then acts as a simple microscope and produces a final virtual, inverted and highly magnified image. Total magnification M = M(objective) x M(eyepiece) = (L/fo)(d/fe)." }, level: "both", topic: "Light and Optics" },
  ],
  numericals: [
    { question: "A car of mass 1200 kg accelerates uniformly from rest to 20 m s^-1 in 8 s. Calculate (i) the acceleration and (ii) the net force acting on the car.", formula: "a = (v - u)/t ; F = ma", solution: "GIVEN:\nm = 1200 kg, u = 0 m s^-1, v = 20 m s^-1, t = 8 s\n\nREQUIRED: a = ? , F = ?\n\nFORMULA: a = (v - u)/t and F = ma\n\nWORKING:\na = (20 - 0)/8 = 20/8 = 2.5 m s^-2\nF = m x a = 1200 x 2.5 = 3000 N\n\nRESULT: acceleration = 2.5 m s^-2 and net force = 3000 N = 3.0 kN", marks: 5, level: "both", topic: "Force and Motion" },
    { question: "A body of mass 5 kg is raised vertically through a height of 12 m. Calculate the work done and the potential energy gained. (g = 10 m s^-2)", formula: "W = F x d = mgh ; P.E. = mgh", solution: "GIVEN:\nm = 5 kg, h = 12 m, g = 10 m s^-2\n\nREQUIRED: W = ? , P.E. = ?\n\nFORMULA: W = mgh\n\nWORKING:\nW = 5 x 10 x 12 = 600 J\nSince all the work done against gravity is stored as potential energy,\nP.E. = mgh = 600 J\n\nRESULT: work done = 600 J and potential energy gained = 600 J", marks: 5, level: "both", topic: "Work and Energy" },
    { question: "Two point charges of 4 microcoulomb and 6 microcoulomb are placed 0.3 m apart in air. Find the force between them. (k = 9 x 10^9 N m^2 C^-2)", formula: "F = k q1 q2 / r^2", solution: "GIVEN:\nq1 = 4 x 10^-6 C, q2 = 6 x 10^-6 C, r = 0.3 m, k = 9 x 10^9 N m^2 C^-2\n\nREQUIRED: F = ?\n\nFORMULA: F = k q1 q2 / r^2\n\nWORKING:\nq1 q2 = (4 x 10^-6)(6 x 10^-6) = 24 x 10^-12 C^2\nr^2 = (0.3)^2 = 0.09 m^2\nF = (9 x 10^9 x 24 x 10^-12) / 0.09\nF = (216 x 10^-3) / 0.09 = 0.216 / 0.09\nF = 2.4 N\n\nRESULT: the force is 2.4 N and it is repulsive, since both charges are positive.", marks: 5, level: "both", topic: "Electrostatics" },
    { question: "An electric heater draws a current of 5 A from a 220 V supply. Calculate its resistance and the heat produced in 10 minutes.", formula: "R = V/I ; H = I^2 R t", solution: "GIVEN:\nI = 5 A, V = 220 V, t = 10 min = 600 s\n\nREQUIRED: R = ? , H = ?\n\nFORMULA: R = V/I and H = I^2 R t\n\nWORKING:\nR = 220/5 = 44 ohm\nH = I^2 R t = (5)^2 x 44 x 600\nH = 25 x 44 x 600 = 1100 x 600 = 660000 J\nH = 6.6 x 10^5 J = 660 kJ\n\nRESULT: resistance = 44 ohm and heat produced = 6.6 x 10^5 J", marks: 5, level: "both", topic: "Current Electricity" },
    { question: "A simple pendulum has a length of 1.0 m. Calculate its time period and frequency. (g = 9.8 m s^-2)", formula: "T = 2 pi sqrt(L/g) ; f = 1/T", solution: "GIVEN:\nL = 1.0 m, g = 9.8 m s^-2\n\nREQUIRED: T = ? , f = ?\n\nFORMULA: T = 2 pi sqrt(L/g)\n\nWORKING:\nL/g = 1.0/9.8 = 0.10204\nsqrt(0.10204) = 0.3194\nT = 2 x 3.1416 x 0.3194 = 2.007 s\nf = 1/T = 1/2.007 = 0.498 Hz\n\nRESULT: time period = 2.01 s and frequency = 0.50 Hz", marks: 5, level: "both", topic: "Oscillations" },
    { question: "A stone is dropped from the top of a tower and reaches the ground in 4 s. Find the height of the tower and the velocity with which it strikes the ground. (g = 9.8 m s^-2)", formula: "S = ut + (1/2)gt^2 ; v = u + gt", solution: "GIVEN:\nu = 0 m s^-1 (dropped), t = 4 s, g = 9.8 m s^-2\n\nREQUIRED: h = ? , v = ?\n\nFORMULA: S = ut + (1/2)gt^2 and v = u + gt\n\nWORKING:\nh = (0)(4) + (1/2)(9.8)(4)^2\nh = (1/2)(9.8)(16) = 4.9 x 16 = 78.4 m\nv = 0 + (9.8)(4) = 39.2 m s^-1\n\nRESULT: height of the tower = 78.4 m and striking velocity = 39.2 m s^-1", marks: 5, level: "both", topic: "Kinematics" },
    { question: "A machine lifts a load of 500 N through 6 m in 10 s. Calculate the work done and the power developed.", formula: "W = F x d ; P = W/t", solution: "GIVEN:\nF = 500 N, d = 6 m, t = 10 s\n\nREQUIRED: W = ? , P = ?\n\nFORMULA: W = F x d and P = W/t\n\nWORKING:\nW = 500 x 6 = 3000 J\nP = 3000/10 = 300 W\nIn horsepower: 300/746 = 0.402 hp\n\nRESULT: work done = 3000 J and power = 300 W (about 0.4 hp)", marks: 5, level: "both", topic: "Work and Energy" },
    { question: "Calculate the energy of a photon of light whose wavelength is 500 nm. (h = 6.63 x 10^-34 J s, c = 3 x 10^8 m s^-1)", formula: "E = hf = hc/lambda", solution: "GIVEN:\nlambda = 500 nm = 500 x 10^-9 m = 5 x 10^-7 m\nh = 6.63 x 10^-34 J s, c = 3 x 10^8 m s^-1\n\nREQUIRED: E = ?\n\nFORMULA: E = hc/lambda\n\nWORKING:\nhc = (6.63 x 10^-34)(3 x 10^8) = 19.89 x 10^-26 J m\nE = (19.89 x 10^-26) / (5 x 10^-7)\nE = 3.978 x 10^-19 J\nIn electron volts: E = (3.978 x 10^-19)/(1.6 x 10^-19) = 2.49 eV\n\nRESULT: energy of the photon = 3.98 x 10^-19 J (about 2.49 eV)", marks: 5, level: "inter", topic: "Modern Physics" },
    { question: "A Carnot engine operates between a source at 500 K and a sink at 300 K. Calculate its efficiency and the work output if it absorbs 1200 J of heat.", formula: "efficiency = 1 - T2/T1 ; W = efficiency x Q1", solution: "GIVEN:\nT1 = 500 K, T2 = 300 K, Q1 = 1200 J\n\nREQUIRED: efficiency = ? , W = ?\n\nFORMULA: efficiency = 1 - T2/T1\n\nWORKING:\nefficiency = 1 - 300/500 = 1 - 0.6 = 0.4\nPercentage efficiency = 0.4 x 100 = 40%\nW = efficiency x Q1 = 0.4 x 1200 = 480 J\nHeat rejected Q2 = 1200 - 480 = 720 J\n\nRESULT: efficiency = 40%, work output = 480 J, heat rejected = 720 J", marks: 5, level: "inter", topic: "Thermodynamics" },
    { question: "Find the equivalent resistance when resistors of 6 ohm and 3 ohm are connected (i) in series and (ii) in parallel.", formula: "Series: Re = R1 + R2 ; Parallel: 1/Re = 1/R1 + 1/R2", solution: "GIVEN:\nR1 = 6 ohm, R2 = 3 ohm\n\nREQUIRED: Re (series) = ? , Re (parallel) = ?\n\nWORKING:\n(i) Series: Re = R1 + R2 = 6 + 3 = 9 ohm\n\n(ii) Parallel: 1/Re = 1/6 + 1/3\nTaking LCM = 6: 1/Re = 1/6 + 2/6 = 3/6 = 1/2\nRe = 2 ohm\n\nRESULT: series equivalent = 9 ohm and parallel equivalent = 2 ohm\n(Note the parallel value is less than the smaller resistance, as expected.)", marks: 5, level: "both", topic: "Current Electricity" },
  ],
};

/* ============================== CHEMISTRY ============================== */
const chemistry: ExamSubjectBank = {
  mcqs: [
    { question: "The atomic number of an element represents the number of:", options: ["Protons", "Neutrons", "Nucleons", "Electrons in the outer shell"], correctIndex: 0, explanation: "The atomic number Z equals the number of protons and, in a neutral atom, the number of electrons.", level: "both", topic: "Atomic Structure" },
    { question: "Avogadro's number is:", options: ["6.02 x 10^23", "6.02 x 10^-23", "3.01 x 10^23", "1.6 x 10^-19"], correctIndex: 0, explanation: "One mole of any substance contains 6.02 x 10^23 particles.", level: "both", topic: "Mole Concept" },
    { question: "The pH of a neutral solution at 25 C is:", options: ["7", "0", "14", "1"], correctIndex: 0, explanation: "In pure water [H+] = 10^-7 mol/dm^3, so pH = 7.", level: "both", topic: "Acids and Bases" },
    { question: "Which of the following is an example of a covalent compound?", options: ["Methane (CH4)", "Sodium chloride", "Magnesium oxide", "Calcium fluoride"], correctIndex: 0, explanation: "Methane is formed by the sharing of electron pairs between carbon and hydrogen.", level: "both", topic: "Chemical Bonding" },
    { question: "The number of electrons that can be accommodated in the M shell is:", options: ["18", "8", "2", "32"], correctIndex: 0, explanation: "The maximum number is 2n^2; for n = 3 this gives 18.", level: "both", topic: "Atomic Structure" },
    { question: "Which gas is evolved when a metal reacts with a dilute acid?", options: ["Hydrogen", "Oxygen", "Carbon dioxide", "Nitrogen"], correctIndex: 0, explanation: "Metal + dilute acid gives salt + hydrogen gas, which burns with a pop sound.", level: "both", topic: "Acids and Bases" },
    { question: "The oxidation state of oxygen in most of its compounds is:", options: ["-2", "+2", "-1", "0"], correctIndex: 0, explanation: "Oxygen usually shows -2 except in peroxides (-1) and OF2 (+2).", level: "both", topic: "Redox" },
    { question: "Isotopes of an element have the same number of protons but different numbers of:", options: ["Neutrons", "Electrons", "Protons", "Shells"], correctIndex: 0, explanation: "Isotopes differ in mass number because of different neutron counts.", level: "both", topic: "Atomic Structure" },
    { question: "A catalyst affects a chemical reaction by:", options: ["Lowering the activation energy", "Increasing the yield", "Changing the equilibrium constant", "Raising the temperature"], correctIndex: 0, explanation: "A catalyst provides an alternative path of lower activation energy; it does not shift the equilibrium position.", level: "both", topic: "Reaction Kinetics" },
    { question: "Which of the following is the general formula of alkanes?", options: ["CnH2n+2", "CnH2n", "CnH2n-2", "CnHn"], correctIndex: 0, explanation: "Alkanes are saturated hydrocarbons with only single bonds.", level: "both", topic: "Organic Chemistry" },
    { question: "The bond formed by the complete transfer of electrons is called:", options: ["Ionic bond", "Covalent bond", "Coordinate bond", "Hydrogen bond"], correctIndex: 0, explanation: "One atom loses and another gains electrons, producing oppositely charged ions.", level: "both", topic: "Chemical Bonding" },
    { question: "Which element has the highest electronegativity?", options: ["Fluorine", "Oxygen", "Chlorine", "Nitrogen"], correctIndex: 0, explanation: "Fluorine has the highest electronegativity value of 4.0 on the Pauling scale.", level: "both", topic: "Periodic Table" },
    { question: "Standard temperature and pressure (STP) corresponds to:", options: ["273 K and 1 atm", "298 K and 1 atm", "273 K and 2 atm", "0 K and 1 atm"], correctIndex: 0, explanation: "At STP one mole of an ideal gas occupies 22.4 dm^3.", level: "both", topic: "Gases" },
    { question: "The functional group of alcohols is:", options: ["-OH", "-CHO", "-COOH", "-NH2"], correctIndex: 0, explanation: "The hydroxyl group -OH characterises alcohols.", level: "both", topic: "Organic Chemistry" },
    { question: "Which quantum number describes the shape of an orbital?", options: ["Azimuthal quantum number (l)", "Principal quantum number (n)", "Magnetic quantum number (m)", "Spin quantum number (s)"], correctIndex: 0, explanation: "l determines the subshell and hence the shape: s spherical, p dumb-bell.", level: "inter", topic: "Atomic Structure" },
    { question: "According to Le Chatelier's principle, increasing pressure on an equilibrium shifts it towards:", options: ["The side with fewer moles of gas", "The side with more moles of gas", "The reactants always", "No change"], correctIndex: 0, explanation: "The system relieves the applied stress by reducing the total number of gas molecules.", level: "inter", topic: "Equilibrium" },
    { question: "The hybridisation of carbon in ethene (C2H4) is:", options: ["sp2", "sp3", "sp", "dsp2"], correctIndex: 0, explanation: "Each carbon forms three sigma bonds and one pi bond, giving trigonal planar sp2 hybridisation.", level: "inter", topic: "Chemical Bonding" },
    { question: "Which of the following is a strong electrolyte?", options: ["NaCl solution", "Acetic acid", "Ammonia solution", "Sugar solution"], correctIndex: 0, explanation: "Sodium chloride ionises completely in water, giving high conductivity.", level: "both", topic: "Electrochemistry" },
  ],
  shorts: [
    { question: "Define an atom, a molecule and an ion.", modelAnswer: "An atom is the smallest particle of an element that can take part in a chemical reaction and may or may not exist independently. A molecule is the smallest particle of a substance that can exist independently and retains all the properties of that substance, e.g. O2, H2O. An ion is an atom or group of atoms carrying a positive charge (cation, formed by loss of electrons) or a negative charge (anion, formed by gain of electrons).", level: "both", topic: "Basic Concepts" },
    { question: "Differentiate between an ionic and a covalent bond.", modelAnswer: "An ionic bond is formed by the complete transfer of electrons from a metal to a non-metal, producing oppositely charged ions held by electrostatic attraction; such compounds have high melting points, are soluble in water and conduct electricity when molten or dissolved, e.g. NaCl. A covalent bond is formed by the mutual sharing of electron pairs between non-metals; such compounds have low melting points, are usually insoluble in water and do not conduct electricity, e.g. CH4.", level: "both", topic: "Chemical Bonding" },
    { question: "What is meant by the mole? Calculate the mass of one mole of water.", modelAnswer: "A mole is the amount of a substance that contains 6.02 x 10^23 particles (Avogadro's number), which is numerically equal to its formula mass expressed in grams. For water H2O: H = 1 x 2 = 2, O = 16, so molar mass = 18 g mol^-1. Therefore one mole of water has a mass of 18 g and contains 6.02 x 10^23 molecules.", level: "both", topic: "Mole Concept" },
    { question: "State Boyle's law and Charles's law.", modelAnswer: "Boyle's law: at constant temperature the volume of a given mass of gas is inversely proportional to the applied pressure, V proportional to 1/P, so P1V1 = P2V2. Charles's law: at constant pressure the volume of a given mass of gas is directly proportional to its absolute temperature, V proportional to T, so V1/T1 = V2/T2. Temperature must always be taken in kelvin.", level: "both", topic: "Gases" },
    { question: "Define acids and bases according to the Bronsted-Lowry concept.", modelAnswer: "According to Bronsted and Lowry, an acid is a substance that donates a proton (H+) and a base is a substance that accepts a proton. For example, in HCl + H2O giving H3O+ + Cl-, HCl is the acid because it donates a proton and water is the base because it accepts one. Every acid has a conjugate base and every base a conjugate acid; here Cl- is the conjugate base of HCl.", level: "both", topic: "Acids and Bases" },
    { question: "What is meant by electronegativity? How does it vary in the periodic table?", modelAnswer: "Electronegativity is the relative tendency of an atom to attract the shared pair of electrons towards itself in a covalent bond. Along a period from left to right it increases because nuclear charge increases while the atomic size decreases. Down a group it decreases because the atomic size and shielding effect increase, weakening the attraction of the nucleus for the bonding electrons. Fluorine is the most electronegative element (4.0).", level: "both", topic: "Periodic Table" },
    { question: "Distinguish between an exothermic and an endothermic reaction.", modelAnswer: "In an exothermic reaction heat is released to the surroundings, the temperature rises, the enthalpy change delta-H is negative and the products have less energy than the reactants, e.g. combustion of methane, neutralisation. In an endothermic reaction heat is absorbed from the surroundings, the temperature falls, delta-H is positive and the products have more energy than the reactants, e.g. photosynthesis and the decomposition of limestone.", level: "both", topic: "Thermochemistry" },
    { question: "What are isotopes? Give two examples.", modelAnswer: "Isotopes are atoms of the same element having the same atomic number but different mass numbers due to a different number of neutrons. They have identical chemical properties but slightly different physical properties. Examples: hydrogen has three isotopes, protium (1H), deuterium (2H) and tritium (3H); carbon has C-12, C-13 and the radioactive C-14 used in carbon dating.", level: "both", topic: "Atomic Structure" },
    { question: "Define oxidation and reduction in terms of electrons.", modelAnswer: "Oxidation is the loss of electrons by an atom or ion, accompanied by an increase in oxidation number. Reduction is the gain of electrons, accompanied by a decrease in oxidation number. Both always occur together in a redox reaction. The species that loses electrons is the reducing agent and the one that gains electrons is the oxidising agent. Mnemonic: OIL RIG (Oxidation Is Loss, Reduction Is Gain).", level: "both", topic: "Redox" },
    { question: "What is a catalyst? Write two of its characteristics.", modelAnswer: "A catalyst is a substance that alters the rate of a chemical reaction without itself being permanently consumed. Characteristics: (i) it remains chemically unchanged in mass and composition at the end of the reaction; (ii) it works by providing an alternative pathway of lower activation energy; (iii) it is required only in a small quantity; (iv) it does not shift the position of equilibrium but helps it to be reached faster.", level: "both", topic: "Reaction Kinetics" },
    { question: "Explain the term 'hydrogen bonding' and its effect on the boiling point of water.", modelAnswer: "A hydrogen bond is a weak electrostatic attraction between a hydrogen atom covalently bonded to a highly electronegative atom (F, O or N) and a lone pair on another such electronegative atom. In water each molecule can form up to four hydrogen bonds. Because considerable extra energy is needed to break this extensive network, water has an abnormally high boiling point of 100 C compared with H2S, which boils at -60 C despite having a greater molar mass.", level: "both", topic: "Chemical Bonding" },
    { question: "State Le Chatelier's principle.", modelAnswer: "If a stress (change in concentration, pressure or temperature) is applied to a system at equilibrium, the system shifts in the direction that tends to relieve that stress and a new equilibrium is established. For example, increasing the pressure on N2 + 3H2 in equilibrium with 2NH3 shifts the equilibrium to the right, towards the smaller number of gaseous moles, increasing the yield of ammonia.", level: "inter", topic: "Equilibrium" },
    { question: "Differentiate between empirical and molecular formula with an example.", modelAnswer: "An empirical formula gives the simplest whole-number ratio of the atoms of each element present in a compound. A molecular formula gives the actual number of atoms of each element in one molecule. Molecular formula = n x empirical formula, where n = molar mass / empirical formula mass. Example: glucose has the empirical formula CH2O (mass 30) and molecular formula C6H12O6 (mass 180), so n = 6. For benzene these are CH and C6H6.", level: "both", topic: "Mole Concept" },
    { question: "What are alkanes, alkenes and alkynes?", modelAnswer: "Alkanes are saturated hydrocarbons containing only carbon-carbon single bonds, general formula CnH2n+2, relatively unreactive and undergo substitution, e.g. methane. Alkenes contain at least one carbon-carbon double bond, general formula CnH2n, and are reactive, undergoing addition reactions, e.g. ethene. Alkynes contain at least one carbon-carbon triple bond, general formula CnH2n-2, and are the most reactive, e.g. ethyne (acetylene).", level: "both", topic: "Organic Chemistry" },
  ],
  longs: [
    { a: { question: "Describe the modern periodic table and discuss the periodic trends in atomic radius and ionisation energy.", modelAnswer: "The modern periodic law states that the properties of elements are a periodic function of their atomic numbers. The long form of the periodic table arranges the elements in order of increasing atomic number in 7 horizontal periods and 18 vertical groups, divided into s, p, d and f blocks according to the subshell receiving the last electron. Atomic radius: along a period it decreases because the nuclear charge increases while electrons enter the same shell, so the nucleus pulls them closer. Down a group it increases because a new shell is added and the shielding effect increases. Ionisation energy is the minimum energy required to remove the most loosely bound electron from an isolated gaseous atom. Along a period it increases because of higher nuclear charge and smaller size, and down a group it decreases because the outer electron is farther away and better shielded. Noble gases have the highest ionisation energies because of their stable configurations." }, b: { question: "Explain the terms electron affinity and electronegativity and state their periodic trends.", modelAnswer: "Electron affinity is the energy released when an electron is added to an isolated gaseous atom to form a negative ion. It generally increases along a period because the smaller atom with higher nuclear charge attracts the incoming electron strongly, and decreases down a group because of increasing size. Halogens have the highest electron affinities as they need only one electron to complete the octet; chlorine actually has a higher value than fluorine because of electron-electron repulsion in the small 2p subshell of fluorine. Electronegativity is the relative tendency of a bonded atom to attract the shared electron pair. It increases along a period and decreases down a group. The difference in electronegativity determines bond character: a difference greater than 1.7 gives a predominantly ionic bond, while a smaller difference gives a polar or non-polar covalent bond." }, level: "both", topic: "Periodic Table" },
    { a: { question: "What are the postulates of Bohr's atomic model? State its achievements and defects.", modelAnswer: "Postulates: (1) The electron revolves around the nucleus only in certain permitted circular orbits called stationary states, in which it does not radiate energy. (2) Only those orbits are allowed for which the angular momentum is an integral multiple of h/2pi, i.e. mvr = nh/2pi. (3) Energy is emitted or absorbed only when an electron jumps from one orbit to another, and the energy difference equals hf = E2 - E1. Achievements: it successfully explained the stability of the atom, derived the radius (0.529 Angstrom for hydrogen) and energy of orbits, and accurately explained the line spectrum of hydrogen including the Lyman, Balmer and Paschen series. Defects: it fails for atoms with more than one electron, cannot explain the fine structure of spectral lines, the Zeeman and Stark effects, or the shapes of molecules, and it contradicts Heisenberg's uncertainty principle by assigning a definite orbit and momentum simultaneously." }, b: { question: "Define the four quantum numbers and explain what each specifies.", modelAnswer: "(1) Principal quantum number (n = 1, 2, 3 ...) determines the main energy level or shell, the size of the orbital and largely the energy of the electron; the maximum number of electrons in a shell is 2n^2. (2) Azimuthal or angular momentum quantum number (l = 0 to n-1) determines the subshell and shape of the orbital: l = 0 is s (spherical), 1 is p (dumb-bell), 2 is d and 3 is f. (3) Magnetic quantum number (m = -l to +l including zero) determines the orientation of the orbital in space; a p subshell has three orientations px, py and pz. (4) Spin quantum number (s = +1/2 or -1/2) describes the direction of spin of the electron about its own axis. According to Pauli's exclusion principle, no two electrons in an atom can have all four quantum numbers the same." }, level: "inter", topic: "Atomic Structure" },
    { a: { question: "Describe the manufacture of ammonia by the Haber process, stating the optimum conditions and their justification.", modelAnswer: "Ammonia is prepared industrially by the direct combination of nitrogen and hydrogen: N2(g) + 3H2(g) in equilibrium with 2NH3(g), delta-H = -92 kJ/mol. The reaction is reversible, exothermic and proceeds with a decrease in the number of gaseous moles (4 to 2). Optimum conditions: (1) Pressure of about 200 atmospheres, since high pressure shifts the equilibrium towards the side of fewer moles and increases the yield; still higher pressures are avoided for reasons of cost and plant safety. (2) Temperature of about 450 to 500 C. Le Chatelier's principle predicts a better yield at low temperature since the reaction is exothermic, but the rate would then be uneconomically slow; 450 C is a compromise between yield and rate. (3) Finely divided iron catalyst promoted with potassium and aluminium oxides increases the rate without disturbing the equilibrium. (4) Ammonia is continuously liquefied and removed while unreacted gases are recycled, which shifts the equilibrium to the right." }, b: { question: "State Le Chatelier's principle and apply it to the effects of concentration, pressure and temperature on the equilibrium N2 + 3H2 in equilibrium with 2NH3." , modelAnswer: "Le Chatelier's principle: if a stress is applied to a system at equilibrium, the system shifts in the direction that relieves the stress. Concentration: adding more N2 or H2 shifts the equilibrium to the right and increases the yield of ammonia; removing NH3 as it forms has the same effect. Pressure: the forward reaction reduces 4 moles of gas to 2, so increasing pressure shifts the equilibrium to the right and increases the yield, while lowering pressure favours the reverse reaction. Temperature: the forward reaction is exothermic, so increasing temperature shifts the equilibrium to the left and lowers the yield, whereas lowering the temperature increases the yield but slows the rate. A catalyst has no effect on the position of equilibrium; it only allows equilibrium to be attained more quickly." }, level: "inter", topic: "Equilibrium" },
    { a: { question: "What is meant by the rate of reaction? Discuss the factors affecting it.", modelAnswer: "The rate of a reaction is the change in the concentration of a reactant or product per unit time, expressed in mol dm^-3 s^-1. Factors: (1) Nature of reactants - ionic reactions are almost instantaneous while covalent reactions are slower. (2) Concentration - increasing concentration increases the number of molecules per unit volume and hence the frequency of effective collisions. (3) Surface area - a powdered solid reacts much faster than a lump because more particles are exposed. (4) Temperature - a rise of 10 C roughly doubles the rate, since more molecules acquire energy equal to or greater than the activation energy. (5) Catalyst - lowers the activation energy by providing an alternative pathway, greatly increasing the rate. (6) Light - some reactions such as the chlorination of methane and photosynthesis are accelerated by light." }, b: { question: "Define activation energy and explain it with an energy-profile diagram.", modelAnswer: "Activation energy (Ea) is the minimum amount of energy that colliding reactant molecules must possess in order to form the activated complex and be converted into products. On an energy-profile diagram, energy is plotted against the reaction pathway. Reactants start at a certain energy level, rise to a peak representing the transition state or activated complex, and then fall to the level of the products. The height from the reactants to the peak is the activation energy of the forward reaction. If the products lie below the reactants, delta-H is negative and the reaction is exothermic; if above, delta-H is positive and it is endothermic. A catalyst lowers the peak, reducing Ea for both forward and reverse reactions equally, so it speeds up both without altering delta-H or the equilibrium position." }, level: "both", topic: "Reaction Kinetics" },
  ],
  numericals: [
    { question: "Calculate the number of moles and the number of molecules present in 88 g of carbon dioxide (CO2). (C = 12, O = 16)", formula: "n = mass / molar mass ; N = n x 6.02 x 10^23", solution: "GIVEN:\nMass of CO2 = 88 g\n\nREQUIRED: number of moles n = ? , number of molecules N = ?\n\nFORMULA: n = mass / molar mass\n\nWORKING:\nMolar mass of CO2 = 12 + (2 x 16) = 12 + 32 = 44 g mol^-1\nn = 88 / 44 = 2 mol\nN = n x Avogadro's number = 2 x 6.02 x 10^23\nN = 1.204 x 10^24 molecules\n\nRESULT: 2 moles of CO2 containing 1.204 x 10^24 molecules", marks: 5, level: "both", topic: "Mole Concept" },
    { question: "A solution contains 25 g of NaCl dissolved in 475 g of water. Calculate the mass percentage of the solute.", formula: "mass % = (mass of solute / mass of solution) x 100", solution: "GIVEN:\nMass of solute (NaCl) = 25 g\nMass of solvent (water) = 475 g\n\nREQUIRED: mass percentage = ?\n\nFORMULA: mass % = (mass of solute / total mass of solution) x 100\n\nWORKING:\nTotal mass of solution = 25 + 475 = 500 g\nmass % = (25 / 500) x 100\nmass % = 0.05 x 100 = 5%\n\nRESULT: the solution is 5% NaCl by mass", marks: 5, level: "both", topic: "Solutions" },
    { question: "Calculate the pH of a solution whose hydrogen ion concentration is 1 x 10^-4 mol dm^-3. Also state whether it is acidic or basic.", formula: "pH = -log[H+] ; pOH = 14 - pH", solution: "GIVEN:\n[H+] = 1 x 10^-4 mol dm^-3\n\nREQUIRED: pH = ?\n\nFORMULA: pH = -log[H+]\n\nWORKING:\npH = -log(1 x 10^-4)\npH = -(log 1 + log 10^-4)\npH = -(0 + (-4)) = 4\npOH = 14 - 4 = 10\n\nRESULT: pH = 4. Since the pH is less than 7, the solution is ACIDIC.", marks: 5, level: "both", topic: "Acids and Bases" },
    { question: "A gas occupies 500 cm^3 at a pressure of 760 mm Hg. What volume will it occupy at 950 mm Hg if the temperature remains constant?", formula: "Boyle's law: P1V1 = P2V2", solution: "GIVEN:\nP1 = 760 mm Hg, V1 = 500 cm^3\nP2 = 950 mm Hg, T = constant\n\nREQUIRED: V2 = ?\n\nFORMULA (Boyle's law): P1V1 = P2V2\n\nWORKING:\nV2 = (P1 x V1) / P2\nV2 = (760 x 500) / 950\nV2 = 380000 / 950\nV2 = 400 cm^3\n\nRESULT: the new volume is 400 cm^3. The volume decreased because the pressure increased, as required by Boyle's law.", marks: 5, level: "both", topic: "Gases" },
    { question: "Determine the empirical formula of a compound containing 40% carbon, 6.7% hydrogen and 53.3% oxygen by mass. (C = 12, H = 1, O = 16)", formula: "moles = % / atomic mass ; divide by smallest", solution: "GIVEN:\nC = 40%, H = 6.7%, O = 53.3%\n\nREQUIRED: empirical formula = ?\n\nWORKING:\nStep 1 - moles of each element:\nC = 40 / 12 = 3.33\nH = 6.7 / 1 = 6.70\nO = 53.3 / 16 = 3.33\n\nStep 2 - divide by the smallest value (3.33):\nC = 3.33 / 3.33 = 1\nH = 6.70 / 3.33 = 2\nO = 3.33 / 3.33 = 1\n\nStep 3 - simplest whole-number ratio C : H : O = 1 : 2 : 1\n\nRESULT: the empirical formula is CH2O (this corresponds to formaldehyde; glucose C6H12O6 has the same empirical formula).", marks: 5, level: "both", topic: "Mole Concept" },
    { question: "Calculate the molarity of a solution prepared by dissolving 9.8 g of H2SO4 in enough water to make 500 cm^3 of solution. (H = 1, S = 32, O = 16)", formula: "M = (mass / molar mass) x (1000 / volume in cm^3)", solution: "GIVEN:\nMass of H2SO4 = 9.8 g\nVolume of solution = 500 cm^3 = 0.5 dm^3\n\nREQUIRED: molarity M = ?\n\nFORMULA: M = number of moles / volume in dm^3\n\nWORKING:\nMolar mass of H2SO4 = (2 x 1) + 32 + (4 x 16) = 2 + 32 + 64 = 98 g mol^-1\nNumber of moles = 9.8 / 98 = 0.1 mol\nM = 0.1 / 0.5 = 0.2 mol dm^-3\n\nRESULT: the molarity of the solution is 0.2 M", marks: 5, level: "both", topic: "Solutions" },
    { question: "A sample of gas occupies 250 cm^3 at 27 C. What volume will it occupy at 127 C if the pressure is kept constant?", formula: "Charles's law: V1/T1 = V2/T2 (T in kelvin)", solution: "GIVEN:\nV1 = 250 cm^3\nT1 = 27 C = 27 + 273 = 300 K\nT2 = 127 C = 127 + 273 = 400 K\n\nREQUIRED: V2 = ?\n\nFORMULA (Charles's law): V1/T1 = V2/T2\n\nWORKING:\nV2 = (V1 x T2) / T1\nV2 = (250 x 400) / 300\nV2 = 100000 / 300\nV2 = 333.3 cm^3\n\nRESULT: the new volume is 333.3 cm^3. The volume increased because the absolute temperature increased.", marks: 5, level: "both", topic: "Gases" },
    { question: "How many grams of oxygen are required to completely burn 16 g of methane (CH4)? (C = 12, H = 1, O = 16)", formula: "CH4 + 2O2 -> CO2 + 2H2O ; use mole ratio", solution: "GIVEN:\nMass of CH4 = 16 g\n\nBALANCED EQUATION:\nCH4 + 2O2 -> CO2 + 2H2O\n\nWORKING:\nMolar mass of CH4 = 12 + 4 = 16 g mol^-1\nMoles of CH4 = 16 / 16 = 1 mol\n\nFrom the equation, 1 mol CH4 requires 2 mol O2.\nMoles of O2 required = 2 mol\nMolar mass of O2 = 32 g mol^-1\nMass of O2 = 2 x 32 = 64 g\n\nRESULT: 64 g of oxygen are required for complete combustion.", marks: 5, level: "both", topic: "Stoichiometry" },
  ],
};

/* ============================== MATHEMATICS ============================== */
const math: ExamSubjectBank = {
  mcqs: [
    { question: "If A is a 2x2 matrix and |A| = 0, then A is called:", options: ["Singular matrix", "Non-singular matrix", "Identity matrix", "Symmetric matrix"], correctIndex: 0, explanation: "A matrix whose determinant is zero is singular and has no inverse.", level: "both", topic: "Matrices" },
    { question: "The nth term of an arithmetic progression is given by:", options: ["a + (n-1)d", "a r^(n-1)", "na + d", "(a+d)/n"], correctIndex: 0, explanation: "In an A.P. each term exceeds the previous one by the common difference d.", level: "both", topic: "Sequences and Series" },
    { question: "The solution set of the equation x^2 - 9 = 0 is:", options: ["{3, -3}", "{3}", "{9, -9}", "{0}"], correctIndex: 0, explanation: "x^2 = 9 gives x = plus or minus 3.", level: "both", topic: "Quadratic Equations" },
    { question: "The value of sin 30 degrees is:", options: ["1/2", "1", "0", "sqrt(3)/2"], correctIndex: 0, explanation: "sin 30 = 1/2 is a standard trigonometric value.", level: "both", topic: "Trigonometry" },
    { question: "The discriminant of the quadratic equation ax^2 + bx + c = 0 is:", options: ["b^2 - 4ac", "b^2 + 4ac", "4ac - b^2", "sqrt(b^2 - 4ac)"], correctIndex: 0, explanation: "If b^2 - 4ac > 0 the roots are real and distinct, if = 0 real and equal, if < 0 imaginary.", level: "both", topic: "Quadratic Equations" },
    { question: "log(mn) is equal to:", options: ["log m + log n", "log m - log n", "log m x log n", "n log m"], correctIndex: 0, explanation: "The product law of logarithms converts multiplication into addition.", level: "both", topic: "Logarithms" },
    { question: "The derivative of x^n with respect to x is:", options: ["n x^(n-1)", "x^(n-1)", "n x^n", "x^n / n"], correctIndex: 0, explanation: "This is the power rule of differentiation.", level: "inter", topic: "Differentiation" },
    { question: "The integral of 1/x dx is:", options: ["ln|x| + c", "x^2/2 + c", "-1/x^2 + c", "1/x + c"], correctIndex: 0, explanation: "The antiderivative of the reciprocal function is the natural logarithm.", level: "inter", topic: "Integration" },
    { question: "The area of a circle of radius r is:", options: ["pi r^2", "2 pi r", "pi d", "4/3 pi r^3"], correctIndex: 0, explanation: "2 pi r is the circumference; (4/3) pi r^3 is the volume of a sphere.", level: "both", topic: "Mensuration" },
    { question: "If sin(theta) = 3/5, then cos(theta) equals (for an acute angle):", options: ["4/5", "5/4", "3/4", "5/3"], correctIndex: 0, explanation: "By the Pythagorean identity, cos = sqrt(1 - 9/25) = sqrt(16/25) = 4/5.", level: "both", topic: "Trigonometry" },
    { question: "The sum of the first n natural numbers is:", options: ["n(n+1)/2", "n(n-1)/2", "n^2", "n(n+1)(2n+1)/6"], correctIndex: 0, explanation: "This is the sum of an A.P. with a = 1 and d = 1.", level: "both", topic: "Sequences and Series" },
    { question: "Two lines are perpendicular if the product of their slopes is:", options: ["-1", "1", "0", "Undefined"], correctIndex: 0, explanation: "m1 x m2 = -1 for perpendicular lines; equal slopes mean parallel lines.", level: "both", topic: "Coordinate Geometry" },
    { question: "The value of cos^2(theta) + sin^2(theta) is:", options: ["1", "0", "2", "tan(theta)"], correctIndex: 0, explanation: "This is the fundamental Pythagorean trigonometric identity.", level: "both", topic: "Trigonometry" },
    { question: "The distance between the points (0,0) and (3,4) is:", options: ["5", "7", "12", "25"], correctIndex: 0, explanation: "d = sqrt(3^2 + 4^2) = sqrt(25) = 5.", level: "both", topic: "Coordinate Geometry" },
    { question: "If the ratio a:b = 2:3 and b:c = 4:5, then a:c is:", options: ["8:15", "2:5", "6:20", "3:4"], correctIndex: 0, explanation: "a:b:c = 8:12:15, so a:c = 8:15.", level: "both", topic: "Ratio and Proportion" },
    { question: "The order of the matrix having 3 rows and 4 columns is:", options: ["3 x 4", "4 x 3", "12", "7"], correctIndex: 0, explanation: "Order is written as (number of rows) x (number of columns).", level: "both", topic: "Matrices" },
    { question: "The limit of (sin x)/x as x approaches 0 is:", options: ["1", "0", "Infinity", "Undefined"], correctIndex: 0, explanation: "This standard limit is proved by the sandwich theorem.", level: "inter", topic: "Limits" },
    { question: "The general term of a geometric progression is:", options: ["a r^(n-1)", "a + (n-1)d", "a r^n", "a/(1-r)"], correctIndex: 0, explanation: "Each term of a G.P. is obtained by multiplying the previous term by the common ratio r.", level: "both", topic: "Sequences and Series" },
    { question: "The slope of the line 2x + 3y - 6 = 0 is:", options: ["-2/3", "2/3", "3/2", "-3/2"], correctIndex: 0, explanation: "Writing as y = (-2/3)x + 2, the coefficient of x is the slope.", level: "both", topic: "Coordinate Geometry" },
    { question: "If A and B are two sets, then A intersection B contains:", options: ["Elements common to both A and B", "All elements of A and B", "Elements of A only", "The empty set always"], correctIndex: 0, explanation: "The intersection is the set of elements belonging to both sets.", level: "both", topic: "Sets" },
  ],
  shorts: [
    { question: "Define a singular and a non-singular matrix with an example of each.", modelAnswer: "A square matrix A is singular if its determinant is zero, |A| = 0; such a matrix has no inverse. Example: A = [[2, 4],[1, 2]] has |A| = (2)(2) - (4)(1) = 0, so it is singular. A matrix is non-singular if |A| is not equal to zero, and it possesses a unique inverse. Example: B = [[3, 1],[2, 4]] has |B| = 12 - 2 = 10, so B is non-singular.", level: "both", topic: "Matrices" },
    { question: "Find the sum of the first 20 terms of the A.P. 3, 7, 11, ...", modelAnswer: "Here a = 3, d = 7 - 3 = 4 and n = 20. Using Sn = (n/2)[2a + (n-1)d]: S20 = (20/2)[2(3) + (20-1)(4)] = 10[6 + 76] = 10 x 82 = 820. Therefore the sum of the first 20 terms is 820.", level: "both", topic: "Sequences and Series" },
    { question: "Solve the quadratic equation x^2 - 5x + 6 = 0 by factorisation.", modelAnswer: "x^2 - 5x + 6 = 0. We need two numbers whose product is 6 and whose sum is -5; these are -2 and -3. So x^2 - 2x - 3x + 6 = 0, giving x(x - 2) - 3(x - 2) = 0, hence (x - 2)(x - 3) = 0. Therefore x = 2 or x = 3, and the solution set is {2, 3}.", level: "both", topic: "Quadratic Equations" },
    { question: "State and verify the Pythagorean identity sin^2(theta) + cos^2(theta) = 1 for theta = 30 degrees.", modelAnswer: "The identity states that for any angle theta, sin^2(theta) + cos^2(theta) = 1. Verification for theta = 30: sin 30 = 1/2 and cos 30 = sqrt(3)/2. Then sin^2 30 + cos^2 30 = (1/2)^2 + (sqrt(3)/2)^2 = 1/4 + 3/4 = 4/4 = 1. Hence the identity is verified.", level: "both", topic: "Trigonometry" },
    { question: "Define the discriminant and state the nature of the roots for each case.", modelAnswer: "For ax^2 + bx + c = 0 the discriminant is D = b^2 - 4ac. (i) If D > 0 and is a perfect square, the roots are real, rational and unequal. (ii) If D > 0 but not a perfect square, the roots are real, irrational and unequal. (iii) If D = 0, the roots are real, rational and equal. (iv) If D < 0, the roots are imaginary (complex conjugates).", level: "both", topic: "Quadratic Equations" },
    { question: "Write the laws of logarithms.", modelAnswer: "(1) Product law: log(mn) = log m + log n. (2) Quotient law: log(m/n) = log m - log n. (3) Power law: log(m^n) = n log m. (4) Change of base: log_b(m) = log_a(m) / log_a(b). Also log_a(a) = 1 and log_a(1) = 0. These laws hold only for positive values of m and n.", level: "both", topic: "Logarithms" },
    { question: "Differentiate y = 3x^4 - 5x^2 + 7 with respect to x.", modelAnswer: "Applying the power rule d/dx(x^n) = n x^(n-1) term by term: dy/dx = 3(4x^3) - 5(2x) + 0 = 12x^3 - 10x. The derivative of the constant 7 is zero.", level: "inter", topic: "Differentiation" },
    { question: "Evaluate the integral of (2x + 3) dx.", modelAnswer: "Integrating term by term using the power rule for integration, the integral of x^n dx = x^(n+1)/(n+1) + c: integral of (2x + 3) dx = 2(x^2/2) + 3x + c = x^2 + 3x + c, where c is the constant of integration.", level: "inter", topic: "Integration" },
    { question: "Find the distance between the points A(2, 3) and B(6, 6).", modelAnswer: "Using the distance formula d = sqrt((x2-x1)^2 + (y2-y1)^2): d = sqrt((6-2)^2 + (6-3)^2) = sqrt(4^2 + 3^2) = sqrt(16 + 9) = sqrt(25) = 5 units.", level: "both", topic: "Coordinate Geometry" },
    { question: "Define an arithmetic mean and find the A.M. between 8 and 20.", modelAnswer: "The arithmetic mean between two numbers a and b is the number A such that a, A, b form an arithmetic progression, given by A = (a + b)/2. For a = 8 and b = 20: A = (8 + 20)/2 = 28/2 = 14. Check: 8, 14, 20 has a common difference of 6, confirming the result.", level: "both", topic: "Sequences and Series" },
    { question: "What is a set? Define union and intersection of two sets with an example.", modelAnswer: "A set is a well-defined collection of distinct objects called its elements. The union of A and B, written A union B, is the set of all elements belonging to A or B or both. The intersection, written A intersection B, is the set of elements common to both. Example: if A = {1,2,3,4} and B = {3,4,5}, then A union B = {1,2,3,4,5} and A intersection B = {3,4}.", level: "both", topic: "Sets" },
    { question: "Find the slope of the line passing through the points (1, 2) and (4, 11).", modelAnswer: "The slope m = (y2 - y1)/(x2 - x1) = (11 - 2)/(4 - 1) = 9/3 = 3. Since the slope is positive, the line rises from left to right.", level: "both", topic: "Coordinate Geometry" },
  ],
  longs: [
    { a: { question: "Solve the following system of linear equations by Cramer's rule: 2x + 3y = 13 and 4x - y = 5.", modelAnswer: "Write in matrix form. The coefficient determinant is D = |2 3; 4 -1| = (2)(-1) - (3)(4) = -2 - 12 = -14. Since D is not zero, a unique solution exists. Dx = |13 3; 5 -1| = (13)(-1) - (3)(5) = -13 - 15 = -28. Dy = |2 13; 4 5| = (2)(5) - (13)(4) = 10 - 52 = -42. By Cramer's rule, x = Dx/D = -28/-14 = 2 and y = Dy/D = -42/-14 = 3. Verification: 2(2) + 3(3) = 4 + 9 = 13 and 4(2) - 3 = 8 - 3 = 5. Both equations are satisfied, so the solution set is {(2, 3)}." }, b: { question: "Define the inverse of a 2x2 matrix and find the inverse of A = [[4, 7],[2, 6]].", modelAnswer: "The inverse of a non-singular square matrix A is the matrix A^-1 such that A A^-1 = A^-1 A = I. For A = [[a, b],[c, d]] the inverse is A^-1 = (1/|A|) [[d, -b],[-c, a]], where |A| = ad - bc, provided |A| is not zero. For A = [[4, 7],[2, 6]]: |A| = (4)(6) - (7)(2) = 24 - 14 = 10, which is non-zero, so the inverse exists. The adjoint is [[6, -7],[-2, 4]]. Therefore A^-1 = (1/10)[[6, -7],[-2, 4]] = [[0.6, -0.7],[-0.2, 0.4]]. Check: A A^-1 = [[1, 0],[0, 1]] = I." }, level: "both", topic: "Matrices" },
    { a: { question: "Derive the quadratic formula by completing the square and use it to solve 2x^2 - 7x + 3 = 0.", modelAnswer: "Consider ax^2 + bx + c = 0 with a not zero. Divide by a: x^2 + (b/a)x + c/a = 0, so x^2 + (b/a)x = -c/a. Add the square of half the coefficient of x, (b/2a)^2, to both sides: x^2 + (b/a)x + (b/2a)^2 = (b/2a)^2 - c/a. The left side is a perfect square: (x + b/2a)^2 = (b^2 - 4ac)/(4a^2). Taking the square root: x + b/2a = plus or minus sqrt(b^2 - 4ac)/(2a). Hence x = (-b plus or minus sqrt(b^2 - 4ac))/(2a). Applying to 2x^2 - 7x + 3 = 0 with a = 2, b = -7, c = 3: D = 49 - 24 = 25, sqrt(D) = 5. So x = (7 plus or minus 5)/4, giving x = 12/4 = 3 or x = 2/4 = 1/2. Solution set = {3, 1/2}." }, b: { question: "Find the sum of the roots and the product of the roots of a quadratic equation and verify for 3x^2 - 10x + 8 = 0.", modelAnswer: "If alpha and beta are the roots of ax^2 + bx + c = 0, then from the quadratic formula alpha = (-b + sqrt(D))/(2a) and beta = (-b - sqrt(D))/(2a). Adding: alpha + beta = -2b/(2a) = -b/a. Multiplying: alpha x beta = (b^2 - (b^2 - 4ac))/(4a^2) = 4ac/(4a^2) = c/a. So sum of roots = -b/a and product = c/a. For 3x^2 - 10x + 8 = 0: sum should be -(-10)/3 = 10/3 and product 8/3. Solving by factorisation: 3x^2 - 6x - 4x + 8 = 0 gives 3x(x-2) - 4(x-2) = 0, so (x-2)(3x-4) = 0 and the roots are x = 2 and x = 4/3. Check: sum = 2 + 4/3 = 10/3 and product = 2 x 4/3 = 8/3. Verified." }, level: "both", topic: "Quadratic Equations" },
    { a: { question: "Prove the theorem: a straight line drawn from the centre of a circle to bisect a chord (other than a diameter) is perpendicular to the chord.", modelAnswer: "GIVEN: A circle with centre O and a chord AB which is not a diameter. M is the midpoint of AB, so AM = MB. TO PROVE: OM is perpendicular to AB, i.e. angle OMA = angle OMB = 90 degrees. CONSTRUCTION: Join OA and OB. PROOF: In triangles OAM and OBM: OA = OB (radii of the same circle); AM = MB (given, M is the midpoint); OM = OM (common side). Therefore triangle OAM is congruent to triangle OBM by the S.S.S postulate. Hence angle OMA = angle OMB (corresponding angles of congruent triangles). But AMB is a straight line, so angle OMA + angle OMB = 180 degrees (supplementary adjacent angles). Since the two angles are equal and sum to 180 degrees, each must be 90 degrees. Therefore OM is perpendicular to AB. PROVED." }, b: { question: "Prove that any point on the right bisector of a line segment is equidistant from its end points.", modelAnswer: "GIVEN: A line segment AB, and a line LM which intersects AB at C such that LM is perpendicular to AB and AC = CB. P is any point on LM. TO PROVE: PA = PB. CONSTRUCTION: Join P to A and to B. PROOF: In triangles ACP and BCP: AC = BC (given, C is the midpoint of AB); angle PCA = angle PCB = 90 degrees (given, LM is perpendicular to AB); PC = PC (common side). Therefore triangle ACP is congruent to triangle BCP by the S.A.S postulate. Hence PA = PB (corresponding sides of congruent triangles). Since P was chosen arbitrarily on the right bisector, every point on the right bisector of AB is equidistant from A and B. PROVED." }, level: "matric", topic: "Geometry Theorems" },
    { a: { question: "Prove the limit that (sin theta)/theta approaches 1 as theta approaches 0, and hence differentiate sin x from first principles.", modelAnswer: "Consider a circle of unit radius with a small positive angle theta in radians. From the geometry of the sector, area of triangle OAB < area of sector OAB < area of triangle OAT, giving (1/2)sin theta < (1/2)theta < (1/2)tan theta. Dividing throughout by (1/2)sin theta: 1 < theta/sin theta < 1/cos theta. Taking reciprocals reverses the inequalities: cos theta < (sin theta)/theta < 1. As theta approaches 0, cos theta approaches 1, so by the sandwich (squeeze) theorem the limit of (sin theta)/theta is 1. Differentiating sin x from first principles: dy/dx = lim(h->0)[sin(x+h) - sin x]/h = lim[2 cos(x + h/2) sin(h/2)]/h = lim cos(x + h/2) x lim[sin(h/2)/(h/2)] = cos x x 1 = cos x." }, b: { question: "Differentiate y = x^2 sin x with respect to x and find dy/dx for y = (2x+1)/(x-3).", modelAnswer: "For y = x^2 sin x use the product rule, d(uv)/dx = u dv/dx + v du/dx, with u = x^2 and v = sin x. du/dx = 2x and dv/dx = cos x. Therefore dy/dx = x^2 cos x + 2x sin x = x(x cos x + 2 sin x). For y = (2x+1)/(x-3) use the quotient rule, d(u/v)/dx = (v du/dx - u dv/dx)/v^2, with u = 2x+1 and v = x-3. du/dx = 2 and dv/dx = 1. Therefore dy/dx = [(x-3)(2) - (2x+1)(1)]/(x-3)^2 = (2x - 6 - 2x - 1)/(x-3)^2 = -7/(x-3)^2." }, level: "inter", topic: "Differentiation" },
  ],
  numericals: [
    { question: "Solve the system of equations by Cramer's rule: 3x + 2y = 16 and x - y = 2.", formula: "x = Dx/D , y = Dy/D", solution: "GIVEN:\n3x + 2y = 16\nx - y = 2\n\nWORKING:\nD = |3  2 ; 1  -1| = (3)(-1) - (2)(1) = -3 - 2 = -5\nSince D is not zero, a unique solution exists.\n\nDx = |16  2 ; 2  -1| = (16)(-1) - (2)(2) = -16 - 4 = -20\nDy = |3  16 ; 1  2| = (3)(2) - (16)(1) = 6 - 16 = -10\n\nx = Dx/D = -20 / -5 = 4\ny = Dy/D = -10 / -5 = 2\n\nCHECK: 3(4) + 2(2) = 12 + 4 = 16 (correct); 4 - 2 = 2 (correct)\n\nRESULT: x = 4 and y = 2, solution set {(4, 2)}", marks: 5, level: "both", topic: "Matrices" },
    { question: "The 5th term of an A.P. is 17 and the 9th term is 33. Find the first term, the common difference and the sum of the first 15 terms.", formula: "an = a + (n-1)d ; Sn = (n/2)[2a + (n-1)d]", solution: "GIVEN:\na5 = 17, a9 = 33\n\nWORKING:\na + 4d = 17 ..... (i)\na + 8d = 33 ..... (ii)\n\nSubtracting (i) from (ii):\n4d = 16, so d = 4\n\nSubstituting in (i):\na + 4(4) = 17\na + 16 = 17, so a = 1\n\nS15 = (15/2)[2(1) + (15-1)(4)]\nS15 = (15/2)[2 + 56] = (15/2)(58) = 15 x 29 = 435\n\nRESULT: first term a = 1, common difference d = 4, and S15 = 435", marks: 5, level: "both", topic: "Sequences and Series" },
    { question: "Solve the quadratic equation 2x^2 - 7x + 3 = 0 using the quadratic formula.", formula: "x = (-b +/- sqrt(b^2 - 4ac)) / 2a", solution: "GIVEN:\n2x^2 - 7x + 3 = 0, so a = 2, b = -7, c = 3\n\nFORMULA: x = (-b +/- sqrt(b^2 - 4ac)) / 2a\n\nWORKING:\nDiscriminant D = b^2 - 4ac = (-7)^2 - 4(2)(3)\nD = 49 - 24 = 25\nsqrt(D) = 5 (a perfect square, so the roots are rational and distinct)\n\nx = (7 +/- 5) / (2 x 2) = (7 +/- 5)/4\n\nx1 = (7 + 5)/4 = 12/4 = 3\nx2 = (7 - 5)/4 = 2/4 = 1/2\n\nCHECK: sum of roots = 3 + 0.5 = 3.5 = -b/a = 7/2 (correct)\n\nRESULT: solution set = {3, 1/2}", marks: 5, level: "both", topic: "Quadratic Equations" },
    { question: "Find the derivative of y = (3x^2 + 5)(2x - 1) with respect to x.", formula: "Product rule: d(uv)/dx = u dv/dx + v du/dx", solution: "GIVEN:\ny = (3x^2 + 5)(2x - 1)\n\nLet u = 3x^2 + 5 and v = 2x - 1\n\nWORKING:\ndu/dx = 6x\ndv/dx = 2\n\nApplying the product rule:\ndy/dx = u(dv/dx) + v(du/dx)\ndy/dx = (3x^2 + 5)(2) + (2x - 1)(6x)\ndy/dx = 6x^2 + 10 + 12x^2 - 6x\ndy/dx = 18x^2 - 6x + 10\n\nVERIFICATION by expanding first: y = 6x^3 - 3x^2 + 10x - 5\ndy/dx = 18x^2 - 6x + 10 (same result)\n\nRESULT: dy/dx = 18x^2 - 6x + 10", marks: 5, level: "inter", topic: "Differentiation" },
    { question: "Evaluate the definite integral of (3x^2 + 2x) dx from x = 1 to x = 3.", formula: "integral of x^n dx = x^(n+1)/(n+1)", solution: "GIVEN:\nDefinite integral of (3x^2 + 2x) dx from 1 to 3\n\nWORKING:\nFirst find the antiderivative:\nintegral of 3x^2 dx = 3(x^3/3) = x^3\nintegral of 2x dx = 2(x^2/2) = x^2\nSo F(x) = x^3 + x^2\n\nApply the limits (upper minus lower):\nF(3) = (3)^3 + (3)^2 = 27 + 9 = 36\nF(1) = (1)^3 + (1)^2 = 1 + 1 = 2\n\nValue = F(3) - F(1) = 36 - 2 = 34\n\nRESULT: the value of the definite integral is 34 square units", marks: 5, level: "inter", topic: "Integration" },
    { question: "Find the equation of the straight line passing through the points A(2, 3) and B(5, 9).", formula: "Slope m = (y2-y1)/(x2-x1) ; y - y1 = m(x - x1)", solution: "GIVEN:\nA(2, 3) and B(5, 9)\n\nWORKING:\nStep 1 - find the slope:\nm = (y2 - y1)/(x2 - x1) = (9 - 3)/(5 - 2) = 6/3 = 2\n\nStep 2 - use the point-slope form with point A(2, 3):\ny - y1 = m(x - x1)\ny - 3 = 2(x - 2)\ny - 3 = 2x - 4\ny = 2x - 1\n\nIn general form: 2x - y - 1 = 0\n\nCHECK with B(5, 9): 2(5) - 9 - 1 = 10 - 10 = 0 (satisfied)\n\nRESULT: the equation of the line is 2x - y - 1 = 0", marks: 5, level: "both", topic: "Coordinate Geometry" },
    { question: "The sum of three consecutive terms of a G.P. is 26 and their product is 216. Find the terms.", formula: "Let the terms be a/r, a, ar", solution: "GIVEN:\nSum = 26, Product = 216\n\nWORKING:\nLet the three terms be a/r, a, ar\n\nProduct: (a/r)(a)(ar) = a^3 = 216\nTherefore a = 6\n\nSum: a/r + a + ar = 26\n6/r + 6 + 6r = 26\n6/r + 6r = 20\nMultiplying throughout by r: 6 + 6r^2 = 20r\n6r^2 - 20r + 6 = 0\nDividing by 2: 3r^2 - 10r + 3 = 0\n(3r - 1)(r - 3) = 0\nr = 1/3 or r = 3\n\nIf r = 3: terms are 6/3, 6, 6x3 = 2, 6, 18\nIf r = 1/3: terms are 18, 6, 2 (same set reversed)\n\nRESULT: the three terms are 2, 6 and 18", marks: 5, level: "both", topic: "Sequences and Series" },
    { question: "Find the value of x if log(x) + log(4) = log(20).", formula: "log m + log n = log(mn)", solution: "GIVEN:\nlog x + log 4 = log 20\n\nWORKING:\nUsing the product law of logarithms on the left side:\nlog(4x) = log 20\n\nSince the logarithms are equal and the log function is one-to-one,\nthe arguments must be equal:\n4x = 20\nx = 20/4\nx = 5\n\nCHECK: log 5 + log 4 = log 20 (since 5 x 4 = 20) - correct\nAlso x = 5 > 0, so the logarithm is defined.\n\nRESULT: x = 5", marks: 5, level: "both", topic: "Logarithms" },
  ],
};

export const EXAM_BANK: Record<string, ExamSubjectBank> = {
  physics,
  chemistry,
  math,
  mathematics: math,
};

export default EXAM_BANK;
