/**
 * Authentic BISE-style question bank.
 *
 * Purpose: the original generator built its pools with `for (i=1..25)` loops that
 * cycled through only 1-3 hardcoded strings, so a 15-MCQ English paper contained
 * the SAME question 15 times. This bank supplies genuinely distinct items so a
 * full paper reads like a real board paper.
 *
 * Every entry is written to Pakistani board conventions (SSC / HSSC).
 */

export interface BankMCQ {
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export interface BankShort {
  question: string;
  modelAnswer: string;
}

export interface BankLong {
  a: { question: string; modelAnswer: string };
  b: { question: string; modelAnswer: string };
}

export interface SubjectBank {
  mcqs: BankMCQ[];
  shorts: BankShort[];
  longs: BankLong[];
}

/* ===================== BIOLOGY ===================== */
const biology: SubjectBank = {
  mcqs: [
    { question: "The net gain of ATP molecules during glycolysis of one glucose molecule is:", options: ["2", "4", "36", "38"], correctIndex: 0, explanation: "Glycolysis produces 4 ATP but consumes 2, giving a net gain of 2 ATP." },
    { question: "The oxygen-carrying pigment present in human red blood cells is:", options: ["Haemoglobin", "Chlorophyll", "Haemocyanin", "Melanin"], correctIndex: 0, explanation: "Haemoglobin binds oxygen to form oxyhaemoglobin for transport." },
    { question: "Which plant hormone is chiefly responsible for apical dominance?", options: ["Auxin", "Gibberellin", "Ethylene", "Abscisic acid"], correctIndex: 0, explanation: "Auxin produced at the shoot apex suppresses growth of lateral buds." },
    { question: "The functional unit of the kidney is called the:", options: ["Nephron", "Neuron", "Alveolus", "Villus"], correctIndex: 0, explanation: "Each kidney contains about one million nephrons that filter blood." },
    { question: "Photosynthesis light reactions occur in which part of the chloroplast?", options: ["Thylakoid membrane", "Stroma", "Outer membrane", "Intermembrane space"], correctIndex: 0, explanation: "Photosystems I and II are embedded in the thylakoid membrane." },
    { question: "Which blood group is called the universal donor?", options: ["O negative", "AB positive", "A positive", "B negative"], correctIndex: 0, explanation: "O negative has no A, B or Rh antigens, so it is not attacked by recipient antibodies." },
    { question: "The site of protein synthesis in a cell is the:", options: ["Ribosome", "Lysosome", "Golgi body", "Centriole"], correctIndex: 0, explanation: "Ribosomes translate mRNA into polypeptide chains." },
    { question: "Deficiency of which vitamin causes rickets in children?", options: ["Vitamin D", "Vitamin A", "Vitamin C", "Vitamin K"], correctIndex: 0, explanation: "Vitamin D is required for calcium absorption and bone calcification." },
    { question: "In a dihybrid cross of heterozygous parents, the phenotypic ratio obtained is:", options: ["9:3:3:1", "3:1", "1:2:1", "1:1"], correctIndex: 0, explanation: "Mendel's law of independent assortment gives 9:3:3:1 in the F2 generation." },
    { question: "Which enzyme begins the digestion of starch in the mouth?", options: ["Salivary amylase", "Pepsin", "Trypsin", "Lipase"], correctIndex: 0, explanation: "Salivary amylase (ptyalin) hydrolyses starch into maltose." },
    { question: "The double helix model of DNA was proposed by:", options: ["Watson and Crick", "Mendel and Morgan", "Darwin and Wallace", "Hooke and Schleiden"], correctIndex: 0, explanation: "Watson and Crick proposed the double helix in 1953." },
    { question: "Which chamber of the human heart pumps blood into the aorta?", options: ["Left ventricle", "Right ventricle", "Left atrium", "Right atrium"], correctIndex: 0, explanation: "The thick-walled left ventricle pumps oxygenated blood into the aorta." },
    { question: "Bacteria are best described as:", options: ["Prokaryotes", "Eukaryotes", "Viruses", "Fungi"], correctIndex: 0, explanation: "Bacteria lack a true nucleus and membrane-bound organelles." },
    { question: "The exchange of gases in the lungs takes place in the:", options: ["Alveoli", "Bronchi", "Trachea", "Pleura"], correctIndex: 0, explanation: "Thin-walled alveoli provide a large surface area for gaseous exchange." },
    { question: "Which of the following is a nitrogenous waste excreted by the human kidney?", options: ["Urea", "Glucose", "Albumin", "Fibrinogen"], correctIndex: 0, explanation: "Urea is formed in the liver from ammonia and excreted in urine." },
    { question: "Meiosis results in the production of:", options: ["Four haploid cells", "Two diploid cells", "Two haploid cells", "Four diploid cells"], correctIndex: 0, explanation: "Meiosis halves the chromosome number and yields four haploid gametes." },
    { question: "The green pigment that traps light energy in plants is:", options: ["Chlorophyll", "Carotene", "Xanthophyll", "Anthocyanin"], correctIndex: 0, explanation: "Chlorophyll a and b absorb mainly red and blue light." },
    { question: "Insulin is secreted by which cells of the pancreas?", options: ["Beta cells of Islets of Langerhans", "Alpha cells", "Acinar cells", "Delta cells"], correctIndex: 0, explanation: "Beta cells secrete insulin, which lowers blood glucose level." },
    { question: "The basic structural and functional unit of life is the:", options: ["Cell", "Tissue", "Organ", "Molecule"], correctIndex: 0, explanation: "The cell theory states that all organisms are composed of cells." },
    { question: "Transpiration in plants mainly occurs through:", options: ["Stomata", "Xylem", "Phloem", "Root hairs"], correctIndex: 0, explanation: "Most water vapour is lost through stomatal pores on the leaf surface." },
  ],
  shorts: [
    { question: "Define homeostasis and give one example from the human body.", modelAnswer: "Homeostasis is the maintenance of a stable internal environment despite external changes. Example: the kidneys regulate water and salt balance (osmoregulation) to keep blood concentration constant." },
    { question: "Differentiate between arteries and veins on the basis of structure and function.", modelAnswer: "Arteries have thick muscular elastic walls, narrow lumen, no valves, and carry blood away from the heart at high pressure. Veins have thin walls, wide lumen, contain valves to prevent backflow, and carry blood towards the heart at low pressure." },
    { question: "What is the role of stomata in a leaf?", modelAnswer: "Stomata are tiny pores bounded by guard cells. They allow the exchange of CO2 and O2 during photosynthesis and respiration, and permit loss of water vapour during transpiration. Guard cells open and close them to control water loss." },
    { question: "Write down the overall balanced equation of photosynthesis.", modelAnswer: "6CO2 + 12H2O --(light energy, chlorophyll)--> C6H12O6 + 6O2 + 6H2O. Carbon dioxide and water in the presence of light and chlorophyll produce glucose, oxygen and water." },
    { question: "Name any three components of blood and state one function of each.", modelAnswer: "(i) Red blood cells - transport oxygen using haemoglobin. (ii) White blood cells - provide defence against disease by phagocytosis and antibody production. (iii) Platelets - help in blood clotting. Plasma transports nutrients, hormones and wastes." },
    { question: "What is meant by a balanced diet?", modelAnswer: "A balanced diet contains all the nutrients (carbohydrates, proteins, fats, vitamins, minerals, water and roughage) in correct proportion and adequate amount according to age, sex and activity of a person." },
    { question: "Distinguish between mitosis and meiosis.", modelAnswer: "Mitosis occurs in somatic cells, involves one division, produces two genetically identical diploid cells and is used for growth and repair. Meiosis occurs in reproductive cells, involves two divisions, produces four genetically different haploid cells and forms gametes." },
    { question: "Explain the function of the nephron.", modelAnswer: "The nephron filters blood in three steps: ultrafiltration at the glomerulus (water, salts, urea, glucose pass into Bowman's capsule), selective reabsorption in the tubules (glucose, useful salts and water return to blood), and tubular secretion of extra ions, finally forming urine." },
    { question: "What are enzymes? Write two of their properties.", modelAnswer: "Enzymes are biological catalysts, mostly proteins, that speed up biochemical reactions without being consumed. Properties: (i) they are highly specific for their substrate (lock and key model); (ii) they work best at a particular optimum temperature and pH and are denatured beyond it." },
    { question: "Define pollination and give its two types.", modelAnswer: "Pollination is the transfer of pollen grains from the anther to the stigma. Types: (i) Self-pollination - transfer within the same flower or another flower on the same plant; (ii) Cross-pollination - transfer to a flower of a different plant of the same species, usually by wind, water or insects." },
    { question: "What is the importance of the nitrogen cycle?", modelAnswer: "The nitrogen cycle converts atmospheric nitrogen into usable nitrates by nitrogen fixation, nitrification and decomposition, and returns nitrogen to the air by denitrification. It maintains soil fertility and supplies nitrogen for the synthesis of proteins and nucleic acids." },
    { question: "Describe the structure of a chromosome.", modelAnswer: "A chromosome consists of a long DNA molecule coiled around histone proteins forming chromatin. During cell division it condenses into two identical sister chromatids joined at a centromere. The tips are called telomeres, which protect the chromosome ends." },
    { question: "State two differences between plant and animal cells.", modelAnswer: "(i) A plant cell has a rigid cellulose cell wall; an animal cell has only a cell membrane. (ii) A plant cell contains chloroplasts and a large central vacuole; animal cells lack chloroplasts and have small or no vacuoles. Animal cells contain centrioles." },
    { question: "What causes diabetes mellitus?", modelAnswer: "Diabetes mellitus is caused by insufficient secretion of insulin by the beta cells of the Islets of Langerhans, or by the failure of body cells to respond to insulin. As a result glucose is not absorbed by cells, blood glucose rises and glucose appears in urine." },
    { question: "Define ecosystem and name its two main components.", modelAnswer: "An ecosystem is a self-supporting unit in which living organisms interact with one another and with their physical environment. Its components are: (i) biotic - producers, consumers and decomposers; (ii) abiotic - light, temperature, water, air and soil." },
    { question: "What is meant by antibiotic resistance?", modelAnswer: "Antibiotic resistance is the ability of bacteria to survive and multiply in the presence of an antibiotic that formerly killed them. It develops by mutation and natural selection, and is accelerated by incomplete courses and unnecessary use of antibiotics." },
    { question: "Explain the term 'double circulation' in humans.", modelAnswer: "In double circulation blood passes twice through the heart in one complete round. Pulmonary circulation carries deoxygenated blood from the right ventricle to the lungs and back to the left atrium. Systemic circulation carries oxygenated blood from the left ventricle to the body and back to the right atrium." },
    { question: "Write two functions of the liver.", modelAnswer: "(i) It converts excess glucose into glycogen and stores it, regulating blood glucose. (ii) It converts toxic ammonia into less harmful urea (deamination) and detoxifies drugs and alcohol. It also secretes bile for the emulsification of fats." },
    { question: "What is a food chain? Give one example.", modelAnswer: "A food chain is a linear sequence showing the transfer of food energy from one organism to the next. Example: Grass (producer) -> Grasshopper (primary consumer) -> Frog (secondary consumer) -> Snake (tertiary consumer) -> Eagle (top consumer)." },
    { question: "Define osmosis.", modelAnswer: "Osmosis is the movement of water molecules from a region of their higher concentration (dilute solution) to a region of their lower concentration (concentrated solution) through a selectively permeable membrane, until equilibrium is reached." },
  ],
  longs: [
    { a: { question: "Describe the light-dependent reactions of photosynthesis with the help of a diagram.", modelAnswer: "Light is absorbed by photosystem II; water is split by photolysis (2H2O -> 4H+ + 4e- + O2). Electrons pass along the electron transport chain releasing energy to pump protons into the thylakoid space. Photosystem I re-energises electrons which reduce NADP+ to NADPH. The proton gradient drives ATP synthase to make ATP (photophosphorylation). Products ATP and NADPH are used in the Calvin cycle; oxygen is released as a by-product." }, b: { question: "State Mendel's law of independent assortment and illustrate it with a dihybrid cross.", modelAnswer: "The law states that the alleles of two different genes segregate into gametes independently of each other. Cross RrYy x RrYy: gametes RY, Ry, rY, ry from each parent. The 4x4 Punnett square gives 16 combinations with the phenotypic ratio 9 round-yellow : 3 round-green : 3 wrinkled-yellow : 1 wrinkled-green, i.e. 9:3:3:1." } },
    { a: { question: "Explain the structure and working of the human heart.", modelAnswer: "The heart is a four-chambered muscular organ with two atria and two ventricles separated by a septum. Deoxygenated blood from the body enters the right atrium via the venae cavae, passes the tricuspid valve into the right ventricle, and is pumped through the pulmonary artery to the lungs. Oxygenated blood returns by pulmonary veins into the left atrium, passes the bicuspid valve into the thick-walled left ventricle, and is pumped into the aorta. Semilunar valves prevent backflow. The cardiac cycle consists of atrial systole, ventricular systole and diastole, initiated by the SA node (pacemaker)." }, b: { question: "Describe the mechanism of breathing in humans.", modelAnswer: "During inspiration the external intercostal muscles contract raising the ribs upward and outward, and the diaphragm contracts and flattens. Thoracic volume increases, pressure falls below atmospheric pressure and air rushes into the lungs. During expiration these muscles relax, the ribs move down and in, the diaphragm becomes dome-shaped, thoracic volume decreases, pressure rises and air is expelled." } },
    { a: { question: "Describe the structure of a nephron and explain urine formation.", modelAnswer: "A nephron consists of the Bowman's capsule enclosing the glomerulus, the proximal convoluted tubule, loop of Henle, distal convoluted tubule and collecting duct. Urine formation: (1) Ultrafiltration - high blood pressure in the glomerulus forces water, salts, glucose, amino acids and urea into the capsule forming glomerular filtrate; blood cells and proteins are retained. (2) Selective reabsorption - all glucose and amino acids, most water and needed salts are reabsorbed in the proximal tubule and loop of Henle. (3) Tubular secretion - extra H+, K+ and drugs are secreted into the tubule. The remaining fluid is urine, which passes to the bladder." }, b: { question: "What is osmoregulation? How do the kidneys maintain water balance?", modelAnswer: "Osmoregulation is the control of the water and salt content of body fluids. When blood becomes concentrated, the hypothalamus stimulates the pituitary to release ADH, which makes the collecting ducts more permeable so more water is reabsorbed and concentrated urine is produced. When blood is dilute, ADH secretion falls, less water is reabsorbed and dilute urine is produced in larger volume." } },
    { a: { question: "Explain the process of digestion of food in the human alimentary canal.", modelAnswer: "In the mouth, teeth chew food and salivary amylase converts starch to maltose. The bolus passes down the oesophagus by peristalsis. In the stomach, gastric juice supplies HCl (kills bacteria, provides acidic pH) and pepsin (proteins to polypeptides). In the duodenum, bile emulsifies fats while pancreatic juice supplies amylase, trypsin and lipase. In the ileum, intestinal juice completes digestion: maltase, peptidase and lipase produce glucose, amino acids, fatty acids and glycerol, which are absorbed by villi. Water is absorbed in the colon and faeces are egested through the anus." }, b: { question: "Write a note on the structure of a villus and its role in absorption.", modelAnswer: "A villus is a finger-like projection of the ileum wall, about 1 mm long. It has a single layer of epithelium with microvilli, a network of blood capillaries and a central lacteal. Adaptations: very large surface area, thin wall (one cell thick) for a short diffusion path, rich blood supply maintaining a concentration gradient. Glucose and amino acids are absorbed into the capillaries; fatty acids and glycerol enter the lacteal as lymph." } },
    { a: { question: "Discuss the causes, symptoms, prevention and treatment of hepatitis in Pakistan.", modelAnswer: "Hepatitis is inflammation of the liver caused by viruses A, B, C, D and E. Hepatitis A and E spread through contaminated food and water; B, C and D through infected blood, used syringes, unsterilised instruments and from mother to child. Symptoms: fever, loss of appetite, nausea, dark urine, jaundice (yellowing of skin and eyes), pain in the upper right abdomen. Prevention: vaccination against A and B, use of disposable syringes, screening of blood before transfusion, boiled or filtered drinking water, personal hygiene. Treatment: rest, a proper diet and antiviral drugs prescribed by a doctor." }, b: { question: "Describe the harmful effects of tobacco smoking on the human respiratory system.", modelAnswer: "Tobacco smoke contains nicotine, tar and carbon monoxide. Nicotine is addictive and raises heart rate and blood pressure. Tar paralyses and destroys the cilia lining the airways, so mucus accumulates causing smoker's cough and chronic bronchitis. It also contains carcinogens that cause lung cancer. Destruction of alveolar walls reduces surface area causing emphysema and shortness of breath. Carbon monoxide binds irreversibly with haemoglobin forming carboxyhaemoglobin, reducing oxygen transport." } },
    { a: { question: "Explain the structure of DNA and describe its replication.", modelAnswer: "DNA is a double helix of two antiparallel polynucleotide strands. Each nucleotide has deoxyribose sugar, a phosphate group and a nitrogenous base (adenine, thymine, guanine, cytosine). Strands are joined by hydrogen bonds: A=T (two bonds) and G=C (three bonds). Replication is semi-conservative: helicase unwinds the helix and breaks hydrogen bonds; each strand acts as a template; DNA polymerase adds complementary free nucleotides in the 5'->3' direction; ligase joins the fragments. Two identical daughter molecules are formed, each with one parent and one new strand." }, b: { question: "What is genetic engineering? State two of its benefits.", modelAnswer: "Genetic engineering is the deliberate transfer of a desired gene from one organism into the DNA of another to give it a new characteristic. Restriction enzymes cut the gene and the plasmid vector, and ligase joins them to make recombinant DNA, which is inserted into a host such as a bacterium. Benefits: (i) production of human insulin, growth hormone and vaccines cheaply and in large amounts; (ii) development of crops resistant to pests, disease and drought, improving yield and food security." } },
    { a: { question: "Describe the different types of ecological relationships between organisms with examples.", modelAnswer: "(i) Mutualism - both partners benefit, e.g. Rhizobium bacteria in the root nodules of leguminous plants fix nitrogen and receive shelter and food. (ii) Commensalism - one benefits, the other is unaffected, e.g. epiphytic orchids growing on tree branches. (iii) Parasitism - the parasite benefits and the host is harmed, e.g. Plasmodium in humans, Cuscuta on plants. (iv) Predation - the predator kills and eats the prey, e.g. a lion hunting a deer. (v) Competition - organisms compete for the same limited resource, e.g. weeds and crops competing for light and minerals." }, b: { question: "Explain the flow of energy in an ecosystem with the help of a pyramid.", modelAnswer: "Energy enters an ecosystem as sunlight, which producers convert into chemical energy by photosynthesis. It flows unidirectionally through trophic levels: producers -> primary consumers -> secondary consumers -> tertiary consumers, with decomposers acting at every level. Only about 10% of the energy is transferred to the next level (the ten percent law); the rest is lost as heat in respiration and in undigested matter. Hence the pyramid of energy is always upright and the number of trophic levels is limited to four or five." } },
    { a: { question: "Describe the structure of the human eye and explain how an image is formed.", modelAnswer: "The eye has three layers: the protective sclera with the transparent cornea in front, the vascular choroid with the iris and pupil, and the light-sensitive retina containing rods (dim light, black and white) and cones (bright light, colour). The biconvex lens is held by suspensory ligaments and ciliary muscles. Light passes through the cornea, aqueous humour, pupil, lens and vitreous humour and is refracted to form a real, inverted, diminished image on the retina at the yellow spot. Rods and cones generate nerve impulses carried by the optic nerve to the brain, which interprets the image the right way up. Accommodation is achieved by the ciliary muscles altering lens thickness." }, b: { question: "What are the common defects of vision? How are they corrected?", modelAnswer: "(i) Myopia (short-sightedness) - the eyeball is too long or the lens too convex, so the image forms in front of the retina and distant objects appear blurred; corrected by a concave (diverging) lens. (ii) Hypermetropia (long-sightedness) - the eyeball is too short or the lens too weak, so the image forms behind the retina and near objects are blurred; corrected by a convex (converging) lens. (iii) Astigmatism - uneven curvature of the cornea; corrected by a cylindrical lens. (iv) Presbyopia - loss of lens elasticity with age; corrected by bifocal lenses." } },
  ],
};

/* ===================== COMPUTER SCIENCE ===================== */
const cs: SubjectBank = {
  mcqs: [
    { question: "Which normal form removes transitive dependency from a relation?", options: ["Third Normal Form (3NF)", "First Normal Form (1NF)", "Second Normal Form (2NF)", "Boyce-Codd Normal Form"], correctIndex: 0, explanation: "3NF requires the relation to be in 2NF and have no transitive dependency on the primary key." },
    { question: "Which layer of the OSI model is responsible for framing data packets?", options: ["Data Link Layer", "Physical Layer", "Network Layer", "Transport Layer"], correctIndex: 0, explanation: "The Data Link Layer organises bits into frames and performs error detection." },
    { question: "The binary equivalent of the decimal number 25 is:", options: ["11001", "10011", "11010", "10101"], correctIndex: 0, explanation: "25 = 16 + 8 + 1 = 11001 in binary." },
    { question: "Which of the following is a non-volatile memory?", options: ["ROM", "RAM", "Cache", "Register"], correctIndex: 0, explanation: "ROM retains its contents when the power is switched off." },
    { question: "In C, which operator is used to access a member of a structure through a pointer?", options: ["->", ".", "&", "*"], correctIndex: 0, explanation: "The arrow operator dereferences the pointer and accesses the member." },
    { question: "A primary key in a database table:", options: ["Uniquely identifies each record and cannot be null", "May contain duplicate values", "Can be null", "Is always a foreign key"], correctIndex: 0, explanation: "A primary key must be unique and NOT NULL." },
    { question: "Which SQL statement is used to remove all rows from a table but keep its structure?", options: ["TRUNCATE", "DROP", "DELETE TABLE", "ALTER"], correctIndex: 0, explanation: "TRUNCATE removes all rows quickly while retaining the table definition." },
    { question: "The number of bits in one byte is:", options: ["8", "4", "16", "32"], correctIndex: 0, explanation: "One byte consists of 8 bits." },
    { question: "Which topology connects every node to a single central device?", options: ["Star", "Bus", "Ring", "Mesh"], correctIndex: 0, explanation: "In a star topology all nodes connect to a central hub or switch." },
    { question: "A compiler differs from an interpreter because it:", options: ["Translates the whole program at once", "Executes line by line", "Does not produce object code", "Cannot detect syntax errors"], correctIndex: 0, explanation: "A compiler translates the entire source program into object code before execution." },
    { question: "Which data structure works on the Last In First Out (LIFO) principle?", options: ["Stack", "Queue", "Array", "Linked list"], correctIndex: 0, explanation: "In a stack the last element pushed is the first popped." },
    { question: "The protocol used to transfer web pages on the Internet is:", options: ["HTTP", "FTP", "SMTP", "POP3"], correctIndex: 0, explanation: "HyperText Transfer Protocol transfers hypertext documents." },
    { question: "In a relational database, a row is also called a:", options: ["Tuple", "Attribute", "Domain", "Schema"], correctIndex: 0, explanation: "A row of a relation is called a tuple or record." },
    { question: "Which loop is guaranteed to execute at least once?", options: ["do-while", "while", "for", "nested for"], correctIndex: 0, explanation: "The do-while loop tests its condition after executing the body." },
    { question: "An IP address in IPv4 consists of how many bits?", options: ["32", "16", "64", "128"], correctIndex: 0, explanation: "IPv4 uses a 32-bit address written as four octets." },
    { question: "Which device connects two networks and forwards packets between them?", options: ["Router", "Repeater", "Hub", "Modem"], correctIndex: 0, explanation: "A router works at the network layer and routes packets between networks." },
    { question: "The process of finding and removing errors from a program is called:", options: ["Debugging", "Compiling", "Linking", "Executing"], correctIndex: 0, explanation: "Debugging locates and corrects logical and runtime errors." },
    { question: "Which of the following is an example of system software?", options: ["Operating system", "MS Word", "Spreadsheet", "Web browser"], correctIndex: 0, explanation: "An operating system manages hardware and provides a platform for application software." },
    { question: "In object-oriented programming, wrapping data and functions into a single unit is called:", options: ["Encapsulation", "Inheritance", "Polymorphism", "Abstraction"], correctIndex: 0, explanation: "Encapsulation binds data members and member functions inside a class." },
    { question: "The hexadecimal equivalent of binary 1111 1010 is:", options: ["FA", "AF", "FB", "EA"], correctIndex: 0, explanation: "1111 = F and 1010 = A, giving FA." },
  ],
  shorts: [
    { question: "Define an algorithm and state two of its properties.", modelAnswer: "An algorithm is a finite, ordered set of unambiguous steps to solve a particular problem. Properties: (i) it must be finite and terminate after a limited number of steps; (ii) each step must be precise and unambiguous, with well-defined input and output." },
    { question: "Differentiate between RAM and ROM.", modelAnswer: "RAM is volatile read/write memory that stores programs and data currently in use and loses its contents when power is off. ROM is non-volatile read-only memory that permanently stores the bootstrap program and firmware, and retains data when power is off." },
    { question: "What is a primary key? Why can it not be null?", modelAnswer: "A primary key is an attribute or set of attributes that uniquely identifies each record in a table. It cannot be null because a null value cannot uniquely identify a row, which would violate entity integrity and allow duplicate or unidentifiable records." },
    { question: "Differentiate between an IP address and a MAC address.", modelAnswer: "An IP address is a 32-bit (IPv4) logical address assigned by software at the network layer and can change when the network changes. A MAC address is a 48-bit physical address permanently burnt into the NIC by the manufacturer and works at the data link layer." },
    { question: "What is the difference between a compiler and an interpreter?", modelAnswer: "A compiler translates the entire source program into object code in one go, reports all errors together, and execution is fast because translation happens once. An interpreter translates and executes the program line by line, stops at the first error, and execution is slower as translation repeats each run." },
    { question: "Define a loop. Name its two types.", modelAnswer: "A loop is a control structure that repeats a block of statements while a condition remains true. Types: (i) counter-controlled loop (for loop) where the number of iterations is known; (ii) condition-controlled loop (while and do-while) where iteration continues until a condition becomes false." },
    { question: "What is a network topology? Name any three types.", modelAnswer: "Network topology is the physical or logical arrangement of nodes and links in a network. Types: bus (all nodes on a single backbone cable), star (all nodes connected to a central hub or switch), ring (each node connected to two neighbours forming a closed loop), and mesh." },
    { question: "Explain the difference between a stack and a queue.", modelAnswer: "A stack follows Last In First Out (LIFO): insertion (push) and deletion (pop) occur at the same end called the top. A queue follows First In First Out (FIFO): insertion (enqueue) occurs at the rear and deletion (dequeue) at the front." },
    { question: "What is meant by a variable and a constant in programming?", modelAnswer: "A variable is a named memory location whose value can change during program execution, e.g. int marks = 50;. A constant is a named memory location whose value is fixed once defined and cannot be altered, e.g. const float PI = 3.1416;." },
    { question: "Define a database and a DBMS.", modelAnswer: "A database is an organised collection of related data stored so that it can be easily accessed, managed and updated. A DBMS (Database Management System) is software such as MySQL or Oracle that allows users to create, store, retrieve, update and control access to the database." },
    { question: "What is the function of an operating system?", modelAnswer: "An operating system manages hardware and software resources. Its functions include process management, memory management, file management, device (I/O) management, security and access control, and providing a user interface between the user and the machine." },
    { question: "Differentiate between analog and digital signals.", modelAnswer: "An analog signal is continuous and varies smoothly over time with infinite possible values, e.g. a human voice. A digital signal is discrete and takes only fixed values (0 and 1), is less affected by noise, and can be transmitted and stored more reliably." },
    { question: "What is an array? How is it different from a simple variable?", modelAnswer: "An array is a collection of elements of the same data type stored in contiguous memory locations and accessed by a common name with an index. A simple variable stores only one value, whereas an array stores many values, e.g. int marks[10]; stores ten integers." },
    { question: "Explain the term 'computer virus' and give two prevention methods.", modelAnswer: "A computer virus is a malicious program that attaches itself to files, replicates and damages data or disturbs normal operation. Prevention: (i) install and regularly update reliable antivirus software; (ii) avoid opening unknown email attachments and scan external storage media before use; take regular backups." },
    { question: "What is a foreign key? Give an example.", modelAnswer: "A foreign key is an attribute in one table that refers to the primary key of another table, creating a link between them and enforcing referential integrity. Example: in a Result table, Student_ID is a foreign key referencing the primary key Student_ID of the Student table." },
    { question: "Distinguish between LAN and WAN.", modelAnswer: "A LAN covers a small geographical area such as a building or campus, has a high data transfer rate, low error rate and is usually privately owned. A WAN spans cities or countries, uses public telecommunication links, has a lower data rate and a higher error rate; the Internet is the largest WAN." },
    { question: "Define encapsulation in object-oriented programming.", modelAnswer: "Encapsulation is the wrapping of data members and the member functions that operate on them into a single unit called a class. It hides internal details by making data private and exposing only public methods, which protects data from accidental modification (data hiding)." },
    { question: "What is the purpose of the SELECT statement in SQL? Write its general syntax.", modelAnswer: "The SELECT statement retrieves data from one or more tables of a database. Syntax: SELECT column1, column2 FROM table_name WHERE condition ORDER BY column; For example: SELECT name, marks FROM Student WHERE marks > 60 ORDER BY marks DESC;" },
    { question: "Convert the decimal number 45 into binary, showing the steps.", modelAnswer: "Divide repeatedly by 2 and record remainders: 45/2 = 22 r 1; 22/2 = 11 r 0; 11/2 = 5 r 1; 5/2 = 2 r 1; 2/2 = 1 r 0; 1/2 = 0 r 1. Reading the remainders upward gives 101101. Check: 32 + 8 + 4 + 1 = 45." },
    { question: "What is a flowchart? Name any three of its symbols.", modelAnswer: "A flowchart is a pictorial representation of an algorithm using standard symbols connected by arrows showing the flow of control. Symbols: oval (start/stop terminal), parallelogram (input/output), rectangle (process), diamond (decision) and arrows (flow lines)." },
  ],
  longs: [
    { a: { question: "Explain the seven layers of the OSI reference model with the function of each layer.", modelAnswer: "(1) Physical - transmits raw bits over the medium, defines cables, voltages and connectors. (2) Data Link - organises bits into frames, provides physical (MAC) addressing, error detection and flow control. (3) Network - performs logical addressing (IP) and routing of packets between networks. (4) Transport - provides end-to-end delivery, segmentation, reassembly, error recovery and flow control (TCP/UDP). (5) Session - establishes, manages and terminates sessions between applications. (6) Presentation - handles translation, encryption/decryption and compression of data. (7) Application - provides network services to the user such as HTTP, FTP and SMTP." }, b: { question: "Differentiate between the OSI model and the TCP/IP model.", modelAnswer: "OSI has seven layers while TCP/IP has four (Network Access, Internet, Transport, Application). OSI is a theoretical reference model developed by ISO; TCP/IP is a practical model on which the Internet actually runs. In OSI the session and presentation layers are separate, whereas TCP/IP merges them into the application layer. OSI clearly separates services, interfaces and protocols; TCP/IP does not." } },
    { a: { question: "What is database normalisation? Explain 1NF, 2NF and 3NF with examples.", modelAnswer: "Normalisation is the step-by-step decomposition of tables to remove redundancy and insertion, deletion and update anomalies. 1NF: every attribute must be atomic with no repeating groups; e.g. splitting a 'Phone' column holding two numbers into separate rows. 2NF: the relation must be in 1NF and every non-key attribute must be fully functionally dependent on the whole primary key, removing partial dependency in composite keys. 3NF: the relation must be in 2NF and no non-key attribute may depend on another non-key attribute; e.g. if Student(ID, Name, City, City_Code) has City_Code depending on City, split it into a separate City table." }, b: { question: "Write SQL statements to create a Student table and insert one record into it.", modelAnswer: "CREATE TABLE Student ( Student_ID INT PRIMARY KEY, Name VARCHAR(50) NOT NULL, Class VARCHAR(10), Marks INT ); INSERT INTO Student (Student_ID, Name, Class, Marks) VALUES (101, 'Ali Raza', '10th', 480); To view: SELECT * FROM Student WHERE Marks > 400; To modify: UPDATE Student SET Marks = 485 WHERE Student_ID = 101;" } },
    { a: { question: "Explain the different types of computer memory with a memory hierarchy diagram.", modelAnswer: "Memory is arranged in a hierarchy of decreasing speed and cost but increasing capacity. (1) Registers - fastest, inside the CPU, hold operands being processed. (2) Cache - very fast SRAM between CPU and main memory, stores frequently used data (L1, L2, L3). (3) Main memory (RAM) - volatile, holds programs and data currently in execution; ROM stores permanent firmware. (4) Secondary storage - hard disk, SSD, non-volatile, large capacity, slower. (5) Tertiary/backup - magnetic tape, optical discs, cheapest and slowest, used for archives." }, b: { question: "Differentiate between primary and secondary memory.", modelAnswer: "Primary memory is directly accessible by the CPU, is fast, has small capacity and is mostly volatile (RAM); it holds data currently being processed. Secondary memory is not directly accessible by the CPU, is slower, has very large capacity and is non-volatile (hard disk, USB, DVD); it permanently stores programs and data. Primary memory is costly per byte while secondary memory is cheap per byte." } },
    { a: { question: "Explain the basic control structures of programming with the help of flowcharts.", modelAnswer: "(1) Sequence - statements execute one after another in the order written; represented by rectangles joined by arrows. (2) Selection (decision) - a condition is tested and one of the alternative paths is taken; represented by a diamond, implemented by if, if-else and switch statements. (3) Repetition (loop) - a block repeats while a condition is true; represented by a decision symbol with a flow line looping back, implemented by for, while and do-while. Any program, however complex, can be written using only these three structures (structured programming theorem)." }, b: { question: "Write an algorithm and its equivalent C code to find the largest of three numbers.", modelAnswer: "Algorithm: Step 1 Start. Step 2 Input a, b, c. Step 3 If a > b and a > c then largest = a. Step 4 Else if b > c then largest = b. Step 5 Else largest = c. Step 6 Print largest. Step 7 Stop. Code: #include <stdio.h> int main(){ int a,b,c,max; scanf(\"%d %d %d\",&a,&b,&c); if(a>b && a>c) max=a; else if(b>c) max=b; else max=c; printf(\"Largest = %d\", max); return 0; }" } },
    { a: { question: "What is network security? Describe any four common threats and their countermeasures.", modelAnswer: "Network security is the set of policies and technologies that protect data and resources from unauthorised access, misuse or damage. Threats: (1) Virus and malware - self-replicating harmful programs; countered by antivirus software and regular updates. (2) Hacking/unauthorised access - countered by strong passwords, authentication and firewalls. (3) Phishing - fake emails or sites stealing credentials; countered by user awareness and verifying URLs. (4) Data interception (eavesdropping) - countered by encryption such as SSL/TLS and VPNs. Regular backups and access-control lists further reduce risk." }, b: { question: "Define encryption. Differentiate between symmetric and asymmetric encryption.", modelAnswer: "Encryption converts plaintext into unreadable ciphertext using an algorithm and a key, so only an authorised receiver with the correct key can decrypt it. In symmetric encryption the same secret key is used for both encryption and decryption (e.g. DES, AES); it is fast but key distribution is difficult. In asymmetric encryption a pair of keys is used - a public key to encrypt and a private key to decrypt (e.g. RSA); it solves key distribution and enables digital signatures but is slower." } },
    { a: { question: "Explain the main features of object-oriented programming.", modelAnswer: "(1) Class and object - a class is a blueprint defining data members and member functions; an object is its instance. (2) Encapsulation - data and functions are bound in one unit and data is hidden using access specifiers, protecting it from outside interference. (3) Inheritance - a derived class acquires the properties and behaviour of a base class, promoting code reuse and establishing an is-a hierarchy. (4) Polymorphism - the same interface behaves differently in different contexts, achieved by function overloading, operator overloading and virtual functions. (5) Abstraction - only essential features are shown while implementation details are hidden." }, b: { question: "Differentiate between a class and an object with an example.", modelAnswer: "A class is a user-defined data type, a logical blueprint that occupies no memory until instantiated; an object is a real instance of a class that occupies memory and holds actual values. Example: class Student { private: int roll; char name[30]; public: void input(); void display(); }; Here Student is the class, whereas Student s1, s2; creates two objects s1 and s2, each with its own copy of roll and name." } },
    { a: { question: "Describe the various types of transmission media used in computer networks.", modelAnswer: "Guided (wired) media: (1) Twisted pair - two insulated copper wires twisted to reduce crosstalk; cheap, easy to install, used in LANs; limited distance and bandwidth. (2) Coaxial cable - a central conductor surrounded by insulation, braided shield and jacket; higher bandwidth and better noise immunity, used in cable TV. (3) Fibre optic - transmits data as light pulses through a glass core; extremely high bandwidth, immune to electromagnetic interference, spans long distances, but costly and difficult to splice. Unguided (wireless) media: radio waves, microwaves, infrared and satellite, which need no physical cable and support mobility but are less secure and more affected by weather and interference." }, b: { question: "What is bandwidth? How does it affect network performance?", modelAnswer: "Bandwidth is the maximum amount of data that can be transmitted over a communication channel per unit time, measured in bits per second (bps, Kbps, Mbps, Gbps). Higher bandwidth allows more data to be carried simultaneously, giving faster downloads, smoother video streaming and support for more users. Low bandwidth causes congestion, delay (latency), packet loss and buffering. Actual usable bandwidth (throughput) is always lower than the theoretical maximum because of protocol overhead, noise and network traffic." } },
    { a: { question: "Explain the software development life cycle (SDLC) and its phases.", modelAnswer: "SDLC is a structured sequence of phases used to develop quality software. (1) Requirement analysis - gather and document what users need; produce an SRS. (2) Feasibility study - assess technical, economic and operational viability. (3) Design - prepare system architecture, database design, flowcharts and interface layouts. (4) Coding/implementation - translate the design into a programming language. (5) Testing - unit, integration, system and acceptance testing to find and remove errors. (6) Deployment - install the system and train users. (7) Maintenance - correct faults, adapt to new requirements and enhance performance. Feedback may return the project to an earlier phase." }, b: { question: "Differentiate between system software and application software with examples.", modelAnswer: "System software manages and controls the computer hardware and provides a platform on which application software runs; it is generally installed with the machine and written in low-level or system languages. Examples: operating systems (Windows, Linux), device drivers, compilers, utilities. Application software is designed to perform specific tasks for the end user and cannot run without system software. Examples: MS Word, Excel, media players, accounting packages and web browsers." } },
  ],
};

/* ===================== ENGLISH (Compulsory) ===================== */
const english: SubjectBank = {
  mcqs: [
    { question: "Choose the correct synonym of the word 'diligent'.", options: ["Hardworking", "Careless", "Rude", "Idle"], correctIndex: 0, explanation: "Diligent means showing persistent and hardworking effort." },
    { question: "Choose the correct antonym of the word 'ancient'.", options: ["Modern", "Old", "Historic", "Antique"], correctIndex: 0, explanation: "Ancient means very old; its opposite is modern." },
    { question: "Change into passive voice: 'She writes a letter.'", options: ["A letter is written by her", "A letter was written by her", "A letter has written by her", "A letter is being wrote by her"], correctIndex: 0, explanation: "Simple present passive = is/am/are + past participle." },
    { question: "Choose the correct spelling.", options: ["Occurrence", "Occurence", "Ocurrence", "Occurrance"], correctIndex: 0, explanation: "The correct spelling has double c, double r and -ence." },
    { question: "Identify the part of speech of the underlined word: 'He runs quickly.'  (quickly)", options: ["Adverb", "Adjective", "Noun", "Verb"], correctIndex: 0, explanation: "Quickly modifies the verb 'runs', so it is an adverb of manner." },
    { question: "Fill in the blank with the correct preposition: 'He is fond ___ music.'", options: ["of", "with", "for", "at"], correctIndex: 0, explanation: "The fixed expression is 'fond of'." },
    { question: "Change into indirect speech: He said, 'I am tired.'", options: ["He said that he was tired", "He says that he is tired", "He said that I was tired", "He told that he is tired"], correctIndex: 0, explanation: "Present tense changes to past and the pronoun changes accordingly." },
    { question: "Choose the correct form of the verb: 'Neither of the boys ___ present.'", options: ["was", "were", "have been", "are"], correctIndex: 0, explanation: "'Neither' is singular, so it takes a singular verb." },
    { question: "The idiom 'to burn the midnight oil' means:", options: ["To work late into the night", "To waste money", "To sleep early", "To set fire to something"], correctIndex: 0, explanation: "It refers to studying or working until very late." },
    { question: "Choose the word with the correct meaning of 'abundant'.", options: ["Plentiful", "Scarce", "Weak", "Narrow"], correctIndex: 0, explanation: "Abundant means existing in large quantity." },
    { question: "Select the correctly punctuated sentence.", options: ["Where are you going?", "Where are you going.", "where are you going?", "Where are you going!"], correctIndex: 0, explanation: "A direct question begins with a capital letter and ends with a question mark." },
    { question: "Fill in the blank: 'He has been living here ___ 2015.'", options: ["since", "for", "from", "at"], correctIndex: 0, explanation: "'Since' is used with a point of time; 'for' with a period." },
    { question: "Choose the plural of 'crisis'.", options: ["Crises", "Crisises", "Crisis", "Crisi"], correctIndex: 0, explanation: "Words ending in -is form the plural in -es (crisis - crises)." },
    { question: "Identify the tense: 'They had finished the work before I arrived.'", options: ["Past perfect", "Present perfect", "Past continuous", "Simple past"], correctIndex: 0, explanation: "'Had + past participle' denotes the past perfect tense." },
    { question: "Choose the correct article: '___ honest man is respected everywhere.'", options: ["An", "A", "The", "No article"], correctIndex: 0, explanation: "'Honest' begins with a vowel sound because the h is silent." },
  ],
  shorts: [
    { question: "Write a paragraph of about 100 words on 'The Importance of Time'.", modelAnswer: "Time is the most precious commodity in human life. Unlike wealth, once it is lost it can never be regained. Every successful person in history has valued time and used it purposefully. A student who wastes time in idle gossip and useless entertainment ruins his career, while one who divides his day into study, rest and recreation makes steady progress. Punctuality is the habit of respecting time, and nations that value time achieve rapid progress. Therefore we should prepare a daily timetable, avoid procrastination and make the best possible use of every moment granted to us." },
    { question: "Use the following idiom in a sentence: 'a bolt from the blue'.", modelAnswer: "The news of his father's sudden death came as a bolt from the blue for Ahmad, who had spoken to him only that morning. (Meaning: something completely unexpected and shocking.)" },
    { question: "Change the voice: 'The teacher punished the naughty boy.'", modelAnswer: "Passive: The naughty boy was punished by the teacher. Rule: subject and object are interchanged, the verb becomes 'was + past participle' for the simple past, and the agent is introduced with 'by'." },
    { question: "Change into indirect speech: She said to me, 'Where are you going?'", modelAnswer: "Indirect: She asked me where I was going. Rules applied: the reporting verb 'said to' becomes 'asked', the interrogative word 'where' acts as the conjunction, the sentence takes assertive word order, the present continuous changes to past continuous, and the question mark is dropped." },
    { question: "Correct the sentence: 'He do not knows the answer.'", modelAnswer: "Correct: He does not know the answer. Explanation: with the third person singular subject 'he' the auxiliary is 'does', and after the auxiliary 'does' the main verb is used in its base form 'know', not 'knows'." },
    { question: "Write the summary of any poem you have studied in your course.", modelAnswer: "The poem conveys a central moral lesson through simple imagery. The poet describes an ordinary situation and gradually develops it into a reflection on human life, urging the reader to value patience, hard work and sincerity. Through vivid comparisons and a regular rhyme scheme the poet makes the message memorable, and concludes by appealing to the reader to act upon this truth in daily life." },
    { question: "Make a sentence using the word 'perseverance'.", modelAnswer: "It was only through sheer perseverance that Fatima cleared the entry test after failing twice. (Meaning: continued steady effort in spite of difficulties.)" },
    { question: "Punctuate the following: my father said to me you must work hard", modelAnswer: "My father said to me, \"You must work hard.\" Corrections: capital M at the beginning, a comma after the reporting verb 'said to me', inverted commas enclosing the exact words, a capital Y for the first word of the quotation, and a full stop inside the closing inverted commas." },
    { question: "Write four sentences about your favourite personality.", modelAnswer: "My favourite personality is Quaid-e-Azam Muhammad Ali Jinnah. He was a brilliant lawyer and an honest, disciplined leader who never compromised on principles. Through constitutional struggle he won a separate homeland for the Muslims of the subcontinent. His motto of Unity, Faith and Discipline continues to inspire every Pakistani student." },
    { question: "Change the narration: He said, 'I shall go to Lahore tomorrow.'", modelAnswer: "Indirect: He said that he would go to Lahore the next day. Changes: 'shall' becomes 'would', the pronoun 'I' changes to 'he' according to the subject of the reporting verb, and the adverb 'tomorrow' changes to 'the next day'." },
    { question: "Give the meanings of and use in sentences: 'to look after'.", modelAnswer: "Meaning: to take care of. Sentence: My elder sister looks after our grandmother, who has been ill since last winter. The phrasal verb takes a direct object and cannot be separated." },
    { question: "Write an application to the Principal for a fee concession (outline only).", modelAnswer: "To, The Principal, Government High School, Lahore. Subject: Application for Fee Concession. Respected Sir, With due respect, I beg to state that my father is a labourer with a very limited income and cannot afford the monthly fee. I have always secured an A grade in the class. Kindly grant me a fee concession so that I may continue my studies. I shall be very thankful to you. Yours obediently, A.B.C, Class 10th, Roll No. 21. Dated: ___" },
    { question: "Fill in the blanks with suitable prepositions: (i) He is angry ___ me. (ii) She is good ___ mathematics.", modelAnswer: "(i) He is angry with me. (We are angry 'with' a person but angry 'at' a thing or situation.) (ii) She is good at mathematics. ('Good at' expresses skill in a subject or activity.)" },
    { question: "Define a simple sentence and give one example.", modelAnswer: "A simple sentence contains only one subject and one finite verb, expressing a single complete thought; it has one independent clause and no subordinate clause. Example: The sun rises in the east. Here 'the sun' is the subject and 'rises' is the finite verb." },
    { question: "Write the central idea of the lesson you liked most.", modelAnswer: "The central idea of the lesson is that true greatness lies in service to humanity rather than in wealth or position. The writer illustrates this through the conduct of the main character, who sacrifices personal comfort for the welfare of others, and concludes that a life devoted to others is the only life truly worth living." },
  ],
  longs: [
    { a: { question: "Write an essay of about 250-300 words on 'The Role of Technology in Education'.", modelAnswer: "Outline: (1) Introduction - technology has transformed every field including education. (2) Body: access to online lectures, digital libraries and e-books; multimedia makes abstract concepts visual and easy; distance learning reaches rural areas of Pakistan; smart boards and simulations improve science teaching; online assessment gives instant feedback. (3) Drawbacks - digital distraction, eye strain, unequal access due to poverty and load-shedding, dependence on ready-made material weakening creativity, and unreliable information. (4) Suggestions - balanced use under teacher supervision, provision of internet facilities in government schools, and teacher training. (5) Conclusion - technology is an excellent servant but a poor master; if used wisely under proper guidance it can revolutionise the educational standard of Pakistan." }, b: { question: "Write a letter to your friend congratulating him on his brilliant success in the examination.", modelAnswer: "Examination Hall, City A.B.C. 8th September 2026. My dear Ahmad, I was delighted to read in the newspaper that you have secured first position in the Intermediate examination. Please accept my heartiest congratulations. Your success is the fruit of your regular hard work, discipline and the constant guidance of your teachers and parents. I still remember how you devoted your summer vacation to your studies while the rest of us wasted our time. Please convey my respects to your parents, who must be proud of you today. My parents also send their good wishes. I hope you will continue this brilliant performance in your professional career as well. Yours sincerely, X.Y.Z." } },
    { a: { question: "Write an essay of about 250-300 words on 'My Aim in Life'.", modelAnswer: "Outline: (1) Introduction - a life without an aim is like a ship without a rudder. (2) Choice of aim - I want to become a doctor. (3) Reasons - the noble desire to serve suffering humanity; the acute shortage of qualified doctors in the rural areas of Pakistan; the respectable and financially secure nature of the profession; the inspiration of Abdul Sattar Edhi's example of selfless service. (4) Preparation - hard work in Biology, Chemistry and Physics, preparation for the MDCAT, and building qualities of patience and sympathy. (5) Plan of service - to establish a free dispensary in my village and treat poor patients without charge. (6) Conclusion - I pray to Almighty Allah to enable me to achieve this aim and serve my country honestly." }, b: { question: "Write an application to the Principal of your college for the issuance of a character certificate.", modelAnswer: "To, The Principal, Government College, Lahore. Subject: Application for the Issuance of a Character Certificate. Respected Sir, With due respect, it is stated that I have recently passed my Intermediate examination from your esteemed institution with an A grade. I now intend to seek admission to a university, and the admission form requires a character certificate issued by my previous institution. During my two years in this college I have never been involved in any indiscipline and have taken an active part in co-curricular activities. It is therefore requested that a character certificate may kindly be issued to me at your earliest convenience. I shall be highly obliged. Yours obediently, A.B.C. Class: 2nd Year (Pre-Medical). Roll No: 45. Dated: 8th September 2026." } },
    { a: { question: "Write a story with the moral 'Honesty is the best policy'.", modelAnswer: "Once a poor woodcutter named Rustam lived near a river in a small village. One day, while cutting wood on the bank, his old axe slipped from his hands and fell into the deep water. It was his only means of livelihood, so he sat down and began to weep bitterly. Suddenly a fairy appeared and asked the reason for his grief. On hearing his story she dived into the river and brought out a golden axe. 'Is this your axe?' she asked. 'No,' replied the woodcutter honestly. She then brought out a silver axe, and again he refused it. At last she produced his old iron axe, and his face lit up with joy. 'Yes, this is mine,' he cried. The fairy was greatly pleased with his honesty and gave him all three axes as a reward. When a greedy neighbour heard this, he deliberately threw his axe into the river and pretended to weep. The fairy appeared and showed him a golden axe, which he at once claimed as his own. The fairy vanished, and the greedy man lost even his own axe. Moral: Honesty is the best policy." }, b: { question: "Write a dialogue between two friends about the importance of sports in student life.", modelAnswer: "Ali: You look pale, Bilal. Why do you never come to the playground these days? Bilal: I want to top the class, so I study from morning till night. Ali: But health is more important than marks. Sports keep the body fit and the mind fresh. Bilal: Do you not think games waste precious study time? Ali: Not at all. A tired mind cannot concentrate. An hour of cricket or football refreshes you and doubles your efficiency afterwards. Bilal: That sounds reasonable. Ali: Moreover, games teach discipline, teamwork, tolerance and how to accept defeat gracefully - lessons no textbook can give. Bilal: You have convinced me. From tomorrow I shall join you in the playground for an hour every evening. Ali: Excellent! A sound mind lives only in a sound body." } },
    { a: { question: "Write an essay of about 250-300 words on 'Environmental Pollution in Pakistan'.", modelAnswer: "Outline: (1) Introduction - pollution means the contamination of air, water and land with harmful substances. (2) Kinds and causes: air pollution from vehicle smoke, brick kilns and factories, producing the notorious smog of Lahore; water pollution from untreated industrial effluent and sewage discharged into rivers and canals; land pollution from plastic bags and unmanaged solid waste; noise pollution from traffic and loudspeakers. (3) Effects - respiratory diseases, asthma, hepatitis and gastroenteritis; destruction of aquatic life; reduced crop yields; global warming and irregular rainfall damaging agriculture. (4) Remedies - strict enforcement of environmental laws, installation of treatment plants, promotion of CNG and electric vehicles, large-scale tree plantation, ban on polythene bags, and public awareness through the media and schools. (5) Conclusion - protecting the environment is a collective national duty; if we fail to act today, the coming generations will inherit an uninhabitable land." }, b: { question: "Write a letter to the Editor of a newspaper about the shortage of clean drinking water in your locality.", modelAnswer: "The Editor, Daily Dawn, Karachi. Subject: Shortage of Clean Drinking Water in Our Locality. Sir, Through the columns of your esteemed newspaper I wish to draw the attention of the concerned authorities to the acute shortage of clean drinking water in Gulshan Colony. For the last three months the water supplied through taps has been muddy and foul-smelling, and often the supply remains suspended for several days. The residents are compelled to purchase water at exorbitant rates, which the poor cannot afford. As a result, cases of gastroenteritis and hepatitis are rapidly increasing, and several children have been hospitalised. Repeated complaints to the local water board have produced no result. It is therefore requested that the water supply lines may be repaired, a filtration plant may be installed and the supply may be restored regularly. I hope the authorities will take prompt notice of this genuine grievance. Yours truly, A Resident, Gulshan Colony. Dated: 8th September 2026." } },
    { a: { question: "Write an essay of about 250-300 words on 'The Importance of Education for Women'.", modelAnswer: "Outline: (1) Introduction - women constitute about half of our population; keeping them uneducated means paralysing half the nation. (2) Islamic point of view - the Holy Prophet (PBUH) declared the seeking of knowledge obligatory for every Muslim man and woman; Hazrat Aisha (RA) was a great scholar. (3) Advantages: an educated mother is the first school of her children and shapes the character of the coming generation; educated women contribute to the economy as doctors, teachers, engineers and entrepreneurs; education gives them awareness of their legal and religious rights and protects them from exploitation; it improves family health, hygiene and planning. (4) Obstacles in Pakistan - poverty, outdated customs, lack of girls' schools in rural areas, insecurity of transport, and early marriages. (5) Suggestions - free education for girls, more schools with female staff near villages, scholarships and awareness campaigns. (6) Conclusion - as Napoleon said, 'Give me good mothers and I shall give you a good nation.' No country can prosper while its women remain uneducated." }, b: { question: "Write a paragraph on 'A Rainy Day' in about 150 words.", modelAnswer: "A rainy day in the scorching month of July brings a message of joy and relief. Last Friday the sky was overcast with thick dark clouds since early morning. A cool breeze began to blow, and soon it started drizzling; before long it was pouring heavily. The dusty streets were washed clean, the trees looked greener and the parched earth gave off a sweet fragrance. Children ran out of their houses, made paper boats and sailed them in the rainwater. My mother prepared hot pakoras and tea, and the whole family sat on the veranda enjoying the pleasant scene. However, the rain had its darker side too: the low-lying streets were flooded, the electricity failed for several hours and the traffic came to a standstill. Yet, on the whole, the day brought relief from the intense heat and remains a delightful memory." } },
  ],
};

/* ===================== URDU (Compulsory) ===================== */
const urdu: SubjectBank = {
  mcqs: [
    { question: "'آبِ حیات' کس کی تصنیف ہے؟", options: ["محمد حسین آزاد", "سر سید احمد خان", "مولانا حالی", "ڈپٹی نذیر احمد"], correctIndex: 0, explanation: "آبِ حیات محمد حسین آزاد کی مشہور تصنیف ہے جو اردو شاعری کی تاریخ پر مشتمل ہے۔" },
    { question: "غزل کے پہلے شعر کو کیا کہتے ہیں؟", options: ["مطلع", "مقطع", "قافیہ", "ردیف"], correctIndex: 0, explanation: "غزل کا پہلا شعر جس کے دونوں مصرعوں میں قافیہ اور ردیف ہو، مطلع کہلاتا ہے۔" },
    { question: "'توبۃ النصوح' کے مصنف کون ہیں؟", options: ["ڈپٹی نذیر احمد", "پریم چند", "منٹو", "غالب"], correctIndex: 0, explanation: "ڈپٹی نذیر احمد اردو کے پہلے ناول نگار مانے جاتے ہیں۔" },
    { question: "علامہ اقبال کا پہلا اردو شعری مجموعہ کون سا ہے؟", options: ["بانگِ درا", "بالِ جبریل", "ضربِ کلیم", "ارمغانِ حجاز"], correctIndex: 0, explanation: "بانگِ درا 1924ء میں شائع ہوا۔" },
    { question: "'مسدس' میں ہر بند کے کتنے مصرعے ہوتے ہیں؟", options: ["چھ", "چار", "پانچ", "آٹھ"], correctIndex: 0, explanation: "مسدس میں ہر بند چھ مصرعوں پر مشتمل ہوتا ہے۔" },
    { question: "غزل کے آخری شعر کو جس میں شاعر کا تخلص ہو، کیا کہتے ہیں؟", options: ["مقطع", "مطلع", "بیت", "ردیف"], correctIndex: 0, explanation: "مقطع میں شاعر اپنا تخلص استعمال کرتا ہے۔" },
    { question: "'دیوانِ غالب' کس زبان میں ہے؟", options: ["اردو", "فارسی", "عربی", "ترکی"], correctIndex: 0, explanation: "غالب کا اردو دیوان مشہور ہے، اگرچہ ان کا فارسی کلام بھی بہت زیادہ ہے۔" },
    { question: "لفظ 'کتاب' کی جمع کیا ہے؟", options: ["کتب", "کتابیں ہی", "کاتب", "مکتوب"], correctIndex: 0, explanation: "عربی قاعدے کے مطابق کتاب کی جمع 'کتب' ہے۔" },
    { question: "'سر سید احمد خان' نے کون سا رسالہ جاری کیا؟", options: ["تہذیب الاخلاق", "اودھ پنچ", "مخزن", "نیرنگِ خیال"], correctIndex: 0, explanation: "تہذیب الاخلاق کے ذریعے سر سید نے مسلمانوں کی اصلاح کا کام کیا۔" },
    { question: "'نظم' اور 'غزل' میں بنیادی فرق کیا ہے؟", options: ["نظم میں تسلسلِ خیال ہوتا ہے", "نظم میں قافیہ نہیں ہوتا", "غزل میں ردیف نہیں ہوتی", "دونوں میں کوئی فرق نہیں"], correctIndex: 0, explanation: "نظم میں ایک ہی مرکزی خیال تسلسل کے ساتھ بیان ہوتا ہے جبکہ غزل کا ہر شعر مستقل ہوتا ہے۔" },
    { question: "'رموزِ اوقاف' سے کیا مراد ہے؟", options: ["تحریر میں استعمال ہونے والی علامات", "شاعری کے اوزان", "قواعد کے اصول", "لفظوں کے معنی"], correctIndex: 0, explanation: "سکتہ، وقفہ، ختمہ، سوالیہ نشان وغیرہ رموزِ اوقاف کہلاتے ہیں۔" },
    { question: "مولانا الطاف حسین حالی کی مشہور نظم کون سی ہے؟", options: ["مدّ و جزرِ اسلام (مسدسِ حالی)", "شکوہ", "جوابِ شکوہ", "ساقی نامہ"], correctIndex: 0, explanation: "مسدسِ حالی مسلمانوں کے عروج و زوال پر مشتمل ہے۔" },
    { question: "لفظ 'ناخوش' میں 'نا' کیا ہے؟", options: ["سابقہ", "لاحقہ", "حرفِ جار", "اسم"], correctIndex: 0, explanation: "جو حرف لفظ کے شروع میں لگ کر نیا مفہوم دے، اسے سابقہ کہتے ہیں۔" },
    { question: "'افسانہ' کی سب سے اہم خصوصیت کیا ہے؟", options: ["اختصار اور وحدتِ تاثر", "طویل کہانی", "کئی پلاٹ", "صرف مکالمے"], correctIndex: 0, explanation: "افسانہ مختصر ہوتا ہے اور ایک ہی تاثر پیدا کرتا ہے۔" },
    { question: "'قافیہ' سے کیا مراد ہے؟", options: ["ہم آواز الفاظ جو ردیف سے پہلے آئیں", "شعر کا پہلا مصرع", "دہرایا جانے والا لفظ", "شاعر کا تخلص"], correctIndex: 0, explanation: "قافیہ وہ ہم آواز لفظ ہے جو ردیف سے پہلے آتا ہے۔" },
  ],
  shorts: [
    { question: "سر سید احمد خان کی علمی و ادبی خدمات پر مختصر نوٹ لکھیں۔", modelAnswer: "سر سید احمد خان اردو نثر کے معمار اور قوم کے محسن تھے۔ انہوں نے 1875ء میں مدرسۃ العلوم علی گڑھ قائم کیا جو بعد میں علی گڑھ یونیورسٹی بنا۔ رسالہ 'تہذیب الاخلاق' کے ذریعے مسلمانوں کی سماجی اصلاح کی۔ ان کی نثر سادہ، بامقصد اور مقصدیت سے بھرپور ہے۔ 'آثار الصنادید' اور 'خطباتِ احمدیہ' ان کی مشہور تصانیف ہیں۔ انہوں نے مسلمانوں کو جدید تعلیم اور انگریزی زبان سیکھنے کی ترغیب دی۔" },
    { question: "غزل کی تعریف کریں اور اس کے اجزا بیان کریں۔", modelAnswer: "غزل عربی لفظ ہے جس کے لغوی معنی 'عورتوں سے باتیں کرنا' ہیں۔ اصطلاح میں غزل ایسی صنفِ سخن ہے جس کے تمام اشعار ہم وزن، ہم قافیہ اور ہم ردیف ہوں۔ اجزا: (1) مطلع - پہلا شعر جس کے دونوں مصرعے ہم قافیہ ہوں۔ (2) مقطع - آخری شعر جس میں شاعر کا تخلص ہو۔ (3) قافیہ - ہم آواز الفاظ۔ (4) ردیف - وہ لفظ جو قافیے کے بعد بار بار آئے۔ (5) بیت - غزل کا ہر شعر۔" },
    { question: "'حوالہ متن' سے کیا مراد ہے؟ مثال دیں۔", modelAnswer: "حوالہ متن سے مراد یہ ہے کہ کسی عبارت کی تشریح سے پہلے یہ بتایا جائے کہ یہ اقتباس کس سبق سے لیا گیا ہے اور اس کے مصنف کون ہیں۔ مثال: سبق کا عنوان: 'لہو اور قالین'، مصنف کا نام: انتظار حسین۔ اس کے بعد سیاق و سباق اور پھر تشریح لکھی جاتی ہے۔" },
    { question: "علامہ اقبال کے تصورِ خودی کی وضاحت کریں۔", modelAnswer: "خودی سے اقبال کی مراد خود شناسی، خود اعتمادی اور اپنی ذات کے پوشیدہ امکانات کا شعور ہے۔ یہ تکبر یا غرور نہیں بلکہ اپنے مقام کی پہچان ہے۔ اقبال کے نزدیک خودی کی تربیت اطاعتِ الٰہی، ضبطِ نفس اور نیابتِ الٰہی کے مراحل سے گزر کر ہوتی ہے۔ خودی کو بلند کرنے والا انسان مردِ مومن بنتا ہے۔ ان کا مشہور شعر ہے: 'خودی کو کر بلند اتنا کہ ہر تقدیر سے پہلے / خدا بندے سے خود پوچھے بتا تیری رضا کیا ہے'۔" },
    { question: "واحد جمع بنائیں: (i) قلم (ii) طالب علم (iii) شہر", modelAnswer: "(i) قلم کی جمع 'اقلام' یا 'قلمیں' ہے۔ (ii) طالب علم کی جمع 'طلبہ' یا 'طالب علموں' ہے۔ (iii) شہر کی جمع 'شہر' یا عربی قاعدے سے 'امصار' ہے، عام استعمال میں 'شہروں' آتا ہے۔" },
    { question: "مضمون نگاری کے بنیادی اصول تحریر کریں۔", modelAnswer: "(1) موضوع کا انتخاب اور اس پر مکمل غور۔ (2) خاکہ یا آؤٹ لائن تیار کرنا۔ (3) تمہید جو دلچسپ اور مختصر ہو۔ (4) نفسِ مضمون جس میں خیالات ترتیب سے، الگ الگ پیراگراف میں بیان ہوں۔ (5) زبان سادہ، رواں اور بامحاورہ ہو۔ (6) اشعار، آیات یا اقوالِ زریں کا برمحل استعمال۔ (7) اختتام جامع اور مؤثر ہو۔ (8) رموزِ اوقاف کا درست استعمال۔" },
    { question: "'سیاق و سباق' کی وضاحت کریں۔", modelAnswer: "سیاق و سباق سے مراد وہ پس منظر ہے جس میں کوئی عبارت یا شعر کہا گیا ہو۔ اس میں یہ بتایا جاتا ہے کہ اس اقتباس سے پہلے کیا بیان ہوا اور اس کے بعد کیا آتا ہے، مصنف کس موقع پر یہ بات کہہ رہا ہے اور اس کا مقصد کیا ہے۔ عام طور پر سیاق و سباق چھ سے آٹھ جملوں پر مشتمل ہوتا ہے۔" },
    { question: "امدادی افعال کی تعریف کریں اور تین مثالیں دیں۔", modelAnswer: "امدادی افعال وہ افعال ہیں جو اصل فعل کے ساتھ مل کر زمانے، کیفیت یا حالت کو مکمل کرتے ہیں اور اکیلے مکمل مفہوم نہیں دیتے۔ مثالیں: (1) ہے / ہیں / تھا / تھے (2) رہا ہے، رہی ہے (3) چکا ہے، چکی ہے۔ جیسے 'وہ لکھ رہا ہے' میں 'رہا ہے' امدادی فعل ہے اور 'لکھ' اصل فعل ہے۔" },
    { question: "افسانہ اور ناول میں فرق واضح کریں۔", modelAnswer: "افسانہ مختصر ہوتا ہے، اس میں ایک ہی واقعہ، محدود کردار اور وحدتِ تاثر ہوتی ہے، اور اسے ایک نشست میں پڑھا جا سکتا ہے۔ ناول طویل ہوتا ہے، اس میں کئی واقعات، متعدد کردار اور ذیلی پلاٹ ہوتے ہیں، اور یہ زندگی کی مکمل تصویر پیش کرتا ہے۔ افسانے میں اختصار اہم ہے جبکہ ناول میں تفصیل و پھیلاؤ۔" },
    { question: "درج ذیل محاورے کو جملے میں استعمال کریں: 'آٹے دال کا بھاؤ معلوم ہونا'", modelAnswer: "معنی: حقیقتِ حال کا علم ہونا، مشکلات کا اندازہ ہونا۔ جملہ: جب اسلم نے اپنا الگ کاروبار شروع کیا تو اسے آٹے دال کا بھاؤ معلوم ہو گیا کہ روزی کمانا کتنا مشکل کام ہے۔" },
    { question: "رموزِ اوقاف کی چار علامتیں لکھیں اور ان کا استعمال بتائیں۔", modelAnswer: "(1) سکتہ (،) - جملے میں تھوڑے وقفے کے لیے۔ (2) وقفہ (؛) - سکتے سے زیادہ اور ختمے سے کم ٹھہراؤ کے لیے۔ (3) ختمہ (۔) - جملہ مکمل ہونے پر۔ (4) سوالیہ نشان (؟) - سوالیہ جملے کے آخر میں۔ (5) ندائیہ (!) - جذبات یا تعجب کے اظہار کے لیے۔ (6) واوین (\" \") - کسی کے الفاظ نقل کرنے کے لیے۔" },
    { question: "مولانا حالی کی مسدس کا مرکزی خیال بیان کریں۔", modelAnswer: "مسدسِ حالی کا اصل نام 'مدّ و جزرِ اسلام' ہے۔ اس میں حالی نے مسلمانوں کے شاندار ماضی، ان کے علمی، اخلاقی اور تہذیبی کارناموں کا ذکر کیا ہے اور پھر موجودہ زوال، جہالت، تن آسانی اور باہمی نفاق کا نقشہ کھینچا ہے۔ مقصد یہ ہے کہ مسلمان اپنے اسلاف کی روش پر واپس آئیں اور تعلیم و عمل سے دوبارہ عروج حاصل کریں۔" },
    { question: "خط اور درخواست میں فرق بیان کریں۔", modelAnswer: "خط ذاتی نوعیت کا ہوتا ہے، دوستوں یا رشتہ داروں کو لکھا جاتا ہے، اس میں بے تکلفی اور جذبات کا اظہار ہوتا ہے، اور آغاز 'پیارے/محترم' سے ہوتا ہے۔ درخواست سرکاری یا نیم سرکاری ہوتی ہے، کسی افسر یا سربراہ کو لکھی جاتی ہے، اس میں مخصوص ترتیب (بخدمت جناب، عنوان، جنابِ عالی، اختتام 'آپ کا فرمانبردار') ہوتی ہے اور زبان رسمی و مؤدبانہ ہوتی ہے۔" },
    { question: "سابقہ اور لاحقہ کی تعریف مثالوں سے کریں۔", modelAnswer: "سابقہ وہ حرف یا حروف ہیں جو لفظ کے شروع میں لگ کر نیا مفہوم پیدا کریں، جیسے 'نا' + 'کام' = ناکام، 'بے' + 'وفا' = بےوفا، 'ہم' + 'سفر' = ہمسفر۔ لاحقہ وہ ہے جو لفظ کے آخر میں لگے، جیسے 'دان' میں قلمدان، 'گار' میں مددگار، 'بان' میں باغبان۔" },
    { question: "نظم کی تعریف کریں اور اس کی اقسام بیان کریں۔", modelAnswer: "نظم وہ صنفِ سخن ہے جس میں ایک مرکزی خیال کو تسلسل کے ساتھ بیان کیا جاتا ہے اور تمام اشعار آپس میں مربوط ہوتے ہیں۔ اقسام: (1) پابند نظم - وزن اور قافیے کی پابندی۔ (2) آزاد نظم - وزن تو ہو مگر مصرعوں کی لمبائی مختلف۔ (3) نثری نظم - وزن و قافیہ سے آزاد۔ مزید اصناف میں مثنوی، قصیدہ، مرثیہ، رباعی اور مسدس شامل ہیں۔" },
  ],
  longs: [
    { a: { question: "علامہ اقبال کی شاعری کے نمایاں موضوعات پر تفصیلی نوٹ لکھیں۔", modelAnswer: "علامہ اقبال شاعرِ مشرق اور مفکرِ پاکستان کہلاتے ہیں۔ ان کی شاعری کے اہم موضوعات یہ ہیں: (1) خودی - خود شناسی اور خود اعتمادی کا تصور، جس کی تکمیل عشقِ رسول ﷺ سے ہوتی ہے۔ (2) عشق و عقل - اقبال کے نزدیک عقل رہنما ضرور ہے مگر منزل تک عشق پہنچاتا ہے۔ (3) مردِ مومن - وہ کامل انسان جو خودی کی تربیت سے بنتا ہے، جس کی نگاہ سے تقدیریں بدلتی ہیں۔ (4) تصورِ ملت - وطنیت کے بجائے عالمگیر اسلامی اخوت کا پیغام۔ (5) فلسفۂ حرکت و عمل - جمود اور تن آسانی کی مذمت اور مسلسل جدوجہد کی تلقین۔ (6) نوجوانوں سے خطاب - شاہین کی علامت کے ذریعے بلند پروازی، خودداری اور قناعت کا درس۔ (7) مغربی تہذیب پر تنقید - اس کی مادیت اور بے روح ترقی کا رد۔ اقبال کی زبان میں فارسی تراکیب کی شان و شوکت اور فکری گہرائی نمایاں ہے۔ 'بانگِ درا'، 'بالِ جبریل' اور 'ضربِ کلیم' ان کے مشہور اردو مجموعے ہیں۔" }, b: { question: "درج ذیل شعر کی تشریح کریں: 'خودی کو کر بلند اتنا کہ ہر تقدیر سے پہلے / خدا بندے سے خود پوچھے بتا تیری رضا کیا ہے'", modelAnswer: "شاعر کا نام: علامہ محمد اقبال۔ ماخذ: بالِ جبریل۔ مفہوم: اپنی خودی کو اس درجہ بلند کر لو کہ اللہ تعالیٰ بھی تقدیر لکھنے سے پہلے تمہاری مرضی دریافت کرے۔ تفصیلی تشریح: اقبال یہاں اپنے مرکزی فلسفۂ خودی کو نہایت بلیغ انداز میں پیش کرتے ہیں۔ خودی سے مراد وہ خود آگاہی اور خود اعتمادی ہے جو انسان کو اپنے مقامِ بندگی اور نیابتِ الٰہی کا شعور دیتی ہے۔ جب بندہ اطاعتِ الٰہی، ضبطِ نفس اور عشقِ رسول ﷺ کے ذریعے اپنی خودی کو کمال تک پہنچا دیتا ہے تو وہ اللہ کا محبوب بن جاتا ہے۔ ایسے بندے کی دعا میں وہ تاثیر پیدا ہو جاتی ہے کہ تقدیر بھی بدل جاتی ہے۔ حدیثِ قدسی میں بھی اسی مضمون کی طرف اشارہ ہے کہ جب میں بندے سے محبت کرتا ہوں تو اس کا ہاتھ اور اس کی زبان بن جاتا ہوں۔ شعر میں 'ہر تقدیر سے پہلے' کی ترکیب نہایت پُراثر ہے۔ اقبال نوجوانوں کو یہ درس دیتے ہیں کہ قسمت کے سہارے بیٹھنے کے بجائے اپنی ذات کو اس قابل بناؤ کہ حالات تمہارے تابع ہو جائیں۔" } },
    { a: { question: "اردو نثر میں سر سید احمد خان اور ان کے رفقا کی خدمات پر مفصل مضمون لکھیں۔", modelAnswer: "انیسویں صدی کے نصفِ آخر میں 1857ء کی ناکام جنگِ آزادی کے بعد مسلمان ہر لحاظ سے پستی کا شکار ہو چکے تھے۔ ایسے میں سر سید احمد خان نے قوم کی رہنمائی کا بیڑا اٹھایا۔ سر سید کی خدمات: انہوں نے 1875ء میں مدرسۃ العلوم علی گڑھ کی بنیاد رکھی، 'تہذیب الاخلاق' جاری کیا، اور 'آثار الصنادید'، 'اسبابِ بغاوتِ ہند' اور 'خطباتِ احمدیہ' جیسی تصانیف لکھیں۔ انہوں نے اردو نثر کو قدیم مقفیٰ و مسجع انداز سے نکال کر سادہ، سلیس اور بامقصد بنایا۔ رفقا: (1) مولانا الطاف حسین حالی - 'مسدسِ حالی'، 'مقدمہ شعر و شاعری' اور 'حیاتِ جاوید' کے مصنف، اردو تنقید کے بانی۔ (2) مولانا شبلی نعمانی - 'الفاروق'، 'سیرت النبی' اور 'شعر العجم' کے ذریعے سیرت نگاری اور تاریخ نویسی میں نئی راہیں کھولیں۔ (3) ڈپٹی نذیر احمد - اردو کے پہلے ناول نگار، 'مراۃ العروس'، 'بنات النعش' اور 'توبۃ النصوح' کے ذریعے اصلاحِ معاشرت کا کام کیا۔ (4) محمد حسین آزاد - 'آبِ حیات' اور 'نیرنگِ خیال' میں انشا پردازی کا اعلیٰ نمونہ پیش کیا۔ نتیجہ: اس تحریک نے اردو نثر کو مقصدیت، سادگی اور وسعت عطا کی اور مسلمانوں میں جدید تعلیم کا شعور پیدا کیا۔" }, b: { question: "'تعلیمِ نسواں' کے موضوع پر مضمون لکھیں۔", modelAnswer: "تمہید: عورت معاشرے کا نصف حصہ ہے۔ اسے جاہل رکھ کر کوئی قوم ترقی نہیں کر سکتی۔ اسلام اور تعلیم: حضور اکرم ﷺ نے فرمایا کہ علم حاصل کرنا ہر مسلمان مرد و عورت پر فرض ہے۔ حضرت عائشہؓ سے ہزاروں احادیث مروی ہیں۔ فوائد: (1) تعلیم یافتہ ماں بچے کی پہلی درسگاہ ہے اور آنے والی نسل کی تربیت کرتی ہے۔ (2) عورت ڈاکٹر، استاد اور انجینئر بن کر معیشت میں حصہ ڈالتی ہے۔ (3) وہ اپنے شرعی و قانونی حقوق سے آگاہ ہو کر استحصال سے بچتی ہے۔ (4) گھر کا نظم، صحت اور صفائی بہتر ہوتی ہے۔ رکاوٹیں: غربت، فرسودہ رسوم، دیہات میں لڑکیوں کے اسکولوں کی کمی، آمد و رفت کی عدم سہولت اور کم عمری کی شادی۔ تجاویز: مفت تعلیم، دیہات میں خواتین اساتذہ کے ساتھ اسکول، وظائف اور ذرائع ابلاغ کے ذریعے شعور بیداری۔ اختتام: نپولین نے کہا تھا 'تم مجھے اچھی مائیں دو، میں تمہیں اچھی قوم دوں گا'۔ لہٰذا تعلیمِ نسواں قومی ترقی کی بنیادی شرط ہے۔" } },
    { a: { question: "اردو افسانے کے ارتقا پر تفصیلی نوٹ لکھیں۔", modelAnswer: "افسانہ مغرب سے آنے والی صنف ہے جو بیسویں صدی کے آغاز میں اردو میں داخل ہوئی۔ آغاز: عام طور پر پریم چند کے افسانے 'کفن'، 'پوس کی رات' اور 'عیدگاہ' کو اردو افسانے کی بنیاد قرار دیا جاتا ہے۔ انہوں نے حقیقت نگاری کے ذریعے کسانوں، مزدوروں اور غریب طبقے کے مسائل کو موضوع بنایا۔ سجاد حیدر یلدرم نے رومانوی رنگ متعارف کرایا۔ ترقی پسند تحریک: 1936ء کے بعد سعادت حسن منٹو، کرشن چندر، راجندر سنگھ بیدی اور عصمت چغتائی نے سماجی ناانصافی، طبقاتی کشمکش اور تقسیمِ ہند کے المیے کو بے باکی سے بیان کیا۔ منٹو کے 'ٹوبہ ٹیک سنگھ' اور 'کھول دو' فسادات کی ہولناکی کا شاہکار ہیں۔ جدید دور: قرۃ العین حیدر، انتظار حسین، غلام عباس اور احمد ندیم قاسمی نے علامت، داخلی خود کلامی اور اساطیری اسلوب کو اپنایا۔ خصوصیات: اختصار، وحدتِ تاثر، محدود کردار، چست پلاٹ اور مؤثر اختتام۔ نتیجہ: اردو افسانہ آج ہماری تہذیبی اور سماجی زندگی کا سب سے توانا آئینہ ہے۔" }, b: { question: "درج ذیل شعر کی تشریح کریں: 'ہزاروں خواہشیں ایسی کہ ہر خواہش پہ دم نکلے / بہت نکلے مرے ارمان لیکن پھر بھی کم نکلے'", modelAnswer: "شاعر کا نام: مرزا اسد اللہ خاں غالب۔ ماخذ: دیوانِ غالب۔ مفہوم: میرے دل میں ایسی بےشمار خواہشیں ہیں کہ ہر ایک کی شدت جان لینے کے برابر ہے؛ اگرچہ بہت سی خواہشیں پوری بھی ہوئیں مگر پھر بھی وہ ناکافی محسوس ہوئیں۔ تفصیلی تشریح: یہ غالب کی مشہور ترین غزل کا مطلع ہے۔ شاعر انسانی فطرت کی اس ابدی حقیقت کی طرف اشارہ کرتا ہے کہ خواہشات کا سلسلہ کبھی ختم نہیں ہوتا۔ 'دم نکلے' کی ترکیب میں شدتِ آرزو کا بیان ہے کہ ہر خواہش اتنی گہری ہے کہ اس کے حصول میں جان چلی جائے۔ دوسرے مصرعے میں غالب یہ کہتے ہیں کہ اگرچہ زندگی میں بہت سے ارمان پورے ہوئے، مگر تشنگی باقی رہی۔ یہ شعر انسانی نفسیات کا نہایت لطیف مطالعہ ہے اور تصوف کے اس نکتے کی طرف بھی اشارہ کرتا ہے کہ دنیاوی خواہشات سے حقیقی تسکین حاصل نہیں ہوتی۔ غالب کے مخصوص فلسفیانہ انداز، ایجازواختصار اور معنی آفرینی کا بہترین نمونہ ہے۔" } },
    { a: { question: "'قائدِ اعظم محمد علی جناح' کے موضوع پر مضمون تحریر کریں۔", modelAnswer: "تمہید: قوموں کی تاریخ میں کبھی کبھار ایسی شخصیات پیدا ہوتی ہیں جو قوم کی تقدیر بدل دیتی ہیں۔ قائدِ اعظم ایسی ہی ہستی تھے۔ ابتدائی زندگی: 25 دسمبر 1876ء کو کراچی میں پیدا ہوئے۔ ابتدائی تعلیم سندھ مدرسۃ الاسلام سے حاصل کی اور پھر لندن سے بیرسٹری کی سند لی۔ سیاسی جدوجہد: ابتدا میں کانگریس میں شامل ہوئے اور ہندو مسلم اتحاد کے سفیر کہلائے، مگر کانگریس کے متعصبانہ رویے سے مایوس ہو کر مسلم لیگ کو منظم کیا۔ 1940ء کی قراردادِ لاہور ان کی قیادت میں منظور ہوئی اور صرف سات برس کی انتھک جدوجہد کے بعد 14 اگست 1947ء کو پاکستان معرضِ وجود میں آیا۔ اوصاف: سچائی، دیانت، اصول پسندی، عزمِ محکم، بےلوث قیادت اور غیر معمولی قانونی بصیرت ان کی نمایاں خوبیاں تھیں۔ انہوں نے کبھی اصولوں پر سمجھوتہ نہیں کیا۔ پیغام: انہوں نے قوم کو اتحاد، ایمان اور تنظیم کا زریں اصول دیا۔ اختتام: 11 ستمبر 1948ء کو وہ اس دنیا سے رخصت ہوئے۔ ان کے افکار پر عمل کر کے ہی ہم پاکستان کو ایک مضبوط اور خوشحال مملکت بنا سکتے ہیں۔" }, b: { question: "اپنے دوست کے نام خط لکھیں جس میں اسے امتحان میں کامیابی پر مبارکباد دی گئی ہو۔", modelAnswer: "امتحان ہال، شہر الف ب ج۔ 8 ستمبر 2026ء۔ پیارے بلال، السلام علیکم! آج اخبار میں انٹرمیڈیٹ کا نتیجہ دیکھا تو معلوم ہوا کہ تم نے بورڈ میں نمایاں پوزیشن حاصل کی ہے۔ یہ خبر پڑھ کر میری خوشی کی کوئی انتہا نہ رہی۔ میری طرف سے دلی مبارکباد قبول کرو۔ یہ کامیابی تمہاری مسلسل محنت، پابندیِ وقت اور والدین و اساتذہ کی دعاؤں کا نتیجہ ہے۔ مجھے اب بھی یاد ہے کہ جب ہم گرمیوں کی چھٹیاں کھیل کود میں گزار رہے تھے، تم اپنی کتابوں میں مصروف رہتے تھے۔ آج تمہاری وہ محنت رنگ لے آئی۔ اپنے والدینِ محترم کو میرا ادب و احترام پہنچانا، وہ آج یقیناً تم پر فخر کر رہے ہوں گے۔ میرے والدین نے بھی تمہارے لیے نیک تمناؤں کا اظہار کیا ہے۔ مجھے امید ہے کہ تم عملی زندگی میں بھی اسی طرح نام روشن کرو گے۔ جواب کا منتظر رہوں گا۔ تمہارا مخلص دوست، ا۔ب۔ج" } },
  ],
};

/* ===================== ISLAMIYAT ===================== */
const islam: SubjectBank = {
  mcqs: [
    { question: "The Holy Quran was revealed over a period of:", options: ["23 years", "10 years", "13 years", "40 years"], correctIndex: 0, explanation: "Revelation continued for about 13 years in Makkah and 10 in Madinah." },
    { question: "How many pillars of Islam are there?", options: ["Five", "Four", "Six", "Seven"], correctIndex: 0, explanation: "Kalima, Salat, Sawm, Zakat and Hajj." },
    { question: "The first revelation was received by the Holy Prophet (PBUH) in:", options: ["Cave Hira", "Cave Thaur", "Masjid-e-Nabvi", "Kaaba"], correctIndex: 0, explanation: "The first verses of Surah Al-Alaq were revealed in the cave of Hira." },
    { question: "Zakat is obligatory at the rate of:", options: ["2.5%", "5%", "10%", "20%"], correctIndex: 0, explanation: "One fortieth (2.5%) of wealth held for a full lunar year above nisab." },
    { question: "The migration of the Holy Prophet (PBUH) to Madinah is called:", options: ["Hijrah", "Hajj", "Umrah", "Isra"], correctIndex: 0, explanation: "The Hijrah in 622 CE marks the start of the Islamic calendar." },
    { question: "Which Surah is called the heart of the Quran?", options: ["Surah Yaseen", "Surah Rehman", "Surah Kahf", "Surah Mulk"], correctIndex: 0, explanation: "A hadith describes Surah Yaseen as the heart of the Quran." },
    { question: "The number of Rakats in the Fajr obligatory prayer is:", options: ["Two", "Three", "Four", "Five"], correctIndex: 0, explanation: "Fajr consists of two Farz Rakats preceded by two Sunnah." },
    { question: "'Huqooq-ul-Ibad' means:", options: ["Rights of fellow human beings", "Rights of Allah", "Rules of prayer", "Laws of inheritance"], correctIndex: 0, explanation: "These are duties owed to other people, which Allah does not forgive without their pardon." },
    { question: "The last sermon (Khutba Hajjat-ul-Wida) was delivered in:", options: ["10 A.H.", "8 A.H.", "2 A.H.", "6 A.H."], correctIndex: 0, explanation: "It was delivered at Arafat during the farewell pilgrimage in 10 A.H." },
    { question: "Which caliph is known as 'Farooq'?", options: ["Hazrat Umar (RA)", "Hazrat Abu Bakr (RA)", "Hazrat Usman (RA)", "Hazrat Ali (RA)"], correctIndex: 0, explanation: "Farooq means one who distinguishes between right and wrong." },
  ],
  shorts: [
    { question: "Explain the concept of Tauheed.", modelAnswer: "Tauheed is the belief in the absolute oneness of Allah in His being, attributes and worship. He is the sole Creator, Sustainer and Master; He has no partner, no offspring and nothing resembles Him. Surah Al-Ikhlas summarises this belief. Tauheed is the foundation of Islam and its opposite, shirk, is the greatest sin." },
    { question: "What is meant by 'Huqooq-ul-Ibad'? Give examples.", modelAnswer: "Huqooq-ul-Ibad are the rights of fellow human beings, as distinct from Huqooq-Allah. Examples: honesty in dealings, paying a worker his wages before his sweat dries, kindness to parents and neighbours, care of orphans and the poor, and avoiding backbiting. Allah may forgive His own rights but the rights of people are not forgiven until the wronged person pardons." },
    { question: "State the importance of Salat in Islam.", modelAnswer: "Salat is the second pillar of Islam and the first act to be reckoned on the Day of Judgement. It is obligatory five times a day, establishes a direct link between the servant and Allah, restrains from indecency and evil (Surah Al-Ankabut), teaches punctuality, cleanliness, discipline and equality, since rich and poor stand shoulder to shoulder in congregation." },
    { question: "Describe the significance of Zakat in the Islamic economic system.", modelAnswer: "Zakat is the third pillar of Islam, obligatory at 2.5% on wealth held above nisab for one lunar year. It purifies both wealth and the heart from greed, and redistributes wealth from the affluent to the needy. It reduces the gap between rich and poor, discourages hoarding, promotes circulation of money, and creates a welfare society. The eight categories of recipients are listed in Surah At-Tawbah." },
    { question: "Write a short note on the Farewell Sermon (Khutba Hajjat-ul-Wida).", modelAnswer: "Delivered at Arafat in 10 A.H. before about 124,000 companions, it is regarded as the first charter of human rights. Its main points: sanctity of life, property and honour; abolition of interest and blood revenge of the age of ignorance; no superiority of an Arab over a non-Arab except by piety; kind treatment of women and slaves; and the command to hold fast to the Quran and Sunnah." },
    { question: "What are the main sources of Islamic law?", modelAnswer: "(1) The Holy Quran - the primary and absolute source, the word of Allah. (2) Sunnah - the sayings, actions and approvals of the Holy Prophet (PBUH), which explain and elaborate the Quran. (3) Ijma - the consensus of qualified Muslim scholars of an age on a legal issue. (4) Qiyas - analogical reasoning applying an established ruling to a new but similar case." },
    { question: "Explain the concept of Risalat.", modelAnswer: "Risalat is the belief that Allah sent prophets to guide mankind, beginning with Hazrat Adam (AS) and ending with Hazrat Muhammad (PBUH), the Khatam-un-Nabiyyin. Prophets are chosen, sinless (masoom) human beings who convey divine revelation, present a practical model of the teachings, and warn of accountability. Belief in Risalat is part of the Kalima and is essential to faith." },
    { question: "Describe the rights of parents in Islam.", modelAnswer: "The Quran places obedience to parents immediately after the worship of Allah (Surah Bani Israel). Children must speak to them respectfully, never say even 'uff' to them, obey them in all lawful matters, serve them especially in old age, spend on them, and pray for their forgiveness. The Holy Prophet (PBUH) said Paradise lies beneath the feet of the mother, and that Allah's pleasure lies in the father's pleasure." },
    { question: "What is Jihad? Explain its kinds.", modelAnswer: "Jihad literally means to strive and exert utmost effort in the way of Allah. Kinds: (1) Jihad bin-Nafs - struggle against one's own evil desires, called the greater jihad. (2) Jihad bil-Lisan and bil-Qalam - conveying truth by speech and pen. (3) Jihad bil-Maal - spending wealth for the cause of Islam. (4) Jihad bis-Saif - armed struggle, permitted only in defence, under a lawful authority, with strict rules forbidding harm to women, children, the aged and places of worship." },
    { question: "Write down the importance of seeking knowledge in Islam.", modelAnswer: "The first revealed word was 'Iqra' (Read). The Holy Prophet (PBUH) declared that seeking knowledge is obligatory upon every Muslim man and woman, and that the ink of the scholar is more sacred than the blood of the martyr. He also said, 'Seek knowledge even if you have to go to China.' Islam encourages both religious and worldly beneficial knowledge, and the Quran repeatedly asks people to reflect on the universe." },
  ],
  longs: [
    { a: { question: "Describe the social and economic system established by Islam for the welfare of society.", modelAnswer: "Social system: Islam establishes equality of all human beings, declaring that no Arab is superior to a non-Arab except by piety. It guarantees the sanctity of life, property and honour, grants women the right to inherit, own property, gain education and consent in marriage, and abolished female infanticide. It stresses the rights of neighbours, orphans, widows and the poor, and forbids backbiting, suspicion and mockery. Economic system: (1) Zakat, obligatory at 2.5%, redistributes wealth to the eight prescribed categories. (2) Riba (interest) is strictly prohibited as it concentrates wealth and exploits the needy. (3) Lawful earning (halal rizq) is emphasised, and hoarding, gambling, bribery, short measure and fraud are forbidden. (4) The law of inheritance divides property among many heirs, preventing accumulation. (5) Sadaqah, Ushr and Khums provide further support. The aim is a welfare society in which wealth does not circulate only among the rich, as stated in Surah Al-Hashr." }, b: { question: "Explain the prohibition of Riba (interest) in Islam and its wisdom.", modelAnswer: "Riba is any predetermined excess taken over the principal amount of a loan. The Quran declares in Surah Al-Baqarah that Allah has permitted trade and forbidden riba, and warns of war from Allah and His Messenger against those who do not abandon it. The Holy Prophet (PBUH) cursed the one who takes it, the one who gives it, the one who records it and the witnesses. Wisdom: interest guarantees profit to the lender without any risk or labour, while the borrower bears the entire risk, which is unjust. It concentrates wealth in a few hands, increases inflation and unemployment, discourages charity and mutual sympathy, and pushes the poor and indebted nations into permanent slavery. Islam instead promotes profit-and-loss sharing arrangements such as Mudarabah and Musharakah, and Qarz-e-Hasna, in which the lender expects reward only from Allah." } },
    { a: { question: "Write a detailed note on the life and character of the Holy Prophet (PBUH) as a model for mankind.", modelAnswer: "The Quran declares, 'Indeed in the Messenger of Allah you have an excellent example' (Surah Al-Ahzab 33:21). Before prophethood he was known as Sadiq (truthful) and Ameen (trustworthy) even among his enemies. As a son, husband and father he was affectionate and just; as a neighbour, kind and forgiving. As a teacher he was patient and gentle, never rebuking harshly. As a judge he was absolutely impartial, declaring that even if his own daughter Fatimah (RA) stole, her hand would be cut off. As a statesman he framed the Charter of Madinah, guaranteeing rights to Jews and other communities. As a commander he forbade harm to women, children, the aged, monks and trees. At the conquest of Makkah, though fully victorious, he forgave his bitterest enemies saying, 'Go, you are free.' He lived simply, mended his own shoes, milked his goat, sat with the poor and freed slaves. Thus his life provides complete guidance in every sphere - individual, family, social, economic, political and spiritual." }, b: { question: "Discuss the rights of women granted by Islam.", modelAnswer: "Before Islam women were treated as property, deprived of inheritance and baby girls were buried alive. Islam elevated their status. (1) Right to life - female infanticide was abolished and the Prophet (PBUH) promised Paradise to one who raises daughters well. (2) Right to inheritance - the Quran fixes definite shares for mother, wife, daughter and sister in Surah An-Nisa. (3) Right to education - seeking knowledge is obligatory on every Muslim man and woman. (4) Right to own property and to earn, keep and spend her own wealth and mahr independently. (5) Right of consent in marriage; a marriage without her consent is invalid, and she has the right of khula. (6) Right to maintenance - the husband must provide food, clothing and shelter. (7) Honour and dignity - as a mother, Paradise lies beneath her feet; as a wife, the best of men are those best to their wives; as a daughter, she is a mercy. The farewell sermon specifically enjoined kind treatment of women." } },
  ],
};

export const QUESTION_BANK: Record<string, SubjectBank> = {
  biology,
  cs,
  english,
  urdu,
  islam,
};

export default QUESTION_BANK;
