/**
 * Authoritative chapter lists for the BISE / PCTB curriculum.
 *
 * WHY THIS FILE EXISTS
 * --------------------
 * The chapter arrays previously inlined in App.tsx were heavily truncated:
 * 30 of the 42 syllabus entries listed fewer than 8 chapters, and several
 * collapsed whole spans of the book into a single row (12th Chemistry had
 * "Unit 8-12: Hydrocarbons, Alcohols & Alkyl Halides" as one item and omitted
 * units 3-6 entirely). A student ticking those off would believe they had
 * finished the book while missing most of it, and the Dashboard completion
 * percentage was correspondingly wrong.
 *
 * These lists follow the Punjab Curriculum & Textbook Board (PCTB) editions
 * used by all Punjab boards, which FBISE/KPK/Sindh/Balochistan track closely
 * in chapter count and order. Verified against ilmkidunya, PDF Hive and
 * out-class chapter indexes (Sept 2026).
 *
 * Keyed by the same syllabus id used in App.tsx's getSyllabusForClass().
 * Anything not listed here keeps its original inline list.
 */

export const CHAPTER_LISTS: Record<string, string[]> = {
  /* ============================ CLASS 9 ============================ */

  "syl-math-9-sci": [
    "Unit 1: Matrices and Determinants",
    "Unit 2: Real and Complex Numbers",
    "Unit 3: Logarithms",
    "Unit 4: Algebraic Expressions and Algebraic Formulas",
    "Unit 5: Factorization",
    "Unit 6: Algebraic Manipulation",
    "Unit 7: Linear Equations and Inequalities",
    "Unit 8: Linear Graphs and Their Application",
    "Unit 9: Introduction to Coordinate Geometry",
    "Unit 10: Congruent Triangles",
    "Unit 11: Parallelograms and Triangles",
    "Unit 12: Line Bisectors and Angle Bisectors",
    "Unit 13: Sides and Angles of a Triangle",
    "Unit 14: Ratio and Proportion",
    "Unit 15: Pythagoras Theorem",
    "Unit 16: Theorems Related with Area",
    "Unit 17: Practical Geometry - Triangles",
  ],

  "syl-math-9-art": [
    "Unit 1: Percentage, Ratio and Proportion",
    "Unit 2: Zakat, Ushr and Inheritance",
    "Unit 3: Business Mathematics",
    "Unit 4: Financial Mathematics (Taxes and Insurance)",
    "Unit 5: Consumer Mathematics (Profit, Loss, Discount)",
    "Unit 6: Exponents and Logarithms",
    "Unit 7: Arithmetic and Geometric Sequences",
    "Unit 8: Sets and Functions",
    "Unit 9: Linear Equations and Inequalities",
    "Unit 10: Matrices and Determinants",
    "Unit 11: Basic Statistics",
    "Unit 12: Geometry: Lines, Angles and Triangles",
  ],

  "syl-ch-9-sci": [
    "Unit 1: Fundamentals of Chemistry",
    "Unit 2: Structure of Atoms",
    "Unit 3: Periodic Table and Periodicity of Properties",
    "Unit 4: Structure of Molecules (Chemical Bonding)",
    "Unit 5: Physical States of Matter",
    "Unit 6: Solutions",
    "Unit 7: Electrochemistry",
    "Unit 8: Chemical Reactivity",
  ],

  "syl-bio-9-sci": [
    "Unit 1: Introduction to Biology",
    "Unit 2: Solving a Biological Problem",
    "Unit 3: Biodiversity",
    "Unit 4: Cells and Tissues",
    "Unit 5: Cell Cycle",
    "Unit 6: Enzymes",
    "Unit 7: Bioenergetics (Photosynthesis & Respiration)",
    "Unit 8: Nutrition",
    "Unit 9: Transport",
  ],

  "syl-cs-9": [
    "Unit 1: Problem Solving",
    "Unit 2: Binary System (Number Systems)",
    "Unit 3: Networks",
    "Unit 4: Data and Privacy",
    "Unit 5: Designing Websites (HTML)",
    "Unit 6: Introduction to Programming",
    "Unit 7: Input / Output Handling",
    "Unit 8: Computational Thinking and Algorithms",
  ],

  "syl-gsci-9-art": [
    "Unit 1: The Nature of Science",
    "Unit 2: Life and Living Things (Cells & Organisms)",
    "Unit 3: Human Body Systems and Health",
    "Unit 4: Diversity Among Living Things",
    "Unit 5: Matter and Its Structure",
    "Unit 6: Chemical Reactions in Daily Life",
    "Unit 7: Energy, Force and Motion",
    "Unit 8: Electricity and Magnetism in Daily Life",
    "Unit 9: The Earth, Atmosphere and Environment",
    "Unit 10: Space and the Solar System",
  ],

  "syl-isl-9-all": [
    "Unit 1: Aqaid (Tauheed, Risalat and Akhirat)",
    "Unit 2: Ibadat (Salat, Sawm, Zakat and Hajj)",
    "Unit 3: Quranic Ayat and Their Translation",
    "Unit 4: Ahadith-e-Nabvi (SAW) and Their Explanation",
    "Unit 5: Seerat-un-Nabi (SAW) - Makki Life",
    "Unit 6: Seerat-un-Nabi (SAW) - Madani Life",
    "Unit 7: Akhlaqiyat (Islamic Morals and Manners)",
    "Unit 8: Huqooq-ul-Ibad (Rights of Fellow Beings)",
    "Unit 9: Khulafa-e-Rashideen and Their Services",
  ],

  /* ============================ CLASS 10 ============================ */

  "syl-math-10-sci": [
    "Unit 1: Quadratic Equations",
    "Unit 2: Theory of Quadratic Equations",
    "Unit 3: Variations",
    "Unit 4: Partial Fractions",
    "Unit 5: Sets and Functions",
    "Unit 6: Basic Statistics",
    "Unit 7: Introduction to Trigonometry",
    "Unit 8: Projection of a Side of a Triangle",
    "Unit 9: Chords of a Circle",
    "Unit 10: Tangent to a Circle",
    "Unit 11: Chords and Arcs",
    "Unit 12: Angle in a Segment of a Circle",
    "Unit 13: Practical Geometry - Circles",
  ],

  "syl-math-10-art": [
    "Unit 1: Algebraic Formulas and Applications",
    "Unit 2: Factorization and Algebraic Manipulation",
    "Unit 3: Linear Equations and Inequalities",
    "Unit 4: Quadratic Equations",
    "Unit 5: Matrices and Determinants",
    "Unit 6: Sets and Functions",
    "Unit 7: Basic Statistics (Mean, Median, Mode)",
    "Unit 8: Introduction to Trigonometry",
    "Unit 9: Practical Geometry and Mensuration",
    "Unit 10: Business and Financial Mathematics",
  ],

  "syl-ch-10-sci": [
    "Unit 9: Chemical Equilibrium",
    "Unit 10: Acids, Bases and Salts",
    "Unit 11: Organic Chemistry",
    "Unit 12: Hydrocarbons",
    "Unit 13: Biochemistry",
    "Unit 14: The Atmosphere",
    "Unit 15: Water",
    "Unit 16: Chemical Industries",
  ],

  "syl-bio-10-sci": [
    "Unit 10: Gaseous Exchange",
    "Unit 11: Homeostasis",
    "Unit 12: Coordination and Control",
    "Unit 13: Support and Movement",
    "Unit 14: Reproduction",
    "Unit 15: Inheritance",
    "Unit 16: Man and His Environment",
    "Unit 17: Biotechnology",
    "Unit 18: Pharmacology",
  ],

  "syl-cs-10": [
    "Unit 1: Programming Fundamentals (C / Python)",
    "Unit 2: User Interaction and Input Handling",
    "Unit 3: Conditional Logic and Control Structures",
    "Unit 4: Data and Repetition (Loops)",
    "Unit 5: Functions and Modular Programming",
    "Unit 6: Arrays and Data Structures",
    "Unit 7: Databases and Data Management",
    "Unit 8: Web Development and Publishing",
  ],

  "syl-gsci-10-art": [
    "Unit 1: Environment and Pollution Control",
    "Unit 2: Natural Resources and Their Conservation",
    "Unit 3: Human Health, Disease and Nutrition",
    "Unit 4: Heredity and Reproduction in Living Things",
    "Unit 5: Acids, Bases, Salts and Everyday Chemicals",
    "Unit 6: Chemical Industries and Their Products",
    "Unit 7: Sound, Light and Optical Instruments",
    "Unit 8: Electricity, Magnetism and Electronics",
    "Unit 9: Information Technology and Communication",
    "Unit 10: Space Science and Modern Technology",
  ],

  "syl-isl-10-all": [
    "Unit 1: Quranic Surahs and Their Translation",
    "Unit 2: Ahadith and Their Explanation",
    "Unit 3: Seerat-un-Nabi (SAW) as a Model of Life",
    "Unit 4: Ibadat and Their Social Wisdom",
    "Unit 5: Islamic Social and Economic System",
    "Unit 6: Ideology of Pakistan and Its Basis",
    "Unit 7: Pakistan Movement and the Creation of Pakistan",
    "Unit 8: Land, Climate and Resources of Pakistan",
    "Unit 9: Population, Culture and Society of Pakistan",
    "Unit 10: Pakistan and the Muslim World",
  ],

  /* ============================ CLASS 11 ============================ */

  "syl-math-11-fsc": [
    "Unit 1: Number Systems",
    "Unit 2: Sets, Functions and Groups",
    "Unit 3: Matrices and Determinants",
    "Unit 4: Quadratic Equations",
    "Unit 5: Partial Fractions",
    "Unit 6: Sequences and Series",
    "Unit 7: Permutation, Combination and Probability",
    "Unit 8: Mathematical Induction and Binomial Theorem",
    "Unit 9: Fundamentals of Trigonometry",
    "Unit 10: Trigonometric Identities (Sum and Difference)",
    "Unit 11: Trigonometric Functions and Their Graphs",
    "Unit 12: Application of Trigonometry",
    "Unit 13: Inverse Trigonometric Functions",
    "Unit 14: Solutions of Trigonometric Equations",
  ],

  "syl-math-11-comm": [
    "Unit 1: Number Systems and Sets",
    "Unit 2: Ratio, Proportion and Percentage",
    "Unit 3: Simple and Compound Interest",
    "Unit 4: Annuities and Present Value",
    "Unit 5: Matrices and Determinants",
    "Unit 6: Linear Equations and Inequalities",
    "Unit 7: Quadratic Equations in Business",
    "Unit 8: Sequences and Series",
    "Unit 9: Permutation, Combination and Probability",
    "Unit 10: Mathematics of Trade and Discount",
  ],

  "syl-cs-11": [
    "Unit 1: Information and Data",
    "Unit 2: Number Systems and Data Representation",
    "Unit 3: Digital Logic and Boolean Algebra",
    "Unit 4: Computer Architecture and Components",
    "Unit 5: Operating Systems",
    "Unit 6: Computer Networks and Topologies",
    "Unit 7: Data Communication and Transmission",
    "Unit 8: Internet, Web and Emerging Technologies",
    "Unit 9: Security, Privacy and Cyber Ethics",
    "Unit 10: Introduction to Programming and Algorithms",
  ],

  "syl-comm-11": [
    "Unit 1: Introduction to Commerce and Business",
    "Unit 2: Forms of Business Organisation",
    "Unit 3: Sole Proprietorship and Partnership",
    "Unit 4: Joint Stock Company",
    "Unit 5: Co-operative Societies and State Enterprises",
    "Unit 6: Trade: Home and Foreign",
    "Unit 7: Channels of Distribution",
    "Unit 8: Aids to Trade: Banking and Insurance",
    "Unit 9: Aids to Trade: Transport, Warehousing and Advertising",
    "Unit 10: Business Combination and Stock Exchange",
  ],

  "syl-acc-11": [
    "Unit 1: Introduction to Accounting",
    "Unit 2: The Accounting Equation and Double Entry",
    "Unit 3: Books of Original Entry (Journal)",
    "Unit 4: Ledger and Posting",
    "Unit 5: Cash Book and Petty Cash Book",
    "Unit 6: Bank Reconciliation Statement",
    "Unit 7: Trial Balance and Rectification of Errors",
    "Unit 8: Adjusting and Closing Entries",
    "Unit 9: Financial Statements of a Sole Trader",
    "Unit 10: Depreciation and Its Accounting Treatment",
    "Unit 11: Capital and Revenue Expenditure",
  ],

  "syl-isl-11-all": [
    "Unit 1: Tauheed and Its Effects on Human Life",
    "Unit 2: Risalat and the Finality of Prophethood",
    "Unit 3: Belief in the Hereafter (Akhirat)",
    "Unit 4: The Holy Quran: Compilation and Importance",
    "Unit 5: Hadith and Sunnah as Sources of Guidance",
    "Unit 6: Ibadat and Their Spiritual Wisdom",
    "Unit 7: Islamic Moral System (Akhlaqiyat)",
    "Unit 8: Huqooq-ul-Ibad and Social Justice",
    "Unit 9: The Islamic Economic and Social System",
  ],

  /* ============================ CLASS 12 ============================ */

  "syl-math-12-fsc": [
    "Unit 1: Functions and Limits",
    "Unit 2: Differentiation",
    "Unit 3: Integration",
    "Unit 4: Introduction to Analytic Geometry",
    "Unit 5: Linear Inequalities and Linear Programming",
    "Unit 6: Conic Sections",
    "Unit 7: Vectors",
  ],

  "syl-math-12-comm": [
    "Unit 1: Introduction to Statistics and Data",
    "Unit 2: Presentation of Data (Tables and Graphs)",
    "Unit 3: Measures of Central Tendency",
    "Unit 4: Measures of Dispersion",
    "Unit 5: Index Numbers",
    "Unit 6: Time Series Analysis",
    "Unit 7: Correlation and Regression",
    "Unit 8: Probability and Probability Distributions",
    "Unit 9: Sampling and Estimation",
    "Unit 10: Statistical Inference in Business",
  ],

  "syl-ch-11-fsc": [
    "Unit 1: Basic Concepts",
    "Unit 2: Experimental Techniques in Chemistry",
    "Unit 3: Gases",
    "Unit 4: Liquids and Solids",
    "Unit 5: Atomic Structure",
    "Unit 6: Chemical Bonding",
    "Unit 7: Thermochemistry",
    "Unit 8: Chemical Equilibrium",
    "Unit 9: Solutions",
    "Unit 10: Electrochemistry",
    "Unit 11: Reaction Kinetics",
  ],
  "syl-ch-12-fsc": [
    "Unit 1: Periodic Classification of Elements and Periodicity",
    "Unit 2: s-Block Elements",
    "Unit 3: Group IIIA and Group IVA Elements",
    "Unit 4: Group VA and Group VIA Elements",
    "Unit 5: The Halogens and the Noble Gases",
    "Unit 6: Transition Elements",
    "Unit 7: Fundamental Principles of Organic Chemistry",
    "Unit 8: Aliphatic Hydrocarbons",
    "Unit 9: Aromatic Hydrocarbons",
    "Unit 10: Alkyl Halides",
    "Unit 11: Alcohols, Phenols and Ethers",
    "Unit 12: Aldehydes and Ketones",
    "Unit 13: Carboxylic Acids",
    "Unit 14: Macromolecules",
    "Unit 15: Common Chemical Industries in Pakistan",
    "Unit 16: Environmental Chemistry",
  ],

  "syl-bio-12-fsc": [
    "Unit 15: Homeostasis",
    "Unit 16: Support and Movement",
    "Unit 17: Coordination and Control",
    "Unit 18: Reproduction",
    "Unit 19: Growth and Development",
    "Unit 20: Chromosomes and DNA",
    "Unit 21: Cell Cycle",
    "Unit 22: Variation and Genetics",
    "Unit 23: Biotechnology",
    "Unit 24: Evolution",
    "Unit 25: Ecosystem",
    "Unit 26: Some Major Ecosystems",
    "Unit 27: Man and His Environment",
  ],

  "syl-cs-12-fsc": [
    "Unit 1: Data Basics and Database Concepts",
    "Unit 2: Data Integrity and Normalisation",
    "Unit 3: Introduction to Database Management Systems",
    "Unit 4: Microsoft Access and Query Design",
    "Unit 5: Structured Query Language (SQL)",
    "Unit 6: Introduction to C Language",
    "Unit 7: Input / Output Handling in C",
    "Unit 8: Decision Constructs and Control Structures",
    "Unit 9: Loop Constructs and Iteration",
    "Unit 10: Functions and Arrays",
  ],

  "syl-comm-12": [
    "Unit 1: Introduction to Commercial Geography",
    "Unit 2: Location, Land and Physical Features of Pakistan",
    "Unit 3: Climate and Its Effect on Economic Activity",
    "Unit 4: Agricultural Resources and Crops",
    "Unit 5: Water Resources and Irrigation",
    "Unit 6: Mineral and Power Resources",
    "Unit 7: Industries of Pakistan",
    "Unit 8: Means of Transport and Communication",
    "Unit 9: Foreign Trade of Pakistan",
    "Unit 10: Population and Human Resources",
  ],

  "syl-acc-12": [
    "Unit 1: Partnership: Formation and Accounts",
    "Unit 2: Partnership: Admission of a Partner",
    "Unit 3: Partnership: Retirement and Death",
    "Unit 4: Partnership: Dissolution of a Firm",
    "Unit 5: Company Accounts: Issue of Shares",
    "Unit 6: Company Accounts: Debentures",
    "Unit 7: Financial Statements of a Company",
    "Unit 8: Analysis of Financial Statements (Ratios)",
    "Unit 9: Cash Flow Statement",
    "Unit 10: Accounting for Non-Trading Concerns",
    "Unit 11: Single Entry and Incomplete Records",
  ],

  "syl-eng-12-all": [
    "Book III: Prose - The Dying Sun",
    "Book III: Prose - Using the Scientific Method",
    "Book III: Prose - Why Boys Fail in College",
    "Book III: Prose - End of Term",
    "Book III: Prose - On Destroying Books",
    "Book III: Prose - The Man Who Was a Hospital",
    "Book III: Prose - My Financial Career",
    "Book III: Prose - China's Way to Progress",
    "Book III: Prose - Hunger and Population Explosion",
    "Book III: Prose - The Jewel of the World",
    "Book III: Prose - First Year at Harrow",
    "Book III: Prose - Hitch-hiking Across the Sahara",
    "Book III: Prose - Sir Alexander Fleming",
    "Book III: Prose - Louis Pasteur",
    "Poems: Selected Poems (Book III)",
    "Play: Heat Lightning",
    "Writing Skills: Essays, Letters and Applications",
    "Grammar: Translation, Idioms and Pair of Words",
  ],

  "syl-urd-12-all": [
    "نثر: سبق ۱ تا ۵ (تشریحات و خلاصہ)",
    "نثر: سبق ۶ تا ۱۰ (تشریحات و خلاصہ)",
    "نثر: سبق ۱۱ تا ۱۵ (تشریحات و خلاصہ)",
    "غزلیات: منتخب اشعار کی تشریح",
    "نظمیں: منتخب نظموں کی تشریح",
    "علامہ اقبال کا کلام اور فکر",
    "قواعد: اسم، فعل، حرف اور اقسام",
    "قواعد: محاورات، ضرب الامثال اور تذکیر و تانیث",
    "مضمون نویسی",
    "خط نویسی اور درخواست نویسی",
    "خلاصہ نگاری اور تلخیص",
    "سلیس اردو میں ترجمہ",
  ],

  "syl-isl-12-all": [
    "Unit 1: Quranic Ayat and Their Detailed Translation",
    "Unit 2: Ahadith on Social and Moral Conduct",
    "Unit 3: Seerat-un-Nabi (SAW): Charter of Madinah and Treaties",
    "Unit 4: Islamic System of Worship and Its Objectives",
    "Unit 5: Islamic Concept of Knowledge and Education",
    "Unit 6: Constitutional Development of Pakistan",
    "Unit 7: Economy and Natural Resources of Pakistan",
    "Unit 8: Foreign Policy and International Relations",
    "Unit 9: Challenges Facing Pakistan and Their Solutions",
    "Unit 10: Contribution of Muslim Scientists and Scholars",
  ],
  // ---- Physics (PTB / FBISE national scheme) ----
  "syl-phy-9-sci": [
    "Unit 1: Physical Quantities and Measurement",
    "Unit 2: Kinematics",
    "Unit 3: Dynamics",
    "Unit 4: Turning Effect of Forces",
    "Unit 5: Gravitation",
    "Unit 6: Work and Energy",
    "Unit 7: Properties of Matter",
    "Unit 8: Thermal Properties of Matter",
    "Unit 9: Transfer of Heat",
  ],

  "syl-phy-10-sci": [
    "Unit 10: Simple Harmonic Motion and Waves",
    "Unit 11: Sound",
    "Unit 12: Geometrical Optics",
    "Unit 13: Electrostatics",
    "Unit 14: Current Electricity",
    "Unit 15: Electromagnetism",
    "Unit 16: Basic Electronics",
    "Unit 17: Information and Communication Technology",
    "Unit 18: Radioactivity",
  ],

  "syl-phy-11-fsc": [
    "Chapter 1: Measurements",
    "Chapter 2: Vectors and Equilibrium",
    "Chapter 3: Motion and Force",
    "Chapter 4: Work and Energy",
    "Chapter 5: Circular Motion",
    "Chapter 6: Fluid Dynamics",
    "Chapter 7: Oscillations",
    "Chapter 8: Waves",
    "Chapter 9: Physical Optics",
    "Chapter 10: Optical Instruments",
    "Chapter 11: Heat and Thermodynamics",
  ],

  "syl-phy-12-fsc": [
    "Chapter 12: Electrostatics",
    "Chapter 13: Current Electricity",
    "Chapter 14: Electromagnetism",
    "Chapter 15: Electromagnetic Induction",
    "Chapter 16: Alternating Current",
    "Chapter 17: Physics of Solids",
    "Chapter 18: Electronics",
    "Chapter 19: Dawn of Modern Physics",
    "Chapter 20: Atomic Spectra",
    "Chapter 21: Nuclear Physics",
  ],

  // ---- Biology 11th (PTB, 14 chapters) ----
  "syl-bio-11-fsc": [
    "Chapter 1: Introduction to Biology",
    "Chapter 2: Biological Molecules",
    "Chapter 3: Enzymes",
    "Chapter 4: The Cell",
    "Chapter 5: Variety of Life",
    "Chapter 6: Kingdom Prokaryotae (Monera)",
    "Chapter 7: The Kingdom Protista",
    "Chapter 8: Fungi",
    "Chapter 9: Kingdom Plantae",
    "Chapter 10: Kingdom Animalia",
    "Chapter 11: Bioenergetics",
    "Chapter 12: Nutrition",
    "Chapter 13: Gaseous Exchange",
    "Chapter 14: Transport",
  ],

  // ---- I.Com Principles of Economics (Part 1, 75 marks) ----
  "syl-eco-11": [
    "Unit 1: Introduction to Economics and Basic Concepts",
    "Unit 2: Consumer Behaviour and Utility Analysis",
    "Unit 3: Demand, Supply and Market Equilibrium",
    "Unit 4: Elasticity of Demand and Supply",
    "Unit 5: Theory of Production and Factors of Production",
    "Unit 6: Cost and Revenue Analysis",
    "Unit 7: Market Structures and Price Determination",
    "Unit 8: National Income and Its Measurement",
    "Unit 9: Money, Inflation and Banking",
    "Unit 10: Public Finance and Taxation",
    "Unit 11: Economic Development and Planning in Pakistan",
  ],

  // ---- I.Com Principles of Banking (Part 2, 75 marks) ----
  "syl-bank-12": [
    "Unit 1: Introduction to Banking and Its Evolution",
    "Unit 2: Kinds and Functions of Banks",
    "Unit 3: The Central Bank and State Bank of Pakistan",
    "Unit 4: Commercial Banks: Functions and Balance Sheet",
    "Unit 5: Banker and Customer Relationship",
    "Unit 6: Bank Accounts and Their Operation",
    "Unit 7: Negotiable Instruments: Cheque, Bill of Exchange and Promissory Note",
    "Unit 8: Endorsement and Crossing of Cheques",
    "Unit 9: Letter of Credit and Financing of Foreign Trade",
    "Unit 10: Islamic Banking in Pakistan",
    "Unit 11: Electronic Banking and Modern Banking Services",
  ],

  // ---- English (PTB compulsory scheme) ----
  "syl-eng-9-all": [
    "Book I: Prose Lessons 1-12 (The Saviour of Mankind to Little by Little)",
    "Book III: Poems (The Rain, Night Mail, Sindbad the Sailor)",
    "Grammar: Parts of Speech and Sentence Structure",
    "Grammar: Tenses and Active-Passive Voice",
    "Grammar: Direct and Indirect Narration",
    "Writing: Paragraph and Essay Writing",
    "Writing: Letters, Applications and Stories",
    "Translation: Urdu to English Sentences",
    "Comprehension and Summary Writing",
  ],
  "syl-eng-10-all": [
    "Book I: Prose Lessons 1-13 (Hazrat Muhammad an Embodiment of Justice to Faithfulness)",
    "Book III: Poems (Peace, The Feed, Stopping by Woods on a Snowy Evening)",
    "Grammar: Tenses, Voice and Narration Revision",
    "Grammar: Prepositions, Articles and Punctuation",
    "Writing: Essays and Paragraphs",
    "Writing: Letters, Applications and Dialogues",
    "Translation: Urdu to English Paragraphs",
    "Comprehension, Precis and Summary",
    "Pairs of Words and Idioms",
  ],
  "syl-eng-11-all": [
    "Book III: Short Stories (The Gift of the Magi, The Reward, Clearing in the Sky)",
    "Book III: Short Stories (The Piece of String, Sale, Thank You Ma'am)",
    "Book I: Plays and Prose Selections",
    "Poems: Night Mail, Loveliest of Trees, O Where Are You Going",
    "Grammar and Usage: Tenses, Voice, Narration",
    "Writing: Essay and Paragraph Writing",
    "Writing: Letters, Applications and Dialogue",
    "Precis Writing and Comprehension",
    "Idioms, Pairs of Words and Translation",
  ],

  // ---- Urdu (PTB compulsory scheme) ----
  "syl-urd-9-all": [
    "\u062d\u0635\u06c1 \u0646\u062b\u0631: \u0633\u0628\u0642 1 \u062a\u0627 6",
    "\u062d\u0635\u06c1 \u0646\u062b\u0631: \u0633\u0628\u0642 7 \u062a\u0627 12",
    "\u062d\u0635\u06c1 \u0646\u0638\u0645: \u062d\u0645\u062f\u060c \u0646\u0639\u062a \u0627\u0648\u0631 \u0645\u0646\u0638\u0648\u0645\u0627\u062a",
    "\u063a\u0632\u0644\u06cc\u0627\u062a \u0627\u0648\u0631 \u062a\u0634\u0631\u06cc\u062d",
    "\u0642\u0648\u0627\u0639\u062f: \u0627\u0633\u0645\u060c \u0641\u0639\u0644\u060c \u062d\u0631\u0641",
    "\u0645\u0636\u0645\u0648\u0646 \u0646\u06af\u0627\u0631\u06cc",
    "\u062e\u0637 \u0646\u0648\u06cc\u0633\u06cc \u0627\u0648\u0631 \u062f\u0631\u062e\u0648\u0627\u0633\u062a",
    "\u0645\u062d\u0627\u0648\u0631\u0627\u062a \u0627\u0648\u0631 \u0636\u0631\u0628 \u0627\u0644\u0627\u0645\u062b\u0627\u0644",
  ],
  "syl-urd-10-all": [
    "\u062d\u0635\u06c1 \u0646\u062b\u0631: \u0633\u0628\u0642 1 \u062a\u0627 7",
    "\u062d\u0635\u06c1 \u0646\u062b\u0631: \u0633\u0628\u0642 8 \u062a\u0627 14",
    "\u062d\u0635\u06c1 \u0646\u0638\u0645: \u062d\u0645\u062f\u060c \u0646\u0639\u062a\u060c \u0645\u0646\u0638\u0648\u0645\u0627\u062a",
    "\u063a\u0632\u0644\u06cc\u0627\u062a \u0627\u0648\u0631 \u062a\u0634\u0631\u06cc\u062d",
    "\u0642\u0648\u0627\u0639\u062f \u0648 \u0627\u0646\u0634\u0627",
    "\u0645\u0636\u0645\u0648\u0646 \u0646\u06af\u0627\u0631\u06cc",
    "\u062e\u0637 \u0646\u0648\u06cc\u0633\u06cc \u0627\u0648\u0631 \u06a9\u06c1\u0627\u0646\u06cc",
    "\u0645\u062d\u0627\u0648\u0631\u0627\u062a\u060c \u0636\u0631\u0628 \u0627\u0644\u0627\u0645\u062b\u0627\u0644 \u0627\u0648\u0631 \u062a\u0631\u062c\u0645\u06c1",
  ],
  "syl-urd-11-all": [
    "\u0633\u0628\u0642 \u0622\u0645\u0648\u0632 \u0646\u062b\u0631 \u067e\u0627\u0631\u06d2 (\u062d\u0635\u06c1 \u0627\u0648\u0644)",
    "\u0633\u0628\u0642 \u0622\u0645\u0648\u0632 \u0646\u062b\u0631 \u067e\u0627\u0631\u06d2 (\u062d\u0635\u06c1 \u062f\u0648\u0645)",
    "\u063a\u0632\u0644\u06cc\u0627\u062a: \u0645\u06cc\u0631\u060c \u063a\u0627\u0644\u0628\u060c \u0627\u0642\u0628\u0627\u0644",
    "\u0646\u0638\u0645\u06cc\u0627\u062a \u0627\u0648\u0631 \u062a\u0634\u0631\u06cc\u062d",
    "\u0627\u0642\u0628\u0627\u0644\u06cc\u0627\u062a",
    "\u0642\u0648\u0627\u0639\u062f: \u062a\u0630\u06a9\u06cc\u0631 \u0648 \u062a\u0627\u0646\u06cc\u062b\u060c \u0648\u0627\u062d\u062f \u062c\u0645\u0639",
    "\u0645\u0636\u0645\u0648\u0646 \u0646\u06af\u0627\u0631\u06cc \u0627\u0648\u0631 \u062e\u0644\u0627\u0635\u06c1",
    "\u062e\u0637 \u0646\u0648\u06cc\u0633\u06cc \u0627\u0648\u0631 \u062f\u0631\u062e\u0648\u0627\u0633\u062a \u0646\u0648\u06cc\u0633\u06cc",
  ],
};

/** Number of syllabus entries corrected by this file. */
export const CORRECTED_COUNT = Object.keys(CHAPTER_LISTS).length;
